### ISSUE TITLE
Taskbar is always visible when overlay is active

### ISSUE THREAD

**Issue by knix15** [ciribob/DCS-SimpleRadioStandalone#103]
Pic attached
![1](https://cloud.githubusercontent.com/assets/22006007/18249242/5f85687a-737d-11e6-9180-21f86979da49.png)

DCS version 1.5.4.55952
Simple Radio Stadalone version 1.2.2.0 (tried with previous as well, same result)
OS: Windows 10 Pro 64 bit

Steps:
1. Start SRS
2. Connect to server
3. Open radio overlay
4. Start DCS

Result:
Taskbar stays always visible

Desired result:
Taskbar disappears

I tried (without success):
-one monitor / two monitor setup
-run DCS as admin (SRS always runs as admin)
-first run DCS then start SRS
-switch mods off
-graphics / full screen with on/off
-using windowed borderless gaming software
-close every other software, stop unneeded services, stop antivir, stop everything with overlay (nvidia, asus suite)
-run srs with all compatibility mode

Workaround (only with 2 screens):
Overlay on second screen causes taskbar to disappear on first screen.

**Comment by ciribob** [comment]
Thanks for the report. I've tried to replicate but cant...

Same Windows - Single Screen only but below is a link showing the test:

https://gfycat.com/PowerfulJovialDwarfrabbit

As soon as I interact with the DCS window, the toolbar disappears which is the correct behaviour. Alt-Tabbing to DCS will also remove the tool bar as it should only be there while you interact with the overlay.

I'm guessing Alt+Tab and interacting with DCS didn't clear the bar for you?

**Comment by knix15** [comment]
Unfortunately alt+tabbing didn't help, and alt+entering made the overlay dissapear completely. If you have any idea I should try, please don't hesitate to write. Thanks.

**Comment by knix15** [comment]
Updated first post. Can I give you any more info, to help figure it out?

**Comment by mvee** [comment]
This might be a stupid question but is the taskbar on top if the SRS is not runing?

**Comment by knix15** [comment]
As soon as I minimize or close or drag to second screen the SRS overlay, the taskbar disappears.

**Comment by Nossarian** [comment]
This may only be possible on multi-screen setups. I've had this issue occur as well, and a few members of my group have had it occur.

**Comment by knix15** [comment]
It happens as well when I set the Windows to one screen only. Should I also unplug the second screen?
Oh, my friend get the same bug, and he has only a one screen setup.

**Comment by Nossarian** [comment]
What other processes do you have running in the background? Is there another program that uses an overlay, even if it's not enabled for DCS?

**Comment by knix15** [comment]
Yes, Geforce Experience and Asus Suite, but I killed the processes and stopped the services. Same thing happens.
(oh and maybe the mumble, but it didn't run and doesn't have services)

**Comment by Nossarian** [comment]
Do you use Discord or Teamspeak?

**Comment by knix15** [comment]
Ofc, Teamspeak.

**Comment by Nossarian** [comment]
I would recommend shutting down every other application and seeing if the issue still occurs. It helps to know if it isn't due to compatability issues.

**Comment by knix15** [comment]
Yes, that was my best guess as well, but even if I close and stop everything, the problem still occurs. Anyway, I will try it again if I get home.

**Comment by ciribob** [comment]
Let me know if its still happening after turning all the other programmes off.

I can try making a version that removes the task bar item for it but that might not work.

**Comment by knix15** [comment]
Thanks, I'll test it today evening. Yesterday I couldn't make it.

**Comment by knix15** [comment]
I tried again, literally nothing ran just dcs and srs, and the taskbar still remained in front.
![image](https://cloud.githubusercontent.com/assets/22006007/18310483/f0692098-74fe-11e6-977f-c00e600fb73a.png)

**Comment by Wh00kiE** [comment]
Hi,
I have the same issue here with one display. I stopped/disabled the unnecessary processes/services, but the taskbar is always visible when I turn the radio overlay on. When I hit ALT-Enter to switch DCS into full screen mode then I can not see the overlay anymore - this time when I'm using the toggle button nothing happening -, just when I use alt-tab and switch back to window mode.

pic attached.
![simpleradioissue](https://cloud.githubusercontent.com/assets/22053580/18313634/eac8d71c-750f-11e6-960f-3dc5dbc42684.png)

**Comment by Nossarian** [comment]
Is your taskbar locked?

**Comment by knix15** [comment]
Yes, mine is locked.

**Comment by Wh00kiE** [comment]
locked or unlocked, all the same.

**Comment by ciribob** [comment]
[SR-Client-NoTaskbarIcon.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/460071/SR-Client-NoTaskbarIcon.zip)
Try this version.

Make sure you alt-tab or click on the DCS window after opening the radio and focus should be returned. 

This version removes the taskbar item for the overlay so this might fix it? I don't understand why this is happening as Windows is behaving incorrectly according to the documentation.

Sorry for the issue. I run only one screen on Windows 10 and can't replicate no matter what I do

**Comment by knix15** [comment]
C'mon man, you are genius. Bugfixing in DAYS, just for the community. I would like to donate you, please tell me I can.

![image](https://cloud.githubusercontent.com/assets/22006007/18324194/889f2c54-753b-11e6-84ec-3efff0fd53cc.png)

**Comment by ciribob** [comment]
Don't worry about donation. Just say thanks on the forums and help others with getting it setup is thanks enough :)

Glad its fixed, sorry for the issue and hopefully others who haven't posted will be happy too  👍

**Comment by knix15** [comment]
Thanks again then.
Btw there's a case when the overlay spanws outside the screen. But no more taskbar icon appears, so have to do a trick:
https://superuser.com/questions/53585/how-to-move-windows-that-open-up-offscreen

here's the howto

**Comment by ciribob** [comment]
ah if that happens, there's a reset button in settings at the bottom as well :)

**Comment by Wh00kiE** [comment]
Thanks man, it's working! :) Keep on update and develop, you are doing great! :)
