### ISSUE TITLE
Reports of High-latency and voice quality drop

### ISSUE THREAD

**Issue by Nossarian** [ciribob/DCS-SimpleRadioStandalone#105]
Members of my group, the 924th, have reported issues with SimpleRadio recently.

I will be looking into it when we get the chance, but I'm willing to bet it's something user related at the moment.

Will update with any information for posterity.

**Comment by ciribob** [comment]
Odd, latency should be around 0.5 seconds at most as long as you've got a relatively low ping.

I'd ask them to check the services listed here: https://forums.eagle.ru/showpost.php?p=2885040&postcount=631

And also do a ping to the server to look for packet drop or general issues with routing

I'll have a think!

**Comment by ciribob** [comment]
Any issues they experienced might also be fixed in the new release from today. Let me know :)
