### ISSUE TITLE
Auto-connect to current server by sniffing out currently connected server IP

### ISSUE THREAD

**Issue by silentwarrior** [ciribob/DCS-SimpleRadioStandalone#117]
Hello.

Could you please implement auto-connect to the correct SimpleRadio server?

So that, we start SimpleRadio, click toggle button like "AutoConnect", and it would sniff out the server we are connecting to and connect to the correct SimpleRadio server automatically instead of us having to find out the correct IP, each time we change servers.

Implementation details options :
1 - Each server would register with you its own IP and associated SimpleRadio IP (you would need a simple script running somewhere with this information or a public pastebin that only you can change and they would register their servers with you)
2 - Each server would have, in its description a pre-formatted string like "SimpleRadio Server: 123.123.123.123" and you would parse this out.
3 - Each time we connect to a server and then manually connect to that server it would keep a matching list of "dcs server" -> "simple radio server"
4 - We manually create a list, within simple radio, with "dcs server" -> "simple radio server", just like TS3 bookmarks that simple radio then uses for auto-connect.

Let me know if this sounds too complicated. 
I believe option 2 would be the best possible implementation for all parties involved and would give that extra boost to Simple Radio adoption.

Thank you for your amazing software :)

**Comment by ciribob** [comment]
Option 2 (ish) is already implemented :)

If you connect to the BuddySpike server or any TAW server as well as a few others, your SimpleRadio will auto connect.

Server admins have to place a special LUA file in their Scripts folder and put in the SimpleRadio IP and thats it.

On switching slots you receive a chat message which contains the IP and tells SRS to autoconnect 

Video here: https://www.youtube.com/watch?v=_dnK4oVUNuU The accept window is now off by default for true auto connect.

**Comment by silentwarrior** [comment]
Awesome @ciribob really good feature.

Not sure I did not notice it before :)
