### ISSUE TITLE
DCS Simple Radio Stoped Working

### ISSUE THREAD

**Issue by WaffenPL** [ciribob/DCS-SimpleRadioStandalone#119]
Hi, after a updtae to 1.2.8 version when trying to connect or tryin gto preview audio app crashes...
was fine in 1.2.6.

**Comment by ciribob** [comment]
Please post your client logs

**Comment by ciribob** [comment]
Please also try the fix here: https://forums.eagle.ru/showpost.php?p=2921938&postcount=866

**Comment by WaffenPL** [comment]
Problem solved, net framework need update.


2016-10-09 9:30 GMT+01:00 Ciaran Fisher <notifications@github.com>:

**Comment by ciribob** [comment]
Great! Glad to hear.

**Comment by WaffenPL** [comment]
yeah, your app is awesome mate, great job.

2016-10-09 11:39 GMT+01:00 Ciaran Fisher <notifications@github.com>:
