### ISSUE TITLE
SRS client process closing when clicking "preview audio"

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#120]
So this is crashing the program.

**Comment by ciribob** [comment]
Please post your client logs

**Comment by ciribob** [comment]
Please also try the fix here: https://forums.eagle.ru/showpost.php?p=2921938&postcount=866

**Comment by Tomcatz315** [comment]
I have the same issue. Tried uninstalling and reinstalling. Tried multiple audio inputs/outputs. Tried forcing audio quality through windows. Still crashes when previewing audio or connecting to server. 


i7-3770K@4.5
32GB Corsair Dominator DDR3-1866
EVGA GTX 970SSC
Creative SB XFi Recon 3D
Windows 7
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/518378/clientlog.txt)

**Comment by ciribob** [comment]
Please try the offline .net update first to bring it to 4.6.2 https://www.microsoft.com/en-us/download/details.aspx?id=53344

And then try the updated build here:  https://forums.eagle.ru/showpost.php?p=2922144&postcount=875

**Comment by Tomcatz315** [comment]
That fixed it. Thank you.

**Comment by ciribob** [comment]
Which one?  Update .net or new build 

Glad its working 👍

**Comment by Tomcatz315** [comment]
Both

**Comment by ST6Daniel** [comment]
FIXED by just using latest SRS build!

**Comment by ST6Daniel** [comment]
Well fixed for me, but for Tomcatz too?
