### ISSUE TITLE
Spelling mistake "AWACS" instead of "awac"

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#121]
what title says, that button as spelling mistake.

**Comment by ciribob** [comment]
Fixed in #127

**Comment by 132nd-etcher** [comment]
@ST6Daniel can you elaborate ? "awac" does not exist, while "AWACS" is the acronym of "Airborne Warning And Control System"

I think it should read "AWACS".
