### ISSUE TITLE
Bug - SRS not remembering selected output device when closing and restarting SRS

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#123]
So, launching SRS there is my screen speakers selected as audio output ("BenQ GL2440H-C(NVIDIA High Definition Audio)" via HDMI) when selecting "Headset" output it works, but setting is not saved instantly/on closing program. (When restarting it is "BenQ..." again)

**Comment by ciribob** [comment]
Setting is only saved on successful connect at the minute - Try that and let me know

**Comment by ST6Daniel** [comment]
aaaah working!!! Sorry, expect it to save instantly when changing audio device :P sry
