### ISSUE TITLE
"auto connect prompt" not working?

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#124]
Assuming this means that SRS would autoconnect to server on start, this isn't working currently?

**Comment by ciribob** [comment]
the prompt is off by default, check the settings to turn it back on - it works :)

**Comment by ST6Daniel** [comment]
No, maybe this is a feature that really needs .NET 4.6.2 ? I turned it on but no autoconnect.

**Comment by ciribob** [comment]
Auto connect is not running on every server. Just BuddySpike and TAW AFAIK. What server did you test on?

**Comment by ST6Daniel** [comment]
Buddyspike OP Blue Flag Round 9

**Comment by ciribob** [comment]
I'll retest but it worked for me earlier

**Comment by ST6Daniel** [comment]
Aaaaah got it!!! ONLY working when SRS running BEFORE starting DCS game!!!

**Comment by ciribob** [comment]
it doesnt actually matter if you run it after. its just triggered when switching slots 👍

**Comment by ST6Daniel** [comment]
👍
