### ISSUE TITLE
Feature request - snap windows to screen borders

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#126]
Would be cool if you can make it like Steam, when any window border reaches a position that is 20 pixels near a border the window will auto snap onto the border the operations (for FHD and 1050p) would be

IF top left window corner X + Y= 20 pixels
then snap top left window corner to X + Y = 0

IF bottom left window corner X = 20, Y = 1060 (Y =1030 for 1680x1050 res)
then snap bottom left window corner to X = 0, Y =1080 (Y =1050 for 1680x1050)

IF top right window corner X = 1900, Y = 20 (X=1660 for 1680x1050)
then snap top right window corner to X = 1920, Y = 0 (X =1680 for 1680x1050)

IF bottom right window corner X = 1900, Y = 1060 (X =1660, Y 1030 for 1680x1050)
then snap bottom right window corner to X = 1920, Y =1080 (X = 1680, Y = 1050 for 1680x1050)

**Comment by ciribob** [comment]
Not sure what the use of this would be? The overlay is in DCS or on a second monitor so not sure where it would snap too?

**Comment by ST6Daniel** [comment]
Yes on the border of my 2nd screen so I have other windows there too (Teamspeak, Buddyspike gadget, Steam friendslist, ... )

**Comment by ciribob** [comment]
For now no, unless you want to have a go at implementing? It seems a lot of effort for little gain

**Comment by ST6Daniel** [comment]
Is it more effort than "if ... then" like in Java ? (That's the only language I learned and that was 5 years ago...)

**Comment by ciribob** [comment]
Yes it is more effort than that.

If you can program Java, you can do C#. This project is how I learnt C# from just knowing Java.

Closing for now but as I say feel free to work on it and send me a pull request.

**Comment by ST6Daniel** [comment]
Ok I found this online:

this goes into the form class:

 ```
protected override void WndProc(ref Message m) {
        const int WM_NCCALCSIZE = 0x83;
        if (m.Msg == WM_NCCALCSIZE && m.WParam.ToInt32() == 1) {
            m.Result = new IntPtr(0xF0);   // Align client area to all borders
            return;
        }
        base.WndProc(ref m);
    }
```

And then we have to set "FormBorderStyle" back to None and make the constructor of the Form look like this:

```

  public Form1() {
        InitializeComponent();
        var designSize = this.ClientSize;
        this.FormBorderStyle = FormBorderStyle.Sizable;
        this.Size = designSize;
    }
```

Source:

http://stackoverflow.com/questions/30421288/how-do-i-snap-a-borderless-form-to-the-edges-of-a-screen

**Comment by ciribob** [comment]
Not using win forms, using  Wpf. :)

Download visual studio, checkout the code and have a go. Best way to learn!

**Comment by ST6Daniel** [comment]
Why WPF instead of WF ?

Then this shoul be the solution: http://stackoverflow.com/questions/22157704/how-to-automatically-snap-a-wpf-window-to-an-edge-of-the-screen-while-retaining

**Comment by ciribob** [comment]
Windows forms is old. Wpf is the new technology.

As I say, fork the project. 

Make the edits in visual studio.

Test it and send me the finished code, not random snippets :)

**Comment by ST6Daniel** [comment]
Ok will try when I'm motivated xD but as more code causes higher energy usage (RAM, CPU, HDD) let's leave SRS as energy efficient as possible for now... :)
