### ISSUE TITLE
Why saying NET 4.6.2 is required when I run it fine with 4.6.1 ? (Or is Win 10 different from Win 7?)

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#128]
Yeah wondering why you say it's requirement when I have no problems with 4.6.1 ?

**Comment by ciribob** [comment]
I'm targeting 4.6.2

Why it works for you i'm not sure but there is no harm in having the latest version.... 👍

**Comment by ST6Daniel** [comment]
Ok as soon as I get problems I'll get 4.6.3 ! 👍
