### ISSUE TITLE
Bindings unresponsive

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#13]
For an unknow reason the key HKEY_CURRENT_USER\SOFTWARE\DCS-SimpleRadioStandalone was not created and the bindings do not map. I compared it to a successful installation on a different computer and permissions do match. All software is installed on default locations and export.lua is valid.

I copied the key from the working installation and I was able to use those bindings but not change em.

**Comment by ciribob** [comment]
Sorry for the slow reply, still unable to replicate but someone else is also having this issue in the linked issue.

Did you manage to solve it completely?

**Comment by mvee** [comment]
No not yet. I'd like to say that it is permission related, but other
options are written to registry such as effect or no effect, audio settings
and server name.

I have a workaround that I mapped warthog on a different computer and the
copied the key to the one with the issues. Both machines are Win10.

Only export in addition used on both computers is Tacview, so not related
game connection either.

If you want we could think of this in TS3 or such. Later today or tomorrow
maybe.
9.7.2016 14.24 "Ciaran Fisher" <notifications@github.com> kirjoitti:

Sorry for the slow reply, still unable to replicate but someone else is
also having this issue in the linked issue.

Did you manage to solve it completely?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/13#issuecomment-231529585>,
or mute the thread
<https://github.com/notifications/unsubscribe/AQuHGxwovv8PN2XqHGm0Vof_ZWp6jRItks5qT4T1gaJpZM4Ix34d>
.

**Comment by ciribob** [comment]
I might be around on the buddyspike TS later, feel free to message me again! :)

Would you mind posting a list of USB devices here: #30 

Maybe there will be something common and then I can fix it.

**Comment by ciribob** [comment]
Workaround in #30
