### ISSUE TITLE
Feature Request: Allow overlay comms (e.g. AWACS) without being in DCS (e.g. for use with LotATC)

### ISSUE THREAD

**Issue by HomeFries94** [ciribob/DCS-SimpleRadioStandalone#131]
Just a request to allow the overlay to govern radio frequencies in lieu of DCS Export.  Useful with LotATC (which doesn't require DCS to even be on the system, much less running).  This allows for integrated ATC and AWACS support.

Implementation: either have a checkbox in the overlay to supersede export.lua, or automatically supersede as long as DCS is not running.  Can disable server side if cheating or spamming is a concern.

**Comment by Quax456** [comment]
This would be a much better solution than the foreward Observer.
Shure I'm an owner of LotATC but its relay cool to control the combat, isn't it?

**Comment by ciribob** [comment]
Exactly as you describe is how I've been toying with implementing it.

The most important part being the server side control which'll be off by default

The main reason I haven't is there is no way of guaranteeing you're on one side or the other so if a server allows this, it'll also have to allow spectator audio and turn off coalition security which might confuse people.

**Comment by szporwolik** [comment]
I came here just to put this feature request in only to find out it's already here. :) 

@ciribob please - runing the LotATC + DCS Simpleradio without need to run DCS would be a great deal for the community, please think about. If PvP mission are concern maybe for the beginning just put the On/Off option on the server to allow/disallow direct connections.

Guys from LotATC are handling it with the simple config file allowing to set seperate (hidden at the server) passwords for RED and BLUE. 

Please think about - as mentioned, this would be a great game changer for most of us ATC guys. 👍

**Comment by MorpheusXAUT** [comment]
I definitely like the side-password idea, should be pretty straight forward to implement. Not direct LotATC integration for the beginning, but making SRS usable without DCS running as a start (if enabled on the server).

I'll be looking into this in the next days.

**Comment by MorpheusXAUT** [comment]
First version done and to be released as a beta version for testing in the near future 😃

**Comment by szporwolik** [comment]
Dude, that's a really great news - thank you for all the effort! :)

**Comment by MorpheusXAUT** [comment]
A `beta` version containing this feature has been release - if you're using the [1.5.3.1](https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.5.3.1) prerelease, you'll be able to try it out before the final `stable` release, be aware that you will not be able to use the `1.5.3.1` server with older clients or the other way around.
Any feedback would be highly appreciated!

**Comment by ciribob** [comment]
in latest release 1.5.3.2

**Comment by HomeFries94** [comment]
Thanks for this!
