### ISSUE TITLE
[BUG] "do you want to connect to xyz ???" Pop-up triggered under wrong condition

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#132]
For some reason this window opens several times when playing, although it should only open once on program startup.

**Comment by ciribob** [comment]
It will be triggered every time you switch slots until you're connected to a server. Was it the auto connect prompt you saw?

**Comment by ST6Daniel** [comment]
Yeah and it was a tad annoying when I was DISCONNECTED on purpose for a while then played long they back to desktop and had 5 of those windows behind each other. :P

**Comment by ciribob** [comment]
I'm going to close as the idea for the auto connect is it connects you. If you don't want to then I'd just close SimpleRadio (as you're not using it?)
