### ISSUE TITLE
FEATURE REQUEST: Overlay to appear in the Rift

### ISSUE THREAD

**Issue by 333VFGSpecter** [ciribob/DCS-SimpleRadioStandalone#133]
this would be a great benefit as currently there is no way apart from audio position within your headset to identify what channel is what

**Comment by ciribob** [comment]
Without a Rift I've no way to work on this. Sorry...

**Comment by 333VFGSpecter** [comment]
stick up a donation page for the work you have been doing with SR, i am sure the community would donate mate

**Comment by ciribob** [comment]
ok added one to the main page.
