### ISSUE TITLE
Can't map hotkey with USB Joystick Board

### ISSUE THREAD

**Issue by 132nd-etcher** [ciribob/DCS-SimpleRadioStandalone#134]
Hi !

My friend's using a [USB Joystick Board](http://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=94&products_id=180), and he can't map the Dx output in SR "Control" page.

The board appears in Windows as a valid DirectX device with 32 Dx buttons. Also, it's used DCS, where they are recognized as Dx buttons as well.

Does anyone have any idea what could be the issue ?

**Comment by ciribob** [comment]
If you post their logs I can add it to the white list if you tell me which device it is at the start of the logs.

The DX devices are filtered by type as I had issues where a mouse reported as a generic device which then caused issues when I tired to access the buttons...

**Comment by 132nd-etcher** [comment]
Oooooh, I see ! I understand why you'd do that. 

I will get back to you with this information ASAP.

In the meantime, do you think it would be a good idea to add the Cougar MFDs ? Here's the ID:
```
Found b351044f-0000-0000-0000-504944564944 Instance: aef85240-76d5-11e6-8003-444553540000 F16 MFD 1 Usage: Generic
Found b352044f-0000-0000-0000-504944564944 Instance: aef85240-76d5-11e6-8004-444553540000 F16 MFD 2 Usage: Generic
```

Cheers !

**Comment by 132nd-etcher** [comment]
Here's the full log: http://pastebin.com/s1jA2wxC

I *think* the relevant lines are those two:

```
Found 11431dd2-0000-0000-0000-504944564944 Instance: 4d8f04b0-1d4b-11e6-8001-444553540000 Button Box Interface 3 Usage: Generic
Found 11411dd2-0000-0000-0000-504944564944 Instance: 4d9bfd00-1d4b-11e6-8006-444553540000 Button Box Interface 2 Usage: Generic
```

What's strange is that this one is added no problem (that's the UBX itself):
```
Adding 22011dd2-0000-0000-0000-504944564944 Instance: 4db3f1d0-1d4b-11e6-800f-444553540000 BU0836X_1
```

**Comment by ciribob** [comment]
The UBX works because it reports as a joystick apparently (http://www.leobodnar.com/shop/index.php?main_page=product_info&products_id=180)

I'll add an option to settings that expands the checks to allow more devices through. If theres an issue you can then just turn it off and report :)

**Comment by 132nd-etcher** [comment]
Sweet ! =)

Is there any way for the end user to white-list a device by UID ? The pal who's having the problem isn't the most tech-savvy guy in the world and I don't have access to his rig (he lives far, far way from me) so there's not much I can do to really pinpoint what's going on. I was thinking some file containing UID read at the client startup could do wonders in this case.

BTW, SR is awesome, I'm getting a lot of people onbard and haven't had any real issue yet getting it up and running, kudos for that man !

[Totally unrelated issue, but now that I have you here: I spent an hour and a half looking into it earlier on to no avail this afternoon, is there any way to tweak the radio effect ? For some reason, some of us are getting so distorted that there's no way to understand what they're saying, even if they're sitting on the parking next to the rest of the group. This is an on and off thing, I haven't been able to find the cause yet.]

**Comment by ciribob** [comment]
No option, just a binary on off setting at the bottom of the settings section. Should hopefully be easy for your buddy to find. Most important thing is after setting it you have to restart SRS for the setting to take effect.. Hopefully should just work.

A Window will popup and alert you anyway about restarting

If they're very distorted its probably because they've put their microphone boosts up too high.

This post here shows two examples - How it should sound and how it'll sound if you go crazy with the boost as well as some more info:

https://forums.eagle.ru/showpost.php?p=2923306&postcount=906

**Comment by 132nd-etcher** [comment]
Microphone boost was at default for everyone, we set it way down to mitigate the issue. "Audio preview" is crystal clear, but the output for the remote client is barely comprehensible at best. Do you want me to start another issue on the subject ? I can start running test sessions with the guys.

Anyway, my apologies for the digression, back to the UBX issue: I'm sure we'll be able to fix his issue with the new option =) I thought it'd be nice to have the possibility of adding some specific UID "on-the-fly" for debugging similar issues later on, and parsing a text file at startup to add a bunch of str to the filter shouldn't be too much of a hassle.

It doesn't really matter, thanks very much for the awesome and lightning-quick support !

**Comment by ciribob** [comment]
If you can, open a seperate issue and get recordings of them all. If its clear for preview it should be fine for receiving on others unless you all have different speaker boosts. Does the garbled noise sound like the example i linked?

I'd recommend you probably stick all mics at -50%, speaker boost at 0% and use the windows audio mixer to boost the volume or balance with respect to DCS and teamspeak as it'll give you all more consistent results when trying to work our why some are distorted.

If your using a mix of the old api and the new it makes it trickier as the boost settings for those will be different as well

no worries, glad i can help 👍

**Comment by ciribob** [comment]
Try the new testing release, it should work for your friend once you turn on the new setting

**Comment by gillesdrone** [comment]
Hi , thank's for you work , it's for me that Etcher make  request for inputs .
I test now but the option :  "allow more  input devices " don't save after  simple radio restarted ... 
and devices not effective

**Comment by ciribob** [comment]
Ok

**Comment by gillesdrone** [comment]
I select 3 options to test
![avant](https://cloud.githubusercontent.com/assets/22989031/19637018/12766b9e-99cd-11e6-8e48-f4b5dff3cbbe.jpg)

after restart 
![apres](https://cloud.githubusercontent.com/assets/22989031/19637020/171cd642-99cd-11e6-9160-d693bec32baa.jpg)
thank's for you speed answer ;)

**Comment by 132nd-etcher** [comment]
Hey there @gillesdrone ! Let me know if I can help translate or anything else =)

**Comment by ciribob** [comment]
Ok, the setting that you selected before restart saves but doesn't show after restarting (but it is on).

You'll have to use the log messages to see what it's doing. 

If you post your client logs once you've turned it on and restarted it I can tell you if it should work or not

**Comment by gillesdrone** [comment]
@Etcher , that's good for me my english is enought for thid call ;) thank's

@ciribob my log after restart and select option 
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/547204/clientlog.txt)

**Comment by ciribob** [comment]
I'll have a look tonight or tomorrow evening and put a new release here once its fixed. Thanks for testing

**Comment by gillesdrone** [comment]
ok thank's for your help , :)

**Comment by ciribob** [comment]
OK try this one attached. Setting should save and also actually work. :)
[DCS-SimpleRadioStandalone-Expand-Devices.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/551708/DCS-SimpleRadioStandalone-Expand-Devices.zip)

**Comment by gillesdrone** [comment]
I test now and the setings are saved it's ok But it's not possible to put BU0836X on the controls :( 
i send log 
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/552568/clientlog.txt)

**Comment by ciribob** [comment]
Are you sure it was on for those tests and you restarted after turning on?

I cant see any log messages saying expanded device added and your device was definitely ignored.

Could you delete your client logs, toggle the setting off and then on and then restart SRS and send me the logs again?

**Comment by ciribob** [comment]
Ah totally my fault, sorry! Will try to make a build tonight

**Comment by ciribob** [comment]
Try this one. Fingers crossed 👍 

[DCS-SimpleRadioStandalone-ExpandControls-V2.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/554311/DCS-SimpleRadioStandalone-ExpandControls-V2.zip)

**Comment by gillesdrone** [comment]
ok that's Good thank's :)  ;)

**Comment by ciribob** [comment]
its working?

**Comment by 132nd-etcher** [comment]
Yes, we just did some testing and the result were conclusive. Thanks a lot for the fix ! :+1:

**Comment by ciribob** [comment]
Great! This'll be part of the next main release. Thanks for testing

**Comment by 132nd-etcher** [comment]
Pleasure ! Don't hesitate to call on us if you ever need something tested in the future =)

**Comment by gillesdrone** [comment]
Hi , yes its working after test with Etcher and other pilots
