### ISSUE TITLE
Sound is awfully garbled For Some Received Transmissions

### ISSUE THREAD

**Issue by 132nd-etcher** [ciribob/DCS-SimpleRadioStandalone#137]
[Discussion started in #134]

All tests were done with a session of 6 clients, hosted on a server with an down/up bw of 100Mbps / 12Mbps.

All clients running the latest 1.2.8.1 version with the new sound API.

I forgot to enforce latest .NET framework installation during the group setup.

Some clients were absolutely crystal clear at all time, others were so garbled it was impossible to understand a single word.

Local "Audio preview" function reported crystal clear audio for everyone.

The strange thing is that one particular client was garbled for a second client, and wasn't for a third client, regardless of actual separation in the DCS World.

For the purpose of the test, all "realism" options were deactivated server-side and client-side

Lowering "Microphone boost" _did_ help in my particular case, but I didn't know it was the recommended fix so I did not advocate it amongst the group.

Quote from @ciribob :

> I'd recommend you probably stick all mics at -50%, speaker boost at 0% and use the windows audio mixer to boost the volume or balance with respect to DCS and teamspeak as it'll give you all more consistent results when trying to work our why some are distorted.

I will enforce .NET FW installation next time, and I'll have everyone tinker with their mike boost during future sessions. I'll report back the results here.

Cheers =)

EDIT: [linked answer from @ciribob on ED forums](https://forums.eagle.ru/showpost.php?p=2923306&postcount=906)

**Comment by ciribob** [comment]
Hopefully its just microphone boost as that fixed it for you! 👍 

Awaiting results, thanks for the help :)

**Comment by 132nd-etcher** [comment]
Wasn't able to perform a full-scale test due to latest test version being a bit itchy with one particular client. Initial tests results with adjustments to both mike & speaker boost volume were, however, promising. Will keep you posted when the installation issue's fixed !

**Comment by ciribob** [comment]
Is it ok to close? Did it work for everyone in the end?

**Comment by 132nd-etcher** [comment]
Yes, this issue was systematically fixed by lowering the microphone boost.

If I may, I would like to suggest lowering the default value to at least -50% (or setting the 0 there on the slider scale). For most of us, the sweet spot was between -60% and -80%.

Thanks a lot for your help ! :+1:

**Comment by ciribob** [comment]
No worries, thanks for confirming! :)
