### ISSUE TITLE
Synchronize audio output/recording device with system settings

### ISSUE THREAD

**Issue by theendsofinvention** [ciribob/DCS-SimpleRadioStandalone#142]
One of us is frequently changing its default output/capture device in Windows.

It would be nice to have an option to have SR synchronize with that setting at startup.

Would it be possible ?

**Comment by ugene143** [comment]
It is possible to get the default device with the MMDeviceEnumerator.
`var activeDevice = deviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Capture, `

I created a fork&branch to test it:
https://github.com/ugene143/DCS-SimpleRadioStandalone/tree/audio_devices_gui

**Comment by ciribob** [comment]
Thanks @ugene143 

At some point i'll merge this in so you can configure it to take the defaults from windows OR remember your settings

**Comment by etcher-be** [comment]
I'm happy with closing this one.

**Comment by ciribob** [comment]
Implemented - better late than never!
