### ISSUE TITLE
Option for constant transmission

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#15]
Option for constant transmission, I'd use it for internet radio or real time ATC. Just for fun.

ps. sorry for flooding your issues

**Comment by ciribob** [comment]
Implement this my making hotkey toggle instead of push and hold

**Comment by mvee** [comment]
I'm getting this with the newest version, but I don't think it's intentional :D So radio selector seems to be hot-mic'ing

**Comment by ciribob** [comment]
Ah just reset all your keybinds and rebind and then it'll be fine :)

**Comment by destotelhorus** [comment]
@mvee it's been 4 years, but I changed DATIS code a bit to make exactly that happen.
Get liveatc or radio stations into DCS:
https://github.com/destotelhorus/DATIS

**Comment by ciribob** [comment]
Supported by the External Audio system now
