### ISSUE TITLE
Win 7 - doesn t launch

### ISSUE THREAD

**Issue by Jekar** [ciribob/DCS-SimpleRadioStandalone#152]
After install, i try to launch the client, but nothing happens.
No error in logs.

Any clue?

**Comment by ciribob** [comment]
Did you run the installer first after extracting everything out of the zip?

If so try that, if not:

Run as Admin

Install:

.NET https://www.microsoft.com/en-gb/download/details.aspx?id=53345

If you're on Windows N edition (No media components installed) then install this - https://www.microsoft.com/en-gb/download/details.aspx?id=48231

**Comment by Jekar** [comment]
Hi
Installing .NET works !
I was sure to already have it.
But it s launching now, just have to try to communicate with someone :)

Thanks
Regards
Jerome

**Comment by ciribob** [comment]
Great!
