### ISSUE TITLE
Selecting active radio in the Ka50

### ISSUE THREAD

**Issue by 132nd-etcher** [ciribob/DCS-SimpleRadioStandalone#153]
In the Ka50, active radio is selected with the SPU9 rotary knob.

That is mighty fine for the people who are willing to tweak their DCS install a tad and get a improved shortcut scheme to actually control the SPU9 without having to click it every time they want to change frequency.

However, trying to get as many people on board as possible, include less tech-savvy ones, poses a challenge.

Do you think it would be possible to "force" radio selection via the shortcuts provided by SRS, bypassing the SPU9, for example with the dedicated PTT buttons ?

**Comment by ciribob** [comment]
Sure! 

Change this line:
https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SimpleRadioStandalone.lua#L741

to a 0

i.e 

_data.control = 0;

Then HOTAS / Hotkey controls will work. You can do it on any aircraft you like 👍

**Comment by 132nd-etcher** [comment]
Well, first of all thanks very much for the speedy support (as always), it's much appreciated =)

I'm guessing this won't be an issue, but can you confirm you're ok with us internally distributing a modified version of SRS including the tweak you described to our "fresh" pilots ?

**Comment by ciribob** [comment]
That's absolutely fine. I assume by modified you mean the edited lua?

That change you can also do on the Huey and mi8 and any other aircraft.

Either way, no worries :)

**Comment by 132nd-etcher** [comment]
Indeed, we'd like to distribute only the modified lua file.

Thanks again for the support and this awesome piece of software =)
