### ISSUE TITLE
Consider making an ingame UI for VR users

### ISSUE THREAD

**Issue by jeffboulanger** [ciribob/DCS-SimpleRadioStandalone#154]
Have you considered this?   Are there issues that cause you to not be able to do this?  Would be very helpful for FC3 aircraft in VR

**Comment by afinegan** [comment]
I use the patented "Look through the nose hole" method lol

**Comment by ciribob** [comment]
Ah just saw your post on reddit 👍 

I was thinking exactly that! 

Shouldn't be too hard to do now i've seen how you went about doing it. Great job BTW.

I was going to do DX overlay injection but that is overkill if the same can be achieved with LUA

**Comment by jeffboulanger** [comment]
Cool deal, DX overlay injection wouldnt work unfortunately for VR, but glad you will be able to do something ;)  Looking forward to it!

**Comment by ciribob** [comment]
ah thats interesting, didn't know that!

Well glad you had the lua idea then as the only reason I was looking at DX injection was for VR!

Time is a little short but i'll see what I can do. At the very least I can make a bodge of your chat interface that has the active radios

**Comment by jeffboulanger** [comment]
If i get time to ill try and contribute, i literally dont use SR as much as I want to because of VR :(

**Comment by jeffboulanger** [comment]
If you make a branch for this let me know so I can fork and help.

**Comment by ciribob** [comment]
I'll make a branch tonight :)

**Comment by ciribob** [comment]
Update: https://forums.eagle.ru/showpost.php?p=2976099&postcount=1175

Thanks again for your work, wouldn't have thought it possible otherwise!

**Comment by jeffboulanger** [comment]
Glad to help!

**Comment by ciribob** [comment]
See Release https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.2.9.6 👍

**Comment by ciribob** [comment]
Fixed in #164
