### ISSUE TITLE
Speaker Boost not working

### ISSUE THREAD

**Issue by Compizfox** [ciribob/DCS-SimpleRadioStandalone#156]
Hi,

The Speaker Boost setting in the latest release does not have any effect for me. It does not matter whether I set it to -80% or to +1400%, the volume level stays the same.

This is a bit cumbersome because (for me, at least) the volume of SimpleRadio is so low that I can't hear anyone without decreasing the volume level of all other applications in Windows Volume Mixer.

**Comment by ciribob** [comment]
Does it work when you preview audio? Nothing changed code wise between the last release to change that but i'll have a look.

**Comment by Compizfox** [comment]
I didn't mean to imply that it worked in earlier versions, sorry. I only tested the latest version.

Yes, it does work with preview audio.

**Comment by ciribob** [comment]
Sorry not able to replicate at all. The speaker boost definitely has a noticeable affect for me. 

Would you mind retesting when I do the new release later this week?

**Comment by ciribob** [comment]
Just reopen if you can replicate 👍
