### ISSUE TITLE
Remove Band Restrictions from AWACS/GCI Panel

### ISSUE THREAD

**Issue by Eddie686** [ciribob/DCS-SimpleRadioStandalone#159]
Currently the AWACS/GCI panel has 10 radios configured for fixed bands, this is proving to be restrictive for ATC/AWACS use and giving an unrealistic limitation. Allowing all radios to operate on any VHF/UHF frequency and making the modulation selectable would remove this limitation.

Suggest a UI button for modulation selection

**Comment by ciribob** [comment]
I'll have a think about how best to do it, requires a bit of a rejig but nice idea!

**Comment by HomeFries94** [comment]
Awesome, thanks for the feature in 1.5.3.2.

**Comment by ciribob** [comment]
Limitations were removed a while ago - closing now 👍
