### ISSUE TITLE
Feature request: support for switch to cycle next/prev radio

### ISSUE THREAD

**Issue by jeetsukumaran** [ciribob/DCS-SimpleRadioStandalone#161]
Right now there are separate assignments for keys to select radio 1, 2, etc.

Is it possible to have support for next/prev radio # keys? 

Thanks!

**Comment by ciribob** [comment]
Great idea, i'll add to the list

**Comment by ciribob** [comment]
Done 👍

**Comment by jeetsukumaran** [comment]
FANTASTIC! Thanks! Appreciate your work :)
