### ISSUE TITLE
Installer deletes favourite servers

### ISSUE THREAD

**Issue by closeratio** [ciribob/DCS-SimpleRadioStandalone#169]
When I ran the installer for 1.2.9.5, it deleted the .csv file containing my favourite/saved SR servers. It'd be cool if it didn't do this.

**Comment by ciribob** [comment]
See #168 

Known bug, sorry for the issue! It is mentioned in the patch notes too

**Comment by closeratio** [comment]
Ah sorry, my fault! Thought I'd looked through the patch notes but I missed that part 😃

**Comment by ciribob** [comment]
No Worries! Just uploading a patch now, might do another release to save others the pain :)
