### ISSUE TITLE
Feature request: Modifier keys

### ISSUE THREAD

**Issue by The-Ignotus** [ciribob/DCS-SimpleRadioStandalone#173]
I just wanted to set keys to change radio frequencies by voice command via the new optional shortcuts
(Thanks for that ;) )

In my opinion we should have the possibility to set key commands with modifier keys like shift, ctrl and alt.
What do you mean?

**Comment by ciribob** [comment]
you've got them already, the second keybind is for the modifier?

ie. down set to button 1
down modifier set to alt

**Comment by The-Ignotus** [comment]
I misspelled that, my mistake :(

I mean multiple modifiers like Shift+Ctrl+Alt+Key :)

If i press shift+ctrl or whatever, my simple radio is taking only the first key i press :)

**Comment by ciribob** [comment]
ah right, gotcha.

To implement that requires a complete rewrite so unfortunately it'll be just two for now, sorry!

**Comment by The-Ignotus** [comment]
Alright, thank you for your quick answer :)

And please NEVER let SR go down! I need this awsome radio  ;D

**Comment by ciribob** [comment]
No worries, its open source so anyone can take if over 👍
