### ISSUE TITLE
High CPU usage, frame rate drops to < 1FPS

### ISSUE THREAD

**Issue by se-fLa** [ciribob/DCS-SimpleRadioStandalone#174]
With latest release 1.2.9.7 DCS becomes unplayable, when SR connected FPS drops to 1 or below 1 FPS. Disconnect SR and frame-rate returns to normal. Tried 4 times, restarted computer and SimpleRadio, reproducible all times
Installed 1.2.9.5 again and problem disappears.

**Comment by ciribob** [comment]
Are you hitting the keys listed here:

https://forums.eagle.ru/showpost.php?p=3103185&postcount=1424

Can you give me more info? 

Single Player / Multiplayer
High CPU when DCS isn't running?
Which version of DCS
When in aircraft or just in mission mission
Which aircraft
Sound Card in use
Windows Version

Are you using the in game new radio overlay?

Disable by deleting the DCS-SRS-OverlayGameGUI.lua from DCS/Scripts and seeing if that makes a difference

**Comment by ciribob** [comment]
If you could get a recording that would be even better, sorry for the issue

**Comment by bwRavencl** [comment]
I'm experiencing the same issue with 1.2.9.7.
When I press Right ALT + L to turn on the landing lights in an FC3 aircraft the lagging starts.
Pressing Left CTRL + Left Shift + L fixes the issue until Right ALT + L gets pressed again.
Disconnecting from the SR server also fixes the lagging.
I do NOT have Tacview installed.

**Comment by ciribob** [comment]
Appears to be a Lua Memory issue in DCS. 

Without Windows Hotkey Weirdness

00389.827 INFO    LuaNET: LISTEN 56320434
00389.827 INFO    LuaNET: Receive 56345182
00389.827 INFO    LuaNET: Decoded 56345256
00389.827 INFO    LuaNET: Assigned 56345394
00389.928 INFO    LuaNET: Garbage Collected 56314651
00389.929 INFO    LuaNET: Paint Start 56317917
00389.929 INFO    LuaNET: Paint End 56317995


With Windows Key Hotkey Weirdness

00395.678 INFO    LuaNET: LISTEN 57120082
00395.834 INFO    LuaNET: Receive 106464899
00395.834 INFO    LuaNET: Decoded 106478543
00395.834 INFO    LuaNET: Assigned 106496603
00395.973 INFO    LuaNET: Garbage Collected 56319716
00395.974 INFO    LuaNET: Paint Start 56719112
00395.975 INFO    LuaNET: Paint End 56986179

Not sure im going to be able to fix this as it looks like some kind of ED Debug code is being triggered

**Comment by ciribob** [comment]
Further test, drop the windows key and try:

Left Ctrl + L - It'll lag regardless of if its bound or not

Fix - Left CTRL + Left Shift + L

**Comment by Kerrac** [comment]
Hey ciribob,
I dont know if its any help, but for me the 1 fps issue is definetly linked to the new overlay (CTRRL + left shift +esc) when ever I have nnew new overlay off the bug does not get triggered.

**Comment by ciribob** [comment]
@Kerrac Yup that I know, but thanks :)

If you look above, pressing that key combination causes the lua memory to go crazy when the overlay is in use. When the overlay is hidden its fine (because im not refreshing the overlay) and its weird that pressing Left CTRL + Left Shift + L Fixes the memory, regardless of what its bound too.

**Comment by ciribob** [comment]
Cant work around

**Fix - Press - Left CTRL + Left Shift + L**

**Comment by se-fLa** [comment]
Fixed (since long)
