### ISSUE TITLE
Feature Request: for new/unsupported modules, assign Combined Arms radio stack by default.

### ISSUE THREAD

**Issue by HomeFries94** [ciribob/DCS-SimpleRadioStandalone#177]
Similar to allowing spectators access to Combined Arms radios, the recommendation is that if a module is undetected/unsupported by SRS, the radio stack defaults to the Combined Arms radios usable by the overlay.  Assigning this as a default state for unsupported modules will allow people to use new modules until specific module support can be provided.

**Comment by ciribob** [comment]
It should already do that?

If you're​ in an unknown aircraft you'll get 3 radios - UHF , VHF and FM.

Is that not working?

**Comment by mvee** [comment]
When Viggen came it didn't revert to expanded radios. Probably same for Spitfire, didn't get to test.

**Comment by HomeFries94** [comment]
Last time I tested was 1.2.9.6 with the Viggen and Spit.  Had the CA radio stack as observer, but went to unknown in the cockpit.  Haven't tested in 1.2.9.7 or 1.3.0.0.

**Comment by ciribob** [comment]
Ah ok, thanks for reporting. I'll find out why!

**Comment by ciribob** [comment]
Fixed 👍  Thanks for reporting!
