### ISSUE TITLE
bluetooth device causes SRS 1.3.2.0 to stop working

### ISSUE THREAD

**Issue by razorizer** [ciribob/DCS-SimpleRadioStandalone#182]
Never had this issue with previous versions. I have the PLT 165 bluetooth headset by Plantronics and when I am trying to connect I get a freeze of SRS with a message of Audio Output Error
![audio output error](https://cloud.githubusercontent.com/assets/28485222/25772506/3ecbabd2-3275-11e7-8f7d-1d99d33347fa.jpg)
My client log is attached also. Thank you.
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/980935/clientlog.txt)

**Comment by ciribob** [comment]
Looks like a driver issue ? https://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/unrecoverable-playback-error-unknown-error-code/d70acfc0-8b4f-408c-9156-86eccafd2ef1

Have you got the latest driver for your headset and have you tried any other headset?

Sorry for the slow reply

**Comment by razorizer** [comment]
No problem. Thanks for replying anyway. I also use another bluetooth
headset from the same brand (plantronics PLT 155) that seems to be working
just fine even though it is an older version of PLT 165. Did not update
drivers though but it seems a good idea to do so. I'll try that and get
back to you.
Thanks again.

Στις 28 Μαΐ 2017 4:16 ΜΜ, ο χρήστης "Ciaran Fisher" <
notifications@github.com> έγραψε:

**Comment by razorizer** [comment]
The latest drivers was already installed instead I've unistalled and reinstalled the divice from device manager and now it seems to be working fine again. Probably a windows 10 issue. Thanks again


Εστάλη από τη συσκευή μου Samsung

-------- Αρχικό μήνυμα --------
Από: Ciaran Fisher <notifications@github.com> 
Ημερομηνία: 28/5/17  4:16 ΜΜ  (GMT+02:00) 
Προς: ciribob/DCS-SimpleRadioStandalone <DCS-SimpleRadioStandalone@noreply.github.com> 
Κοιν.: razorizer <razorizer@gmail.com>, Author <author@noreply.github.com> 
Θέμα: Re: [ciribob/DCS-SimpleRadioStandalone] bluetooth device causes SRS
  1.3.2.0 to stop working (#182) 

Looks like a driver issue ? https://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/unrecoverable-playback-error-unknown-error-code/d70acfc0-8b4f-408c-9156-86eccafd2ef1
Have you got the latest driver for your headset and have you tried any other headset?
Sorry for the slow reply

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ciribob/DCS-SimpleRadioStandalone","title":"ciribob/DCS-SimpleRadioStandalone","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ciribob/DCS-SimpleRadioStandalone"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ciribob in #182: Looks like a driver issue ? https://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/unrecoverable-playback-error-unknown-error-code/d70acfc0-8b4f-408c-9156-86eccafd2ef1\r\n\r\nHave you got the latest driver for your headset and have you tried any other headset?\r\n\r\nSorry for the slow reply"}],"action":{"name":"View Issue","url":"https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/182#issuecomment-304513596"}}}

**Comment by ciribob** [comment]
Great! Glad to hear 👍
