### ISSUE TITLE
L-39 Rear seat radio is incorrect

### ISSUE THREAD

**Issue by ghostots** [ciribob/DCS-SimpleRadioStandalone#183]
Hi ciribob,

  It appears that the rear-seat radio now presents a VHF radio with some random frequency, making it essentially useless in MP.
  Could you please look into this?  I don't know if this is an SRS or a DCS issue.

**Comment by ciribob** [comment]
Unfortunately I just pull out the frequency that DCS give me for it. 

Did you have the controls set to rear cockpit on the radio?

**Comment by ghostots** [comment]
I'll check on that.

**Comment by ghostots** [comment]
It seems to be an L-39 bug.  It is temporarily correctable by editing the DCS LUA files manually.

**Comment by ciribob** [comment]
Could you post what files need to be edited?

Its been reported to ED and is fixed internally so should make its way to us soon
