### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by gillesdrone** [ciribob/DCS-SimpleRadioStandalone#184]
I have load and install last version 1.3.3.0  and i c'ant mappe key
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/1104599/clientlog.txt)
i post my log 
and i post pics 
pics 3 i have make option allow more input device and restart ( you had make this option for me ) 
![sans-titre-3](https://user-images.githubusercontent.com/22989031/27577478-1e6471ec-5b21-11e7-99f6-dcfb1db12710.jpg)

if I select set that Compartment get grey and impossible to make  an input

if I select an other compartment they get grey all 
![sans-titre-1](https://user-images.githubusercontent.com/22989031/27577595-9dc195e6-5b21-11e7-9e05-c4578f903dd4.jpg)
![sans-titre-2](https://user-images.githubusercontent.com/22989031/27577614-a9fc8b54-5b21-11e7-8e75-0079360ac2f6.jpg)

I test with keaboard and same 
thank's for your help 
Gillesdrone

**Comment by gillesdrone** [comment]
I have test with my PC portable and it is good for it ... but I d'ont see where it's no good with my Pc Pit

**Comment by gillesdrone** [comment]
I progress , now I can put keaboard in control but if '' allowmore input devices'' is OFF  

if I have '' allowmore input devices ''ON I have the problem ; my friend have same problem if he valide this option

**Comment by ciribob** [comment]
I'll add an option in the next release so you can add to the whitelist list yourself for devices that you know should work 👍

**Comment by BarneyFife68** [comment]
I have the exact same problem listed above.  I have searched the internet and done all available troubleshooting i could find.  Not sure what to do.  Any help would be greatly appreciated.

**Comment by BarneyFife68** [comment]
Sorry, one point for me is different.  I don't get the keyboard as a choice.  All inputs show in txt file.

**Comment by BarneyFife68** [comment]
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/1132775/clientlog.txt)

**Comment by ciribob** [comment]
@BarneyFife68 Leave expand input devices off, restart SRS and then keyboard & joystick should work? Let me know 👍
