### ISSUE TITLE
Traffic on different frequency blocks main traffic

### ISSUE THREAD

**Issue by warrantyvoids** [ciribob/DCS-SimpleRadioStandalone#185]
On the 107th TTI server, we are using SRS quite intensively. Because of this, we split between several channels for ATC, AWACS and Squadrons. Unfortunately, when a few channels get busy, it blocks the ATC channel or AWACS channel, without them being able to break because nobody knows which channel is busy.

Would it be possible to move from a 'Broadcast to all' to a system where the client subscribes to a frequency (e.g. one which is active) and only route packets whenever the client is listening? If required, I can help with this.

**Comment by ciribob** [comment]
Sorry im not sure I understand

Blocks the network traffic itself or its just hard to identify which channel the data is coming in on?

The UDP VOIP data isnt broadcast to all, its filtered out at the server side so only those on the right frequency have it sent to them. Its not sent to all connected clients - Or should be.
