### ISSUE TITLE
Automatic Reconnect Attempt

### ISSUE THREAD

**Issue by ghostots** [ciribob/DCS-SimpleRadioStandalone#186]
Hi ciribob,

  This is a sort of two in one:

1) We seem to get random disconnects from our SRS server for unknown reasons.   It would be nice to have an auto-reconnect set up where the client to attempt to reconnect automatically if not manually disconnected or booted/banned.
2) When a disconnect occurs, there should be a sound notification.

We certainly got to practice some NORDO thanks to it :D

**Comment by ciribob** [comment]
@ghostots i'll add to the list but thats odd to hear. 

We've run 3 SRS servers on one machine for months and never had a drop out. Is the machine also running DCS? Maybe its under heavy load?

Thanks for the report 👍

**Comment by ghostots** [comment]
Hi, yes, that machine is also running DCS.  However, it is a multi-core CPU so in theory it should be ok?  Is there any debug output that we could check for this?

**Comment by ciribob** [comment]
Should be ok, maybe bandwidth is being saturated? Nothing really you can debug, other than watching CPU and network traffic and seeing if you spot anything odd. Sorry.

**Comment by ghostots** [comment]
After a bit more work, it looks like what fixed the issue for me is adjusting the UDP timeout on my router.  Not everyone has the firmware to do this with their routers though ... the default timeouts are as short as 10s ... would you be able to send 2-3 keep-alives in that amount of time?

**Comment by ghostots** [comment]
I spoke too soon.  Had multiple disconnects today.  I don't believe there's anything odd happening on the server.  It could be that the router is clearing connections very aggressively ... is there a keep-alive schedule in the code?

**Comment by ciribob** [comment]
There is a keep alive, but its more like 30 seconds or more.

Its very odd as the TCP connection has to be dropped for the connection to sever. The UDP can be dropped and you'll lose audio until its opened again but not lose the radio overlay.

I can set you up a test server if you like to see if you get drops from that one?

**Comment by ghostots** [comment]
Hi Ciribob, thanks for setting up that test server.  Long time no talk right? :)

Still experiencing a LOT of drop-outs, and it's with SRS only.  It'll work for a while but then it will start dropping out.

**Comment by ciribob** [comment]
Is this still occurring? If not i'll close 👍

**Comment by ghostots** [comment]
please close :)
