### ISSUE TITLE
Add joystick slider support for radio volume

### ISSUE THREAD

**Issue by BiggieSmallsVR** [ciribob/DCS-SimpleRadioStandalone#191]
It would be useful to me to be able to map a slider on my joystick/throttle to a particular radio's volume so that I am able to easily able to lower it if needed. I know in certain AC the actual radio volume is correctly mapped and this is awesome, but for FC3 for instance it is not possible to modify SRS volume from within DCS (as far as I know).

Also, in addition to all three radios separate volume, a SRS master volume slider mapping would be great.

**Comment by ciribob** [comment]
For now, this wont be possible due to the way the controls are implemented but i'll add to the list 👍

**Comment by 132nd-etcher** [comment]
I second this request.
