### ISSUE TITLE
(Huey) Signal Panel Volume Knob to SRS Volume Level

### ISSUE THREAD

**Issue by BiggieSmallsVR** [ciribob/DCS-SimpleRadioStandalone#192]
In the Huey, the C-1611/AIC Signal Distribution Panel volume knob lowers the volume of all radios simultaneously IRL (acts as a master volume), but unfortunately it does not affect the SRS radio volumes. Would it be possible to map this volume knob to attenuate all 3 radios in SRS?

**Comment by ciribob** [comment]
Sorry for the slow reply - do you mean the volume knob labelled "intercom volume knob" to the left of the intercom mode switch?

Would you mind sending a screenshot of the exact knob? dont want to get it wrong!

**Comment by BiggieSmallsVR** [comment]
Yes, I was referring to the master volume control knob for the C-1611/AIC Signal Distribution Panel (intercom). In the key binding page it is listed as an axis and is called "C1611 Intercom Volume Knob".
Thanks!
![image](https://user-images.githubusercontent.com/26583175/33101807-d7040200-cee7-11e7-9239-98e4d443544f.png)

**Comment by ciribob** [comment]
Thanks! Will add in for release on the weekend
