### ISSUE TITLE
SRS crashes at start

### ISSUE THREAD

**Issue by SgtHawkins** [ciribob/DCS-SimpleRadioStandalone#193]
Hello guys,

your awesome program which I'd love to use crashes every time I try to start it. Windows says: "DCS-SimpleRadio Standalone Client has stopped working". Problem occurs both when installed via the installer and manually. 

Crash info:
_Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	SR-ClientRadio.exe
  Problem Signature 02:	1.3.3.0
  Problem Signature 03:	59468f80
  Problem Signature 04:	SR-ClientRadio
  Problem Signature 05:	1.3.3.0
  Problem Signature 06:	59468f80
  Problem Signature 07:	19d
  Problem Signature 08:	23
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1031
  Additional Information 1:	5b90
  Additional Information 2:	5b9094ca272a40d948d792a51916aff1
  Additional Information 3:	af1d
  Additional Information 4:	af1d3ab38e40636b255be372b93bf526_

**Comment by ciribob** [comment]
Sorry for the slow reply - sounds like a windows .net issue as thats a Windows error as it tries to draw the GUI

Just to double check - have you followed the links on the releases page to make sure your .net is up to date?

Are you running MSI Afterburner? If so quit it and try again

**Comment by SgtHawkins** [comment]
Afterburner was indeed the problem, thanks a lot!

**Comment by ciribob** [comment]
Glad you're sorted :)
