### ISSUE TITLE
Mouse disconnecting/reconnecting

### ISSUE THREAD

**Issue by blaizzmc** [ciribob/DCS-SimpleRadioStandalone#194]
Hi,

While I have SR Client opened and connected my mouse keeps connecting and disconnecting. 
Any idea why ?

Ver 1.3.3.0, mouse is a reddragon perdition M901

**Comment by ciribob** [comment]
Sorry for the slow reply - I've no idea why that would happen - all SRS does is poll the device for its state BUT only if you're using it as a Hotkey device.

Have you bound radio to the mouse? If not, sounds like a very odd bug but no way I can solve that as im not entirely sure its SRS. 

When exactly does it happen? When binding inputs, when connected to the server or just the program running and nothing done to it?

**Comment by blaizzmc** [comment]
No problem :)
It only happens when I have SRS launched and connected to a server :/ Even without dcs running.

**Comment by ciribob** [comment]
Do you have the mouse bound as an input for SRS?

**Comment by blaizzmc** [comment]
Negative

**Comment by ciribob** [comment]
is it a wireless mouse? 
The DirectX code literally just polls specific devices, and only if they're bound, using a 3rd Party Library (DXSharp) so no idea how to resolve this for you, sorry

**Comment by blaizzmc** [comment]
Well thank you for your attention :)

**Comment by ciribob** [comment]
I've updated the library for SharpDX... Maybe it'll magically be fixed for you in the next release 👍

**Comment by ciribob** [comment]
Version released - let me know if it solves it!

**Comment by blaizzmc** [comment]
No :/ But "hacked" it ^^ It was because I binded the ptt to my stick. To resolve it I binded the ptt to a key and then used the profiler to set that key on the joystick.

**Comment by ciribob** [comment]
ah great! glad to hear its fixed 👍
