### ISSUE TITLE
Problem with 1.5.8

### ISSUE THREAD

**Issue by SgtHawkins** [ciribob/DCS-SimpleRadioStandalone#207]
Hello its me again :/

I recently switched to 1.5.8 for the harrier. Now when I try to use SRS with that version it just doesnt work. I don't get the ingame box and the client doesnt recognise the game is running. ("unknown" on the radio overlay).

Maybe you can help me yet again?

EDIT: I fixed the problem with a reinstallation. But still I can't open the info box ingame. The one you usually open by pressing Ctrl+Shift+Esc

**Comment by ciribob** [comment]
Known bug with overlay

Took a while to fix but hotfix is here https://forums.eagle.ru/showthread.php?p=3318849

Thought I put in release notes but will double check and make more obvious :)

Next release will.have this fix in too when openbeta goes to stable

Close this issue if that works, if not please let me know!

**Comment by SgtHawkins** [comment]
Works like a charm! Thank you very much. I think I just didn't put enough attention to the release notes so sry for that :/

**Comment by ciribob** [comment]
No worries, glad it's sorted. When release switches over I'll do a proper release with hotfix
