### ISSUE TITLE
Can't hear or transmit with new release

### ISSUE THREAD

**Issue by estokes** [ciribob/DCS-SimpleRadioStandalone#212]
Hi, I've been using SRS for quite a while. But with this new release, connecting to buddyspike server (5.189.162.17:5014), I can't hear anything, and no one can hear me. The interface looks completely fine, it shows the correct number of connected users. I even hear the click when I transmit, and on the overlay, when I transmit, the correct radio light comes on. But I can never hear anyone else, and the radio lights never come on except when I transmit. Using preview audio I've verified that I have the correct input devices. Teamspeak and Discord work find on this same computer. I've verified that other people are using 1.4.5.0 to connect to buddyspike (it's running 1.4.4.0). Not sure what else to do.

[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/1584450/clientlog.txt)

**Comment by ciribob** [comment]
Sounds like an issue with the gameGUI not loading.

The gameGui file loads your coalition and player name, SRS on the buddyspike server has coalition radio enforcement on so if you have no coalition, you can't hear anyone and they can't hear you.

Can you just jump in on single player and check your DCS logs have this somewhere?

Ignore the numbers, they are just times.

00087.259 INFO    LuaNET: Loaded - DCS-SRS GameGUI
00087.266 INFO    LuaNET: Loaded - DCS-SRS Overlay GameGUI

If you've not got those lines, the gameGui hasn't loaded so try reinstalling SRS using the installer.

If it still doesn't work, and there is a file in Hooks in saved games/dcs/scripts - drag the SRS gameGUI into the scripts/hooks folder and try again

Two other people have had a similar issue but all is well on mine and most others so not sure if it's just a DCS bug. Id run a DCS repair as well to be sure

**Comment by estokes** [comment]
That worked, thanks.

**Comment by ciribob** [comment]
Which worked? Reinstall or dragging the file in? Nice to know for future reference. :)

**Comment by estokes** [comment]
I just reinstalled. I didn't even have a hooks folder, guess my install was
that old.
