### ISSUE TITLE
Application and Installer both close immediately on startup.

### ISSUE THREAD

**Issue by a-harper** [ciribob/DCS-SimpleRadioStandalone#214]
Hi,

Nothing appears when running either the Application or the Installer, I get the prompt for UAC but then a spinning wheel for 1 second and then nothing.

Running the Installer through x64dbg gives:
`EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FF909858913 d3d9.00007FF909858913
        NumberParameters: 2
ExceptionInformation[00]: 0000000000000001 Write
ExceptionInformation[01]: FFFFFFFFFFFFFF80 Inaccessible Address
First chance exception on 00007FF909858913 (C0000005, EXCEPTION_ACCESS_VIOLATION)!
DebugString: "\r\nSTATUS_STACK_BUFFER_OVERRUN encountered\r\n"
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: 80000003 (EXCEPTION_BREAKPOINT)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FF9119993EC kernelbase.00007FF9119993EC
        NumberParameters: 1
ExceptionInformation[00]: 0000000000000000
First chance exception on 00007FF9119993EC (80000003, EXCEPTION_BREAKPOINT)!`

Running the application through x64dbg gives:
`First chance exception on 00007FF9118C3FB8 (E0434352, CLR_EXCEPTION)!
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: E06D7363 (CPP_EH_EXCEPTION)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FF9118C3FB8 kernelbase.00007FF9118C3FB8
        NumberParameters: 4
ExceptionInformation[00]: 0000000019930520
ExceptionInformation[01]: 00000047697DCF38
ExceptionInformation[02]: 00007FF8EDED6BB0 clr.00007FF8EDED6BB0
ExceptionInformation[03]: 00007FF8ED720000 clr.00007FF8ED720000
First chance exception on 00007FF9118C3FB8 (E06D7363, CPP_EH_EXCEPTION)!
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: E0434352 (CLR_EXCEPTION)
          ExceptionFlags: 00000001
        ExceptionAddress: 00007FF9118C3FB8 kernelbase.00007FF9118C3FB8
        NumberParameters: 5
ExceptionInformation[00]: FFFFFFFF80004002
ExceptionInformation[01]: 0000000000000000
ExceptionInformation[02]: 0000000000000000
ExceptionInformation[03]: 0000000000000000
ExceptionInformation[04]: 00007FF8ED720000 clr.00007FF8ED720000
First chance exception on 00007FF9118C3FB8 (E0434352, CLR_EXCEPTION)!`

I have the required .NET Frameworks. Running Windows 10. Any help appreciated!

Thanks

**Comment by a-harper** [comment]
Aha! It was Riva Stats messing with it. Fix is to turn off Application Detection for Riva Tuner.

**Comment by ciribob** [comment]
Good to know.

MSI afterburner does the same for some people :/

Glad you sorted it :)
