### ISSUE TITLE
[feature request] auto updater (there are free ones)

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#216]
I suggest one of these:

https://github.com/ravibpatel/AutoUpdater.NET

https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by ciribob** [comment]
You're welcome to implement :)

Not going to add one for now as I prefer people to update manually as there may be a reason why to not autoupdate
