### ISSUE TITLE
SRS StandAlone 1.4.8 incompatibility with Helios

### ISSUE THREAD

**Issue by KlemenKecman** [ciribob/DCS-SimpleRadioStandalone#221]
Yesterday I updated SRS from 1.4.6 to 1.4.8 and all of a sudden there is an issue with helios.

I was able to track it down to and steps to reproduce:

1. Start Helios (but do not start profile)
2. Start SRS (but do not connect to server)
3. Start DCS (go in to multiplayer)

Once in the pit:
Connect SRS to a server
Start profile in helios
**Result:** helios crash and closure.

Once in the pit:
Start profile in helios
Connect SRS to a server
**Result:** SRS cannot connect to server.

I will downgrade to 1.4.6 to eliminate a possibility of recent DCS patch being the culprit and report back

**Comment by KlemenKecman** [comment]
Just tested it out. It works OK on 1.4.6

**Comment by KlemenKecman** [comment]
In export.lua for helios we have:
----------
-- DATA --
----------

gHost = "127.0.0.1"
gPort = 9089
gExportInterval = 0.1        -- frequency of export events (sec)
gExportLowTickInterval = 2   -- export events call ProcessLowImportance every this many events.

/SNIP

Unfortunately there is no way to change the listening port of helios.

Ciribob acknowledged it and will be fixed via next update.

**Comment by ciribob** [comment]
Fixed in #226
