### ISSUE TITLE
Radio broadcast stations (e.g. music)

### ISSUE THREAD

**Issue by gyrovague** [ciribob/DCS-SimpleRadioStandalone#231]
Might be nice (and possibly not _that_ difficult) to have a feature where SRS server (or maybe even client too) can be configured with a directory of MP3/ogg files to shuffle play on specified frequency+modulation, to basically make a radio station (or multiple stations, with a directory of files each) that clients can tune to.

**Comment by gyrovague** [comment]
#232 could possibly be used to inform SRS clients of these stations, either automatically (if such stations are configured, add a list of them to the MOTD) or manually (i.e. SRS server owner must enter the text manually to point out radio station frequencies).

**Comment by ciribob** [comment]
What I was actually planning was more simple but perhaps more useful. I was going to build a basic client where you can select just an audio input with the assumption that it's a virtual audio cable.

Then you can use a normal MP3 player (music bee is good as you can select output) or chrome or whatever to pipe audio in

It would have a few different frequency selectors and coalition options and that's about it.

**Comment by etcher-be** [comment]
I'm coming from #268 with more specific requests about this one. I'd like to create ATIS stations using SRS, and that would mean having many different stations, each with a position and a frequency. Do you think that could be feasible ? An idea for implementation would be to have a config file that lives server-side and would declare things such as "location, frequency, path_to_mp3". It would depend on what's easiest to add to the existing system.

**Comment by MorpheusXAUT** [comment]
The plans for the external audio input client was primarily for allowing an virtual input to be continously transmitted.
I guess it would be relatively easy to extend the plans for basic audio files to be played repeatedly though, so that would be within the designed features of a standalone audio client 👍

**Comment by rkusa** [comment]
I've just published something for this use case: https://github.com/rkusa/dcs-radio-station (supports only ogg/opus files for now though). It basically allows doing something like:

```bash
.\dcs-radio-station --freq=251000000 --loop .\ogg-opus-files
```

**Comment by etcher-be** [comment]
@rkusa this looks awesome and would fit my requirements, I'm testing it ASAP ! Thanks for posting it here :+1:

**Comment by ciribob** [comment]
Closing for now as is @rkusa's solution and also another is working on a way of piping in audio
