### ISSUE TITLE
Release 1.5.0.0 Client open then close

### ISSUE THREAD

**Issue by r8d** [ciribob/DCS-SimpleRadioStandalone#234]
hey 

what info do you need to help me?

Thanks

**Comment by ciribob** [comment]
Please upload clientlog.txt

Please also disable all unused sound devices (right click and disable in sound manager) and see if that works.

Also check windows error logs and post the error from there for SRS

**Comment by r8d** [comment]
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/1960654/clientlog.txt)

**Comment by r8d** [comment]
Hi ciribob

Uploaded the file just for reference & learning perpuses.

You have nail it when you suggested to 
disable all unused sound devicest.

Thanks for the quick response & keep up the great work .. I'm a big fan.
