### ISSUE TITLE
Add 150Hz squelch tone to NATO FM radios

### ISSUE THREAD

**Issue by sniporbob** [ciribob/DCS-SimpleRadioStandalone#236]
The NATO military FM radios use a 150Hz tone to break squelch. It comes across as a fairly quiet low humming noise during reception.

**Comment by sniporbob** [comment]
[Tx119Rx77_Tx77Rx119.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/2003135/Tx119Rx77_Tx77Rx119.zip)

Sample attached. You'll probably want to open it with audacity or something to control the left/right audio channels.

**First sound sample setup**
Transmitter: RT-1523(C)/U with H-250 handset
Receiver: PRC-77 with audio directly in to computer microphone line (modified H-250 with audio jack instead of speaker)(speaker was broken anyway)
Left audio channel: cellphone audio recording of me speaking into transmitter handset
Right audio channel: computer mic in recording directly from PRC-77

**Second sound sample setup**
Transmitter: PRC-77 with H-250 handset
Receiver: RT-1523(C)/U with audio directly in to computer microphone line
Left audio channel: cellphone audio recording of me speaking into transmitter handset
Right audio channel: computer mic in recording directly from RT-1523(C)/U


Transmissions were on 51.50mHz. Both sound samples have several seconds of PTT with nothing spoken to get a sample of the pure 150Hz tone. The radio squelch was turned on for both receiving radios, and the PRC-77 has a noticeably longer static burst before the squelch kicks back in to silence it.

**Comment by ciribob** [comment]
I know its been a while - but I'll be working on this feature again soon and getting in this tone 👍

**Comment by sniporbob** [comment]
Cool, let me know if you need any more samples or any specific setup recorded. I have an SDR now so I can even record the actual radio signal, though it's probably overkill in this scenario.

**Comment by ciribob** [comment]
This will be out in a release later today. For some reason the tone isnt quite right now I've imported it but as a first pass it's good enough. 

Will try to solve at some point!

Thanks for this!
