### ISSUE TITLE
SteelSeries Arctis Chat 7 output: Invalid output format

### ISSUE THREAD

**Issue by pdxmholmes** [ciribob/DCS-SimpleRadioStandalone#246]
When trying to initialize output to my SteelSeries Arctis 7 Chat output device, I get an invalid format error. Debugging down in to the code, I see this block of code in NAudio's WasapiOut class seems to get confused:

DCS-SimpleRadioStandalone\NAudio\Wave\WaveOutputs\WasapiOut.cs: 286
```C#
WaveFormatExtensible closestSampleRateFormat;
if (!audioClient.IsFormatSupported(shareMode, outputFormat, out closestSampleRateFormat))
{
     // Use closesSampleRateFormat (in sharedMode, it equals usualy to the audioClient.MixFormat)
     // See documentation : http://msdn.microsoft.com/en-us/library/ms678737(VS.85).aspx 
    // They say : "In shared mode, the audio engine always supports the mix format"
    // The MixFormat is more likely to be a WaveFormatExtensible.
    if (closestSampleRateFormat == null)
```

The 'closestSampleRateFormat' it spits out ends up being invalid, with wildly varying BitsPerSample. If I comment out the null check and let it use the MixFormat, everything works as expected. Basically the comment there is incorrect, probably due to bad driver support on SteelSeries part, but an issue none the less.

Since SRS uses an in-repo copy of NAudio, would you prefer I tried to submit a fix for this upstream, or would you like a fix here locally that I can perhaps port upstream?

**Comment by ciribob** [comment]
Replied on discord - thank you very much!

I'll pull this from NAudio / your repo depending on when its merged 👍

**Comment by ciribob** [comment]
Merged - thanks!
