### ISSUE TITLE
Connected clients counter addition

### ISSUE THREAD

**Issue by Cephel** [ciribob/DCS-SimpleRadioStandalone#254]
Is it possible to display the amount of clients actually connected an in game server next to the current list?

It seems the current number only displays whoever is connected to the SRS server, but has no bearing on the actual available people on radio comms in game.

**Comment by MorpheusXAUT** [comment]
Definitely like that suggestion - will be added to next release.

**Comment by MorpheusXAUT** [comment]
Implemented in next release (upcoming beta in the next days) as shown below: 
![IngameClientCount](https://i.imgur.com/TmHdSLN.png)
Was that what you imagined @Cephel ?

**Comment by Cephel** [comment]
Yes this is exactly what I was imagining.

Not gonna lie, since launching the game takes about a decade, SRS has become a quick way for me to check activity on my favorite servers. Seeing how many are on ingame radios is a huge help for that.

**Comment by MorpheusXAUT** [comment]
Awesome. Will be included in the next release!

**Comment by victorcotap** [comment]
May I suggest the opposite as well? Having the number of connected clients in the game overlay.
I rely on auto connect so I pretty much just start SRS and minimize it.

Definitively just a nice to have and there's always the cost of real estate in the overlay to display that information but I thought I would throw it out there :)

**Comment by victorcotap** [comment]
@MorpheusXAUT Yes exactly that. Doesn't have to be connected vs in game but just connected.
To give an idea if people are on SRS or not because I see a lot of people connecting but still using Discord because they are shy of breaking radio silence or wonder if it's worth it if they are the only one on.
This could help, but again nice to have

**Comment by MorpheusXAUT** [comment]
Alright, will discuss this and let you know about the decision!

**Comment by MorpheusXAUT** [comment]
@victorcotap Added the counts to the "full" version of the ingame overlay (it'll be hidden for the "minimal" versions):
![Ingame overlay](https://i.imgur.com/GCj8ihh.png)
