### ISSUE TITLE
Player export JSON location

### ISSUE THREAD

**Issue by szporwolik** [ciribob/DCS-SimpleRadioStandalone#256]
I'm creating the concept of standard module for exporting DCS server data including:
- DCS server status + events + ... (you name it)
- SRS connected players with tunned in frequencies
- LotATC controllers with the control areas

The first part will be handled by LuaSQL what shall be the most bulletproof and easy to setup for the most. LotATC is currently not exporting the data, but I've already proposed this to DArt and I belive it will be considered.

The SRS already is doing the great job with exporting the JSON file, **my feature proposal would be that JSON file location could be set from the server config file** (we do not need this in GUI). Please consider, this shall not be a big effort, but would help a lot.

I will try to talk with all top module makers to start using in example Logs\JSON folder for all json exports, so server admins can easily pull the data from one place and handle.

**Comment by MorpheusXAUT** [comment]
Sounds like a reasonable request, will be added. We'll have it config-file only, as suggested, with a fallback to the current default location should no value be provided or the destination not be writeable.

**Comment by MorpheusXAUT** [comment]
Implemented in the `beta` branch, will be included in the next beta and stable release.

**Comment by szporwolik** [comment]
That was quick, thank you a lot ! :) 🥇

**Comment by MorpheusXAUT** [comment]
A `beta` version containing this feature has been release - if you're using the [1.5.3.1](https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.5.3.1) prerelease, you'll be able to try it out before the final `stable` release, be aware that you will not be able to use the `1.5.3.1` server with older clients or the other way around.
Any feedback would be highly appreciated!
