### ISSUE TITLE
Easy connection!

### ISSUE THREAD

**Issue by Targanon** [ciribob/DCS-SimpleRadioStandalone#264]
I have a server that is on a dynamic IP. and rather than make a new entry ever time I connect. 
it would be nice to be able to type the IP into the connection address box and click connect...

Or a way to have to server ping for an external IP and and insert that into the Script file for Server address.

**Comment by MorpheusXAUT** [comment]
Regarding creating a new entry every time you connect - are you talking about the favorite list of SRS? You can already just enter any IP into the connection address field and connect - no need to add them to the favorite list before. That entry will not be saved when you exit/restart SRS though.

There currently no way of having the server replace the auto-connect script's advertised IP, unfortunately, and we'll have to discuss whether we can find a feasible way of doing so.

For now, you could set up some dynamic DNS service that always updates a DNS record to your current IP, and use that to connect to your server. Many routers support some dynamic DNS providers out of the box, or many providers have a small client you can run alongside with your SRS server to automatically keep the record up-to-date.

**Comment by Targanon** [comment]
OK I have been working on this with my son he is the coder ...

so we found a way of doing to this.

AS you know people do not need to know the IP of a server if its listed in the public list on DCS.

so they can connect and all's good however if you wish to use SRS on that server, you need to know the IP of the server. so using an outside IP look up site we have created and little exe file that looks for the current IP and modifies the line 9 of autoconnect LUA. 

and then starts the SRS server ..

so problem solve I just click the shortcut for the little exe my son made and it does the rest including starting the SRS server sweet... 

Thanks for your prompt reply.
perhaps if you email my son he could tell you what it is he did to get this to work.. I think that it has been made with my current build and file paths in mind so I don't think its much good me forwarding the file to you.

Link_jedi_knight@hotmail.com
try him he may be useful
