### ISSUE TITLE
ATIS stations

### ISSUE THREAD

**Issue by etcher-be** [ciribob/DCS-SimpleRadioStandalone#268]
I made a a little app that manages a remote DCS server from Discord, loading mission, weather and providing info & commands to server owners.

I'm using UniversRadio ATIS feature to convert the current mission weather and generate a local mp3 files containing the ATIS speech. That file is then played by UR over radio at all Georgian airfields, each with its specific frequency.

Would there be a way to achieve the same result using SRS? Is there an API to force it to play a given audio stream over a given frequency? Or are there specification to create a dummy local client for the SRS server that would allowed to appear to be at multiple locations and to emit on multiple frequencies ? I do not care if the radio station is available anywhere on the map, the location isn't such an issue to me, the frequency matters most.

I'm sorry if I missed something in the documentation about this, but I was unable to find anything relevant. I do not want to waste your time over it, so if there is no built-in way to achieve this, I'm sure I'll find a way by reading the source and trial & error.

Cheers !

**Comment by MorpheusXAUT** [comment]
Hi,

something similar was already requested for radio broadcast stations (see issue #231 ) and has been partially worked on already, but is still not finished unfortunately. It's still definitely on the TODO list, but we can't promise any release date yet 😄 

In the meantime, people have been using virtual audio cables as their SRS microphones and either utilising a keyboard macro or a toggle on their HOTAS (basically anything that just keeps a button pressed) to "simulate" this.
Although it's not a perfect solution, you could potentially use that to simulate the ATIS transmission (in combination with an external software than can play it on repeat via a virtual audio cable/output).

I'll keep you updated when we get a proper, standalone client ready and released!

**Comment by etcher-be** [comment]
@MorpheusXAUT that's great, thank you very much for the quick reply ! There's also a ton of useful info in ClientSync.cs & friends, especially about the way AWACS is managed internally. Maybe I could use that to implement my own client?

**Comment by MorpheusXAUT** [comment]
Definitely, check out either the [Client code](https://github.com/ciribob/DCS-SimpleRadioStandalone/tree/master/DCS-SR-Client) or [shared code](https://github.com/ciribob/DCS-SimpleRadioStandalone/tree/master/DCS-SR-Common) between client and server, which also contains some of the network logic/parsing.

I'd also suggest checking out the [external-radio-input](https://github.com/ciribob/DCS-SimpleRadioStandalone/commits/external-radio-input) branch, which is where ciribob already started implementing the upcoming standalone client, although the code is still quite unfinished yet, but might contain some useful starters.

**Comment by etcher-be** [comment]
@MorpheusXAUT thanks a bunch man !

**Comment by rkusa** [comment]
I've just made https://github.com/rkusa/DATIS public, it runs as a DCS mod, automatically generates ATIS reports, converts them to speech and connects to SRS to broadcast the report. Maybe this helps solving your use case, or helps as a starting point for your own implementation?

**Comment by etcher-be** [comment]
Amazing !

I'll see if I can replicate the process to stream audio into SRS from what you've done.

Thanks a bunch !

**Comment by ciribob** [comment]
Solved by @rkusa 🎉
