### ISSUE TITLE
SRS don't work with harrier

### ISSUE THREAD

**Issue by webber02** [ciribob/DCS-SimpleRadioStandalone#278]
hi, i have a problem vith AV-8B

when i try to change the freq or channel in cockpit in the srs radio don't work ( the channel is not changed even in srs radio)

**Comment by LazyBoot** [comment]
Make sure Easy Communication is not enabled (or forced on).

**Comment by webber02** [comment]
Yes Easy Communication is disabled. Srs rado display only 127.000 freq and work in PTT( also volume) . Only in Harrier i have that issue.

**Comment by MorpheusXAUT** [comment]
Hi,

there's currently no known issues with the latest release and the Harrier.
As LazyBoot suggested, make sure Easy Communication is not enabled in your local settings (and not enforced by the mission, as it can overwrite it).
Are you running the latest release (1.5.4.0) and updated using the SRS installer?

**Comment by webber02** [comment]
yes all update

ok, guys, i have solved!  I have able easy comunication by mission!!

thanks!!!!!!

**Comment by MorpheusXAUT** [comment]
Glad to hear it's working! :+1:
