### ISSUE TITLE
When editing a digit/number in a bookmark IP, hitting "enter", closing and restarting SRS, the changes are lost again.

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#281]
Bookmark editing logic is broken currently. I had to entirely remove a bookmark and add again to bookmarks to make an "edit" to my bookmark.

**Comment by MorpheusXAUT** [comment]
Hi,

thanks for the report, looks like the editing slipped through when we changed the favourites to save automatically instead of having to press a "Save" button. Will be fixed for the next release.

**Comment by Dani3lNL** [comment]
Thx super much for reply on Sunday morning! :D so is it true, in the code basically the part "IF user presses "enter" key, then save new bookmark" misses? xD (I learned Java)

**Comment by MorpheusXAUT** [comment]
Yup, something along the lines of that - I added the new save logic to adding/deleting favourites, but seem to have forgotten to add it to the "value of bookmark changed" event 😄

**Comment by Dani3lNL** [comment]
aaaah! but the event "value of bookmark changed" does exist already, or?

**Comment by MorpheusXAUT** [comment]
Nope, that's what was missing - we had one for adding and removing bookmarks, but not editing. Has been added in #282
