### ISSUE TITLE
SRS window position reset (when unplugging 2nd screen) popping up twice instead of once.

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#289]
What title says. Windows notificiation sound plays, then I click that WinXP-style "OK" button and same window opens again with same sound.

**Comment by MorpheusXAUT** [comment]
Are you absolutely certain it's the same window popping up twice?
SRS will check the visibility for each of its three windows - the main (client) one, the radio overlay and the AWACS overlay. If multiple windows are not within Window's reported monitor range anymore, you'll have multiple popups for the affected windows.

**Comment by MorpheusXAUT** [comment]
The logs you've posted in #288 indicate two windows were not visible.
```
2018-10-03 19:57:56.7395 | Ciribob.DCS.SimpleRadio.Standalone.Client.UI.MainWindow | Main client window outside visible area of monitors, resetting position (2632,162) to defaults 
2018-10-03 19:59:16.7483 | Ciribob.DCS.SimpleRadio.Standalone.Client.UI.MainWindow | Radio overlay window outside visible area of monitors, resetting position (2176,345) to defaults 
```
This would result in two popups as you've describe, although they're identical popups, but will slightly differ.

**Comment by Dani3lNL** [comment]
Tried to replicate just now again, this time only once... maybe related to when I plug in my WMR headset. I will test next time (in a few days).

**Comment by Dani3lNL** [comment]
aaaah so it is the 2 things, main client and radio overlay. Can you edit the error messages, so 1st one includes "main client window" and 2nd one "radio overlay" ? That would clear it up, before other users repeat this bug report too... :P @MorpheusXAUT
