### ISSUE TITLE
all bookmarked servers wiped temporarily upon RestoreResolution event...

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#290]
Yep, unplugging 2nd screen (where I always have SRS when I don't play in WMR mode) causes bookmarks to be wiped... Restarted SRS to test, suddenly all bookmarks are back again (POOH, thank god xD I mean thank you guys that they aren't permanently wiped xD )

**Comment by ciribob** [comment]
Not able to replicate

**Comment by Dani3lNL** [comment]
You have 2 screens and had SRS on 2nd screen, then closed SRS, disconnect 2nd screen, start SRS? @ciribob
