### ISSUE TITLE
"connection sucessful" sound playing before the UI of SRS client refreshes OR >UI refresh delayed<

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#295]
Currently either there is a delay in UI refresh or the "successfull" sound is played before the connection really is "established".

**Comment by MorpheusXAUT** [comment]
No noticable delay in sound/main UI update reproducable. What minimal delay might be seen in simply caused by a UI redraw delay and irrelevant.

**Comment by Dani3lNL** [comment]
You sure it can't be caused by SRS 1.5.5.0 only being programmed with SSD in mind? I have 7 year old HDD, there might be some I/O event on Windows installation drive (C:) at that event causing a 50-500 ms delay? Just my theory. @MorpheusXAUT

**Comment by MorpheusXAUT** [comment]
No. SRS was not developed for any kind of hard drive as that's irrelevant to it.

**Comment by Dani3lNL** [comment]
"harddrives are irrelevant for any Windows program", roger......

**Comment by MorpheusXAUT** [comment]
The type of harddrive SRS is installed on is completely irrelevant to it.
SRS has basically no disk IO beside reading the config + favourites file once at startup and writing them back to disk if they're modified (which they are not if you just connect to a server).

**Comment by Dani3lNL** [comment]
But I thought SRS accesses .NET framework files in C:/Windows/Microsoft.NET ?
