### ISSUE TITLE
please change the "critical"-sounding disconnect-sound to a more "happy" sounding one.

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#296]
What title says, it makes me sad everytime I hear the disconnect sound, I think a "happier" (some major chord) sound effect will be more user-friendly.

**Comment by MorpheusXAUT** [comment]
You can replace the audio files in audio effects with whatever you prefer.

**Comment by Dani3lNL** [comment]
ah thanks!
