### ISSUE TITLE
[feature request] drag&drop server entries in Favourites menu for custom sorting

### ISSUE THREAD

**Issue by MikeyMike22** [ciribob/DCS-SimpleRadioStandalone#297]
Currently it's marking all in blue when holding left mouse button and moving mouse up/down. Instead it'd be nice to see a blue (or black) horizontal line move up/down to preview current sorting spot when the user would release the mouse button. (Maybe with an event "OnUserReleaseLMB" (left mouse button) then "saveNewCustomSorting" for example)

**Comment by D4n2020** [comment]
over 2 years later, would still be super super useful to see implemented soon! :)
