### ISSUE TITLE
Cant map hotkeys

### ISSUE THREAD

**Issue by stvnpeters34** [ciribob/DCS-SimpleRadioStandalone#30]
It will not let me map any of my hotkeys on my warthog or my keyboard

**Comment by ciribob** [comment]
Try Manually adding this registry entry and then remapping


[hotkeyfix.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/355530/hotkeyfix.zip)

It was reported here: #13 as well but I can't replicate. 

Just deleted all the registry entries and they recreated successfully.

Can you try running the program as Administrator?

What are the details of your PC? Windows version, antivirus?

**Comment by stvnpeters34** [comment]
I tried the registry and it recognized default keys but how ever i can not set them my self. So if i clear the hotkey it wont let me set them again. Also i ran as admin i am running windows 10 and no antivirus

**Comment by ciribob** [comment]
What USB devices do you have plugged in? 

There must be something the same as mvee here #13 

Sorry for the trouble, wish I could replicate!

For reference for me:
TiR 5
MFG Pedals
Warthog 
USB Headset
Keyboard
Mouse

**Comment by mvee** [comment]
TiR 5
Slaw pedals
Warthog
Keyboard
Mouse
USB-MIDI keyboard (Haven't tried without now that I've mentioned. I'll do it now)

Win10, operating system is in english, SYSTEM has full control on related registry.

**Comment by ciribob** [comment]
Ok with mvee's invaluable help we've tracking down the bug.

The Corsair K65 Gaming Keyboard reports to DirectX (which I retrieve via SharpDX ) that its a Joystick. This obviously isn't the case and so when I try to Poll the device, it fails because its a keyboard!

Please try this version which specifically ignores the K65 Gaming Keyboard.

If you dont have that keyboard, try this version anyway and send me your logs. One of your devices will probably be doing the same as mvees and reporting an incorrect device type 

:)


[SR-ClientRadio.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/356002/SR-ClientRadio.zip)

**Comment by mvee** [comment]
![image](https://cloud.githubusercontent.com/assets/17532699/16713301/21837f24-46ac-11e6-9c54-02d11d2c8e43.png)
Fiddling with this thing might do the trick too, some K65 bullshit.

**Comment by stvnpeters34** [comment]
Hi CiriBob the only thing i have a problem with now is that the client gives me default keys on my hotas but i can clear and not reset them.

**Comment by ciribob** [comment]
Hi @stvnpeters34 , Did you try the new version here: https://github.com/ciribob/DCS-SimpleRadioStandalone/files/356002/SR-ClientRadio.zip Its a special build for you.

If it doesnt work, please attach your client logs here and I can fix it in the next release

**Comment by stvnpeters34** [comment]
Yes i did try it. Here is the logs
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/358067/clientlog.txt)

**Comment by ciribob** [comment]
Thanks for posting! 

Thats odd, your logs appear to be missing the new logging for devices so I can't see the error.

Would you double check that you connected with the attached version not the original version?

If you're sure you did, I'll post a new version tomorrow evening when i'm back.

Out of interest, what USB devices are attached? Do you have the Corsair K65 Gaming Keyboard?

**Comment by stvnpeters34** [comment]
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/358366/clientlog.txt)
ok here is the log with the build you gave me.

**Comment by ciribob** [comment]
Thanks! I can see the correct logs now.

Ah you've also got a Corsair keyboard, thats causing the issue.

I'll blacklist it so that in the next release it'll work. Will do one possibly tonight or tomorrow evening.

Thanks for your help

For my ref: 1b091b1c-0000-0000-0000-504944564944 Corsair K70R Gaming Keyboard

**Comment by ciribob** [comment]
Actually as a quick test, could you try unpluging keyboard, start SimpleRadio and then configure hotkeys?  It should work. You can then plug back in the keyboard again and use as normal.

**Comment by stvnpeters34** [comment]
Unfortunately it doesnt work to set the hotkeys

**Comment by ciribob** [comment]
Thanks for testing. Will have a new build out tomorrow evening hopefully that should solve it. If not I'll blacklist more devices until it works for you :)

**Comment by splash99** [comment]
Hi Ciribob, I cannot bind any POV from my CH Fighterstick/ProThrottle. Rest of the controls works well. Could you fix it? Thanks.

**Comment by ciribob** [comment]
Ah POV isn't a button, it actually counts as an axis so will require a bit of work to fix. Will give it a go but I might take a while to fix it... will let you know after I investigate :)

**Comment by ciribob** [comment]
Linking #40

**Comment by ciribob** [comment]
#50 Linked
