### ISSUE TITLE
Add a default/briefing/lobby/mess hall channel for people out of cockpit

### ISSUE THREAD

**Issue by m4ti140** [ciribob/DCS-SimpleRadioStandalone#302]
What it says on the tin. Would it be possible to have non-radio channels for briefing and coordination when not in flight? Currently SRS relies heavily on external voice communication software to accomplish these tasks.

**Comment by MorpheusXAUT** [comment]
SRS has a spectator audio setting, which can be enabled in the server settings. Players in a spectator slot can then share communications and coordinate or plan before jumping into their respective aircraft.

Does that suffice for the coordination you need?

**Comment by ciribob** [comment]
For now, it's a design choice not to have outside DCS lobby Comms as if you are outside DCS you're likely to be using another program to communicate - either via text or voice. SRS can be used by spectators as Morpheus says as long as you enable it on the SRS settings.
