### ISSUE TITLE
Support for newly plugged in devices after start-up (TARGET Virtual Joystick)

### ISSUE THREAD

**Issue by Code-ScottLe** [ciribob/DCS-SimpleRadioStandalone#305]
Currently SRS only checks for plugged-in devices at start-up time and simply not tracking any new devices being plugged in after. This is a problem with people who use software which would create a virtual joystick at run time for their binding like Thrustmaster TARGET. In other word, it is currently required to have TARGET running first and SRS after. Also to change profile in TARGET would require also a SRS restart. 

Is it possible to have hooks detecting new devices so we don't have to get into business of restarting SRS so often?

**Comment by ciribob** [comment]
Will add to the list. Likely a manual refresh button on the controls page as a first go

**Comment by ciribob** [comment]
Implemented in #309
