### ISSUE TITLE
SRS - Arduino integration

### ISSUE THREAD

**Issue by rglasinovic** [ciribob/DCS-SimpleRadioStandalone#308]
Hello guys
First thanks for this app. It is great!

Is it possible to integrate SRS to Arduino for Input / Output, like DCS-BIOS does with DCS World?

I would like to construct a radio panel based on SRS radio and I would like to present radio frequency and channels for virtual radios that a module of DCS World doesn't have.  Also, I would like to change radio channles / frequencies from this panel for virtual radios.

Thanks!

**Comment by ciribob** [comment]
If you jump onto the SRS discord - https://discord.gg/baw7g3t Someone has implemented an arudio <> SRS interface using the UDP broadcast API 

Should be able to help 👍

**Comment by rglasinovic** [comment]
Thanks ciribob. I entered into discord, but........ how do I get that info? Just request it on chat?
Thnanks!!

**Comment by ciribob** [comment]
Yup, just post in #general and someone will be able to help :)
