### ISSUE TITLE
For stereo input channels, SRS always takes the left channel

### ISSUE THREAD

**Issue by steven-omaha** [ciribob/DCS-SimpleRadioStandalone#310]
I'm using SRS with a Komplete Audio 6 interface. I have 6 inputs, which are grouped into 3 stereo groups, e.g. 1/2 is L/R. These 3 groups are presented to Windows 10 as three different virtual input devices by the audio driver. When I connect my microphone to channel two, I have no microphone input in SRS. When I switch my microphone to channel one, everything functions normally. 

I would suggest to either have a stereo-to-mono option in the settings for stereo input, or allow to choose specific channels from multi-input devices.

**Comment by ciribob** [comment]
I've only got a mono mic and no way of simulating it as far as I know so can't build a good workaround.

I'll still leave open.

**Comment by ciribob** [comment]
Is this still the case? They should be merged now (i think)

**Comment by steven-omaha** [comment]
Just saw this update. Will let you know within a week.

**Comment by steven-omaha** [comment]
No, doesn't work. I switched on "audio preview" without connecting to a server. Can hear myself on the left channel, can't hear anything on the right channel. Tested with 1.7.5.0.

**Comment by ciribob** [comment]
Not sure why, works with stereo webcam. 

Will take another look but don't have any way of replicating. Will try a virtual audio cable

Thanks for the update

**Comment by ciribob** [comment]
Audio input api switched to WASAPI - should be fixed in the 1.9.0 release - reopen if not
