### ISSUE TITLE
AJS-37 Viggen radios swapped

### ISSUE THREAD

**Issue by viper2097** [ciribob/DCS-SimpleRadioStandalone#311]
Just got familiar with the Viggen and realized that the main radio "FR22" is mapped to com2 in SRS, and the second radio "FR24" is mapped to com1.
For my point of view, this is screwed up because FR22 is definitely the main used radio.
So is it possible to swap these two radios in SRS please?

**Comment by ciribob** [comment]
How are they laid out in the cockpit? Usually go by that.

It's been like that for a long time so I wouldn't want to just swap it. Will leave it open and see what others say

**Comment by viper2097** [comment]
Hey, thx for that very fast answer.
Can you confirm that, at the moment, the FR24 is mapped as Com1 and the FR22 is mapped as Com2 in SRS? Just to get sure that it was not me that messed something up...
So it is needed, that the FR22 becomes COM1 and the FR24 becomes Com2.
If you want to do it completely right, both would need to be Com1.
![ajs37-viggen](https://user-images.githubusercontent.com/35421711/51102500-8e0eef00-17df-11e9-92e5-8e335ee04e79.jpg)
![ajs37-viggen](https://user-images.githubusercontent.com/35421711/51102513-9535fd00-17df-11e9-990c-777de208403f.jpg)

I've attached a screenshot from the manual by heatblur, should say everything.
(FR22 is main with 844 pre stored frequencies and one customize able. FR24 is a backup radio with 3 fixed, pretored cahnnels)

**Comment by MorpheusXAUT** [comment]
Correct, COM1 is the FR24, COM2 is the FR22: https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SimpleRadioStandalone.lua#L1905

That said, I tend to agree with ciribob that switching it after quite some time of having it this way might be confusing, although I'm open to it if there's others that agree.

**Comment by viper2097** [comment]
Honestly, and without being arrogant, I would put "correct, or more likely being correct as in RL" more important then "its false, but it has been always so, thats why we are doing it also false the next few years because we got used to it".

**Comment by MorpheusXAUT** [comment]
Feedback noted :smile: :+1: 
We'll discuss how we want to handle this and update the issue accordingly.

**Comment by TOViper** [comment]
Hi folks and good morning!

Following the discussion and flying the Viggen a lot, I would really love to have them switched (following Viper2097's suggestion), despite it may confuse others flying with the current setup.
It seems much more "correct" to me as well, since the FR22 **IS** the main radio in the aircraft, and you use it 99,99999% of the time.

SRS is a good thing, since it adds much "reality".
Thanks for the work done so far!

Kind regards,
TOViper

**Comment by viper2097** [comment]
Any news on that topic?

**Comment by ciribob** [comment]
Swapped
