### ISSUE TITLE
When SRS crashes (due to PC power loss for example), config file gets corrupted

### ISSUE THREAD

**Issue by MikeyMike22** [ciribob/DCS-SimpleRadioStandalone#313]
see this screenshot.

![srscrashcausingcorruptedconfig](https://user-images.githubusercontent.com/40214892/51264424-c0bf1000-19b6-11e9-98ed-3082d265acde.jpg)

**Comment by MikeyMike22** [comment]
(in my case, PC froze, I pressed "reset" button on my PC case)

**Comment by MorpheusXAUT** [comment]
SRS writes its config file on shutdown (or under some circumstances if a setting is changed), however if the shutdown gets interrupted, e.g. by a power failure or Windows simply not giving it enough time to write the file properly, the write process will also be interrupted and leave the file in a partially written state, which corrupts it.
Unfortunately, there's not much we can do against SRS being killed while writing the config file. I guess we could create a "backup copy" before writing the actual file, in case it does get corrupted and you'd have to restore it manually.

I'll see if I can come up with something to help in such a situation.

**Comment by ciribob** [comment]
Closing for now as its a little out of scope
