### ISSUE TITLE
Application hang when disconnecting from the server after being idle for extended time

### ISSUE THREAD

**Issue by Code-ScottLe** [ciribob/DCS-SimpleRadioStandalone#315]
Sometime, after playing, i would leave SRS running and not disconnected from the server. I would leave it running for extended period of time until i realize that I haven't disconnected from the server. And when i click on disconnect after this extended period of time, the application would simply hang and need to be force-killed.

Not a major issue but not desirable either. Not sure it hangs on which call. I can do the dirty work if people are swamped with others bugs.

**Comment by MorpheusXAUT** [comment]
Thanks for the report, I believe I've encountered the issue you're describing a few times before during development, however wasn't able to pinpoint it on anything or reliably reproduce it.

Did you manage to cause the same lockup after waiting for an extended time without any inputs? That'd at least help narrow down the search.

As always, we're obviously very glad about every help we can get, so if you're up for it, feel free to dig into it!

**Comment by Code-ScottLe** [comment]
Got busy last week, will try to find time to clone the repo and built it under debug.

**Comment by ciribob** [comment]
Closing for now - let me know if you managed to reproduce
