### ISSUE TITLE
M2000C manual radio frequency update

### ISSUE THREAD

**Issue by szporwolik** [ciribob/DCS-SimpleRadioStandalone#317]
Since some time : switching between Preset/Manual in Mirage does not change frequency. 

To make a change you need to first go from Preset to Manual (or vice versa) and then modify one of manual frequency selectors (manual) or channel selector (preset).

**Comment by szporwolik** [comment]
I belive this is related to this https://forums.eagle.ru/showthread.php?t=229838 - seems to be Mirage bug, not SRS.

**Comment by ciribob** [comment]
Thanks - will close for now then
