### ISSUE TITLE
Heatblur DCS:F-14A/B

### ISSUE THREAD

**Issue by crowmium** [ciribob/DCS-SimpleRadioStandalone#322]
Unable to use radios while in the F-14. Push to talk does not work. Only hotmic intercom between crew members.

Edit: Disregard. User error.

**Comment by viper2097** [comment]
Worksnfine for me, you need to use just your normal radio commands in DCS, not the ones specified in SRS.

However: Devs, could you please add an option to choose between the old, and this new implementation?

**Comment by crowmium** [comment]
Yup, I was not aware the implementation was different on this specific aircraft. Using in game key binds worked. Disregard.

**Comment by MorpheusXAUT** [comment]
Additionally, there's the `ALWAYS allow SRS Hotkeys` setting.
Enabling this will allow you to use your SRS keybinds, even if the module would otherwise require you to use the actual in-game bindings.

Closing this for now as it's working as intended.
