### ISSUE TITLE
Pass config via CLI param

### ISSUE THREAD

**Issue by Jarvvski** [ciribob/DCS-SimpleRadioStandalone#323]
**As a** server admin

**When** I run SRS via CLI

**I want to** be able to pass in the config file as a parameter

----

This is because when running multiple instances, you require multiple config files. Currently, I've been running it from two different installs which is fine as it's very small in comparison with DCS. However it's a good QOL feature

----

@ciribob tells me that there is a `-cfg` param, so guessing it needs to be added into the docs on the wiki 👍

**Comment by ciribob** [comment]
Sorry I was being an idiot - there is a cfg parameter but only on the client - needs to be added to the server

https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/DCS-SR-Client/Settings/SettingsStore.cs#L223 - Client one

Will make this a feature request 👍
