### ISSUE TITLE
Reinject lua button?

### ISSUE THREAD

**Issue by maestro72x** [ciribob/DCS-SimpleRadioStandalone#324]
Seems everytime there is a dcs update i need to run SRS setup again to inject lua's into dcs.. could you make a button that does that from srs? or something that will verifiy the code is setup in the proper locations in dcs?

**Comment by ciribob** [comment]
The installer will do that - just run it again.

As long as you've used the installer though it should be unaffected by DCS updates as DCS updates dont touch saved games. Can you let me know where its installed?
