### ISSUE TITLE
DCS F-14: Hot mic transmission delay in intercom

### ISSUE THREAD

**Issue by andreyzh** [ciribob/DCS-SimpleRadioStandalone#328]
Greetings,
My pilot and I noticed a lag while operating SRS on F-14B intercom in hot mic setup (both cockpits). 
There is 2-5 second delay in between saying something on intercom and another party receiving it. 
This does not affect transmissions on the radios.

**Comment by uriba107** [comment]
I don't know if related, But we had the same issue. it was resolved when we changed server name from FQDN to IP address. what to you have set up there?

I hadn't tried any other radios as we were only two people, but it definetly solved the delay for us.

I'm not very fluent in code, so I couldn't hunt it down, but my best guess is that the ICS resolves the hostname on transmission rather then on initial connection.

**Comment by ciribob** [comment]
This is due to the way SRS was built as it wasn't built with a long running hot mic in mind. Requires fairly extensive changes to fix so marking as feature request

**Comment by ciribob** [comment]
Fixed in latest release

**Comment by rstoki** [comment]
Hi, just to inform you, that the problem with high latency over ICS using the Hot Mic occurs also in version 1.7.7.0. The latency builds up over time -- at the begining, it is negligible, but after 30-40 minutes it may be as high as 10 seconds. The manual reconnect to the server often helps to reduce it, but the reconnect needs to be done by both clients (i.e., both pilot and RIO in F-14B). 

Also, there is some "echo" which is audible for the speaker, when the other side is using Hot Mic setting. May this cause some sort of trouble?

**Comment by rstoki** [comment]
Just an addendum: it seems this is a server-dependent problem -- it seems to occurs on some servers with higher ping, while for servers with low ping it is not noticeable. 

Observation: 
* the connection on the AVS SRS server (82.99.130.156:5002), which is hosted in the same country and pings are low (don't know the exact numbers, but around say 20 ms), we do not noticed any problem
* on the 104th_Phoenix Dedicated (ping around 130 ms) the problem occurred "consistently"
