### ISSUE TITLE
First run always warns about window move and cannot connect, second run mostly allows a connection

### ISSUE THREAD

**Issue by thebgpikester** [ciribob/DCS-SimpleRadioStandalone#331]
AFAIK, no one else has this issue and seems Windows related
![image](https://user-images.githubusercontent.com/22999891/59430797-13bcb800-8ddb-11e9-83b7-a0d73fede58a.png)
When I try to connect first time the server drop down list is not populated. I run as Admin from the shortcut.
![image](https://user-images.githubusercontent.com/22999891/59430844-36e76780-8ddb-11e9-9d3b-a973c2a3c81f.png)
Connect does nothing in this state.
if I close and relaunch (this has been like this all year) It can either repeat or populate the server drop down
![image](https://user-images.githubusercontent.com/22999891/59430921-70b86e00-8ddb-11e9-877e-79bdca7e86c4.png)

It's odd, quirky, didn't happen in much earlier versions, started many months ago and I live with it but I'm interested to see if other people get this and why.

**Comment by thebgpikester** [comment]
ok, have steps to reproduce ( for me).

1. Open SRS on main monitor, connect to a server as usual.
2. Move the SRS window to a second monitor and close it down.
3. Open SRS and get the prompt and be unable to find favourites.

4. To fix, leave the thing on the main monitor.

Note my monitor config is a 4K > 1080 > Rift. (left to right)

**Comment by danvac** [comment]
Bindings for Favourites got for some reason broken when redrawing window after it was not visible.
`
        private void InitDefaultAddress()
        {
            // legacy setting migration
            if (!string.IsNullOrEmpty(_settings.GetClientSetting(SettingsKeys.LastServer).StringValue) &&
                FavouriteServersViewModel.Addresses.Count == 0)
            {
                var oldAddress = new ServerAddress(_settings.GetClientSetting(SettingsKeys.LastServer).StringValue,
                    _settings.GetClientSetting(SettingsKeys.LastServer).StringValue, null, true);
                FavouriteServersViewModel.Addresses.Add(oldAddress);
            }

            ServerAddress = FavouriteServersViewModel.DefaultServerAddress;
            ServerAddressPicker.ItemsSource = FavouriteServersViewModel.Addresses;
            ServerAddressPicker.SelectedItem = ServerAddress;
        }
`
I have fixed it for me redefining these binding inside InitDefaultAddress(), you may have better location for that...

**Comment by MorpheusXAUT** [comment]
Sorry for the late reply.

@thebgpikester I assume you've set your 4k monitor to a scaling > 100% for better readability? I've seen issues with that, since Windows reports window coordinates that don't appear to be visible as per monitor configuration. I've added a (config-file only) flag that disables the visibility check, if you open the `client.cfg` in your SRS install directory and change `DisableWindowVisibilityCheck=false` to `DisableWindowVisibilityCheck=true`, SRS will no longer reset your window permissions on startup.

As for the favourite dropdown also being affected by this - I'll look into this and will fix it for one of the next releases, thanks.

**Comment by thebgpikester** [comment]
Yes it's a 4K with scaling, next to a 1080. Quite honestly there are loads of apps that misbehave with different scaling, but the important thing is that the drop downs just dont appear and im not sure if this also has other effects on SRS in particular.

I'll feedback on the config change very soon, after the 1.6.1 update to see where we are.
