### ISSUE TITLE
Random disconnects from SRS server for unknown reasons

### ISSUE THREAD

**Issue by Chappy197606** [ciribob/DCS-SimpleRadioStandalone#332]
This is what was in the log file:
"Failed to decode voice packet System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."

Lag? Slow connection?
Is there an automatic reconnect option?

Thanks,

**Comment by ciribob** [comment]
This issue will be solved in the next release - its UDP based so will auto-reconnect (kind of) regardless
