### ISSUE TITLE
SRS should disconnect from a server when you disconnect ingame

### ISSUE THREAD

**Issue by Cephel** [ciribob/DCS-SimpleRadioStandalone#335]
Consider this usecase:

1. Hop on a server, notice SRS automatically connects, if configured
2. You're playing for a while but then decide to switch servers
3. SRS stays connected to the first server, so when you connect to your new server, your SRS is now misaligned, nowhere is this indicated that this happened

What I would propose is that the SRS disconnects when it detects that you left the game server. Additionally it could warn you if you connect to a new server when still connected to a session when it detects that game and SRS server are misaligned.

Lastly, this may honestly be its own issue ticket, but I would love a "connect to current server" option if you forgot SRS, already connected to a server and want to use the auto connect feature, without having to disconnect and reconnect just to get SRS to do its thing.

**Comment by ciribob** [comment]
This is already implemented - as long as the server has SRS autoconnect enabled SRS will prompt you to disconnect and re-connect to the new server if it doesnt match the current connection

**Comment by Cephel** [comment]
Hmm, could it be that the check only checks the domain? TTI for example runs all their SRS on the same server, but with different subdomains or ports I think.

**Comment by MorpheusXAUT** [comment]
As long as every server has the proper SRS address set in the (optional) server-side SRS script, it'll connect you to the correct one even if it's only the port that differs.

**Comment by MorpheusXAUT** [comment]
`Lastly, this may honestly be its own issue ticket, but I would love a "connect to current server" option if you forgot SRS, already connected to a server and want to use the auto connect feature, without having to disconnect and reconnect just to get SRS to do its thing.`
Regarding that: unfortunately, SRS has no way of knowing your current server's SRS server IP apart from the server-side script admins have to add and set the IP manually in.
Said script triggers on join, but also on slot change, so you can simply hop back to spectators and into your aircraft to get autoconnected. Not a perfect solution, I'm aware, especially if you only notice after takeoff, but it's all we are capable of adding with the limited information SRS gets.

**Comment by MorpheusXAUT** [comment]
Closing for now as it's something already supported by SRS, please re-open or create a new issue if there's problems with the current implementation.
