### ISSUE TITLE
SRS causes microphone static

### ISSUE THREAD

**Issue by crowmium** [ciribob/DCS-SimpleRadioStandalone#336]
A recent problem has cropped up that I'm not sure the origin of. Every time I connect to a server my microphone starts transmitting a large amount of static and the transmissions are broken. If I disconnect and/or close SRS my microphone is fine again and works with a variety of different programs without issue.

This affects not just SRS but other programs like Discord. Even the DirectSound from Windows gets effected when I test my mic. I've gone so far as to close all other programs and run only SRS. Even with just SRS open and connected, the issue remains. It seems like SRS is causing serious input lag and interruption. This is an odd problem because I've used SRS for months without issue until last night. Even after a restart of my computer, the problem remains.

**Comment by ciribob** [comment]
Make sure you have "Allow more inputs" off in SRS

**Comment by crowmium** [comment]
Why would that make a difference? Also, I need to have "allow more inputs" on because of the number of USB devices I have.

**Comment by ciribob** [comment]
Because of the way it polls, allow more inputs can cause issues.turn that off and it'll be fine

You can just add the device id to the whitelist.txt so you don't need it

**Comment by ciribob** [comment]
Sorry I thought there was on the Wiki - will add one

**Comment by ciribob** [comment]
Added to Wiki
