### ISSUE TITLE
There is no way to stop a crashed SRS, and start a new one

### ISSUE THREAD

**Issue by WongYueKeung** [ciribob/DCS-SimpleRadioStandalone#337]
SRS frequently crashes my game
 roughly like ten times a day
when the SRS is crashing the game, the DCS  screen will freeze, the RAM usage will keep increasing with 1GB/S rate and no limit
if I play the DCS without SRS, the game will not crash
If I try to start the SRS after it crashes
It would say multiple client running.
And there is no way you can shut down a crash process, you cannot find it in windows tray or process in task manager, but it keeps prompting that there is multiple clients.
**plz add an option to close the crashed SRS process instead of tellin ppl there is duplicated client and the new one will close**
I cannot update it or remove it because it said there is an overlay process running, and I can't find SRS in my tray(it is not hidden in the tray)
and the only way to fix it is to restart the computer

graphics card 1080ti
cpu intel 7700k
1TB SSD

**Comment by ciribob** [comment]
Please post your dcs.log and clientlog.txt from your SRS installation
If a process is running - it will be viewable and SRS will not say there are duplicates unless it can actually find the process
Please also temporarily disable any antivirus and see if that stops the issue
I havent heard of any other similar reports... So unable to replicate or offer more advice

**Comment by ciribob** [comment]
Closing for now - as no more information provided
