### ISSUE TITLE
Clicking "no" on update opens web browser

### ISSUE THREAD

**Issue by ags313** [ciribob/DCS-SimpleRadioStandalone#364]
When launching version 1.7.0.3, it shows a notification about version 1.7.0.4. If I click No (to "do you want to update"), I get a browser window open with a link to github. I would rather it didn't, I just want to open SRS in the current version and fly in DCS.

**Comment by ciribob** [comment]
Hit Cancel to not open the link

**Comment by ciribob** [comment]
Also - turn off check for Beta updates on SRS as 1.7.0.4 is a beta release
