### ISSUE TITLE
Autorestart after update 

### ISSUE THREAD

**Issue by unhappytroll** [ciribob/DCS-SimpleRadioStandalone#369]
So I was tried to do update through autoupdate utility. And it promptly rebooted my computer without any question, warning or need to. If it is made by design, I see no need in that utility to exist, tbh.

**Comment by ciribob** [comment]
Not design... Thats assumedly the silent install of the Microsoft VC Redist. I've used the /quiet flag but nothing I'd read says that is forces a reboot and as i've got it on my pc I didnt experience that.

Did you get any prompts at all?

**Comment by danvac** [comment]
Probably parameters /passive /norestart would be safer.

**Comment by danvac** [comment]
You should also check return code and notify user about it if restart is required:
https://blogs.msdn.microsoft.com/astebner/2010/10/20/mailbag-how-to-perform-a-silent-install-of-the-visual-c-2010-redistributable-packages/

**Comment by GLO3** [comment]
Are those needed:
Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.23.27820

if I already have installed:
Microsoft Visual C++ 2019 X86 Additional Runtime - 14.24.28127
Microsoft Visual C++ 2019 X86 Minimum Runtime - 14.24.28127

and 18 more older versions?

This is repack, to save space on SSD, you can download from here:
https://github.com/abbodi1406/vcredist/releases

I trying to save some space on my SSD but this is hard, when every software doing some sneaky background installs.

**Comment by ciribob** [comment]
Made a hotfix yesterday evening to add the /norestart flag alongside /quiet so should resolve it for now

I'll have a look at the rest of the flags - this post was very helpful - https://docs.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options

@GLO3  I've compiled using visual studio 2019 but its x64 so you need it alongside your x86 packages

Thanks for flagging all - never worked with the VC Redist before and kind of assumed most people would already have them installed as newer software relies on them. 

I'll close for now as this is solved
