### ISSUE TITLE
Can't connect in-game with 1.7.1.1

### ISSUE THREAD

**Issue by obfuscoder** [ciribob/DCS-SimpleRadioStandalone#371]
Since we updated client and server to 1.7.1.1 I (and only I) cannot communicate via SRS in-game.

As soon as I join the multiplayer server, SRS is doing an auto-connect to that server. I get the audio confirmation that SRS has been connected and SRS shows a green icon for server connectivity and a green one for VOIP. SRS window shows "Connected clients: X (X+1 ingame)". After a few seconds during map/mission loading, however, a yellow exclamation mark is shown at the game icon. After the mission loaded and I am at the slot selection dialog in DCS, SRS window shows "Connected clients: X (X ingame)". The error icon for game is still shown. The in-game overlay states that I am not connected to a DCS server and that I should connect to an SRS server and join a mission. Firing up the aircraft system (tried A-10) and switching on the radios changes nothing.

There is nothing in the DCS or SRS logs hinting at an error, also nothing after quitting SRS/DCS.

**Comment by ciribob** [comment]
For support - go to Discord and follow the first post exactly in #common-issues

https://discord.gg/vqxAw7H

**Comment by dwbfox** [comment]
> 
> 
> For support - go to Discord and follow the first post exactly in #common-issues
> 
> https://discord.gg/vqxAw7H

Wouldn't it be better to post the solution in the Wiki section instead of forcing people to download a chat client to troubleshoot issues?

**Comment by ciribob** [comment]
You don't have to download it, its browser based too. It's not a big ask @dwbfox

**Comment by bwheatley** [comment]
it's a big ask and i agree :) but i want this softwre to work so i guess we gotta goto the information if nobody wants to share the solution.

**Comment by dwbfox** [comment]
Or, you can just post it in the GitHub repo in wiki. That way, I don't have to sign up for a social media account  to read documentation. It's an absurd ask to even suggest it in the first place, with all due respect.

**Comment by ciribob** [comment]
@dwbfox it is and always has been in the wiki though https://github.com/ciribob/DCS-SimpleRadioStandalone/wiki#troubleshooting

90% of the time - clearing the export will fix the issue with a reinstall after

Its also free and open source - including the wiki - so feel free to contribute to the wiki if you have time.

I point people to Discord as it means that others can help with support, not just me. The chat style of support is also much more conducive to actually getting a resolution quickly. It's also worked well for years as the primary form of support so I don't see it as absurd at all and won't be changing to doing support here. Others are welcome to reply here though to any issue if they wish!

GitHub is for bugs (i.e doing X crashes it) & feature requests

**Comment by Annoyedwitsrs** [comment]
I hate this crap. Go to discord to get this or that. I searched your stupid discord. Asked for help. you all suck,. def wont donate to your patron after your stupid discord shit. ANSWER the damn question instead of telling us to search on a DIFFERENT forum!!!!

**Comment by dwbfox** [comment]
> 

The problem with discord is that it's a chat client. I can google Github discussions but I can't Google solutions that were discussed in a discord chat. I know it's sort of an upsell as well to get more people participating in Discord, but I feel like this is the wrong way to go about. Anyway, I've resolved the problem.

**Comment by ciribob** [comment]
As mentioned for both of you, it's on the linked wiki above.

**Comment by ciribob** [comment]
> I hate this crap. Go to discord to get this or that. I searched your stupid discord. Asked for help. you all suck,. def wont donate to your patron after your stupid discord shit. ANSWER the damn question instead of telling us to search on a DIFFERENT forum!!!! 

What have I not helped with on the discord?  I can't see anyone I've not replied too that hasn't need solved.

Thanks for supporting open source software!
