### ISSUE TITLE
Random disconnects from game

### ISSUE THREAD

**Issue by blackasdf** [ciribob/DCS-SimpleRadioStandalone#378]
Hello, since the last two updates i'm getting random disconnects from the game only, Server and VOIP connections are still green. If i disconnect and reconnect it works for some time and then it disconnects again. 

The issue is completely random, sometimes it stays connected for hours, sometimes it disconnects 10 times in 2 minutes. I've tried reinstalling SRS from scratch but didnt fix the issue. Any idea to troubleshoot this? Thanks

**Comment by ciribob** [comment]
Please go to Discord for support (link in help in SRS) and follow the first post of common issues, listing all the files it asks for
