### ISSUE TITLE
F-5E UHF radio allows selecting 100 and 400MHz frequencies

### ISSUE THREAD

**Issue by Santi871** [ciribob/DCS-SimpleRadioStandalone#379]
The F-5E's AN/ARC-164 UHF radio allows selecting 100 and 400MHz frequencies by placing the MHz selector to the T or the A position. This is a bug, this radio only supports 225.000 to 399.975 MHz according to the game's manual, and the A and T positions are related to Have Quick antijam functionality.

**Comment by ciribob** [comment]
This is a DCS bug then as SRS just exports the frequency that simulated radio is tuned to directly from the radio

I'll report.

Thanks!
