### ISSUE TITLE
minor bug: "Select Previous Radio" only clickable until first radio.

### ISSUE THREAD

**Issue by D4n2020** [ciribob/DCS-SimpleRadioStandalone#381]
So, while "Select Next Radio" is working fine (it will start from first Radio if last/3rd Radio is selected), "Select Previous Radio" is not working similar, it will just stop at first Radio and when pressing again stay stuck instead of switching to radio 3.

**Comment by ciribob** [comment]
Fixed in release 1.9.3.0
