### ISSUE TITLE
bug: light next to "UHF Guard" green/displaying "transmitting" when pushing PTT, although actually not transmitting (nobody replying although many players  on freq)

### ISSUE THREAD

**Issue by Dani3lNL20** [ciribob/DCS-SimpleRadioStandalone#389]
![grafik](https://user-images.githubusercontent.com/58952899/71690765-eef35680-2da5-11ea-9129-5bf16186b0fa.png)

happens when in spectator slot.

**Comment by ciribob** [comment]
It is transmitting - but coalition security is probably enabled
