### ISSUE TITLE
UH-1H TM Warthog HOTAS mic-switch correlations (hard-coded?)

### ISSUE THREAD

**Issue by bryanestes** [ciribob/DCS-SimpleRadioStandalone#391]
Mic switch appears to be hard-coded for radio 1 (forward), 2 (down), 3 (aft). Changing the settings in SRS Client has no effect on switch/radio correlations.

**Comment by ciribob** [comment]
SRS supports realistic controls where possible so you need to use the real in cockpit controls to transmit and / or change radios.

The a10c, f14 and others support in cockpit controls, so you must use dcs bindings to control

See https://docs.google.com/spreadsheets/d/1tzd996zJ1t0heZ-t1PpL7vNUIZbXl7pI6De0GThN1Qw/edit?usp=drivesdk

If you wish to always use SRS controls, enable always allow SRS hotkeys
