### ISSUE TITLE
UH-1H - Switching radios makes double clicking sound effect when using switch as PTT

### ISSUE THREAD

**Issue by bryanestes** [ciribob/DCS-SimpleRadioStandalone#392]
When "Radio Switch works as Push to Talk (PTT)" is enabled, switching radios makes two clicks (radio effects) when activating mic switch to change radio and transmit simultaneously.  Should make single click sound? It makes a single click sound when PTT is activated via a separate button.
In the A-10C, using the "Radio Switch works as Push to Talk (PTT)" makes only one clicking sound when switching radios and transmitting simultaneously.

**Comment by ciribob** [comment]
This is due to the a10c dcs ptt button

Disable allow dcs ptt to stop that and enable always allow SRS hotkeys
