### ISSUE TITLE
Saved games folder might not begin with "DCS." thus preventing auto update

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#393]
https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/f1ad16242fa72828ad0b6fa595e05a4633a78a37/Installer/MainWindow.xaml.cs#L577

Since it's possible to start DCS `.\DCS.exe --norender --server -w <string>` such as serves might be, then created Saved Games DCS instance folder is not prefixed with `DCS.`. Would it be possible to confirm the location with subfolder such as Scripts or SRS related .lua? Then the autoconnect setting will be overwriten but if one chooses to use autoupdate feature I think this would be acceptable for them.

**Comment by ciribob** [comment]
Will see what I can do to make it more robust 👍

**Comment by ciribob** [comment]
Fixed in #400

**Comment by danvac** [comment]
I don't think this is actually useful for servers. If I understand correctly server just needs autoconnect hook in Scripts/Hooks... and you have to edit it. So you will break autoconnect configuration and install useless files there?

Having folder named without DCS. was protecting it from these unwanted changes and this won't work anymore.

**Comment by ciribob** [comment]
I agree actually, will think about the best way to do it, might prompt for each folder it finds instead

**Comment by danvac** [comment]
@ciribob I would suggest to prepare another install package for servers...also making autoconnect config outside SRS files would be nice, so you don't have to edit that file for every dedicated server on that machine.

**Comment by ciribob** [comment]
Yup, easy enough change is to just not install the scripts and so make that optional on the installer

**Comment by ciribob** [comment]
Changed to add optional scripts install step in #406
