### ISSUE TITLE
Exception being swallowed without being logged?

### ISSUE THREAD

**Issue by RISCfuture** [ciribob/DCS-SimpleRadioStandalone#403]
https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/402010cf8115aa57a6998786c250e35c10e168e4/DCS-SR-Client/Network/SRSClientSyncHandler.cs#L544

We're getting random disconnects on our server. The only thing in the client log is "Disconnecting from server" with no other messages. This is the only place in the code I can see that that would happen -- the exception would not be logged if `_stop` is true, but the disconnect would happen nonetheless. Any idea what error might be being raised and creating these random disconnects?

**Comment by ciribob** [comment]
What do the server logs say?

Please post full client and server logs here

**Comment by RISCfuture** [comment]
I didn't see anything in the server logs correlating with the times of the disconnect. I can post the client logs tonight and ask the server admin to post the server logs if he still has them.

**Comment by RISCfuture** [comment]
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/4168569/clientlog.txt)

That's the client log from my last session. There were three random disconnects on 2002-02-04. I never manually initiated a disconnect.

https://drive.google.com/open?id=1iCNit9kGpPa2Bsm118hNvENzz3HT9YH0

That's the server log. You'll have to correlate the times (UTC vs. PST-8).

**Comment by ciribob** [comment]
@RISCfuture is it happening to anyone else? Can you try with allow more inputs disabled?

**Comment by RISCfuture** [comment]
Yes, it's happening to virtually everyone who uses our squadron's dedicated servers (JTF-1). I'll try it with that option disabled.

**Comment by ciribob** [comment]
Are you still seeing this issue?

**Comment by RISCfuture** [comment]
It's hard to tell now because use of our MP servers has dropped off significantly following the 2.5.6 patch. Once things ramp back up I'll be able to say.

**Comment by RISCfuture** [comment]
@ciribob Yep, flew a mission in 2.5.6 over the weekend, myself and at least one other person were randomly disconnected during the mission.

**Comment by ciribob** [comment]
Made some improvements with the 1.7.8.1 update, hopefully this is solved now

**Comment by ciribob** [comment]
Please reopen if the problem re-occurs in 1.8.0.0 - should be solved
