### ISSUE TITLE
autoupdater improvement: check if DCS is running (and prompt "please close DCS"), before downloading a new SRS version.

### ISSUE THREAD

**Issue by Dani3lNL20** [ciribob/DCS-SimpleRadioStandalone#404]

**Comment by ciribob** [comment]
Some changes to this in the installer next release

**Comment by Dani3lNL20** [comment]
what's ETA for next installer release? :)

**Comment by ciribob** [comment]
Its already out

**Comment by Dani3lNL20** [comment]
Still bugged, still downloading new update BEFORE checking if DCS is running, instead of FIRST checking for running DCS and THEN downloading if DCS not running.

**Comment by Dani3l2020** [comment]
there's no "install again". there's only "ok"... And it does re-download the update when clicking "ok" after having closed DCS.
![grafik](https://user-images.githubusercontent.com/58952899/79062758-27f07080-7c9d-11ea-8af4-5c787111e94e.png)

**Comment by Dani3l2020** [comment]
@ciribob

**Comment by D4n2020** [comment]
@ciribob was this issue fixed in 1.9.0.1 ?

**Comment by MikeyMike22** [comment]
@ciribob still a quite frustrating issue ;(
