### ISSUE TITLE
feature request, SRS overlay SteamVR integration

### ISSUE THREAD

**Issue by Dani3lNL20** [ciribob/DCS-SimpleRadioStandalone#407]
For SteamVR users (including WMR headsets), it would be awesome (if possible) if a keyboard-shortcut can make the darkgrey-green SRS overlay appear in VR with a mouse-cursor so that players can change frequencies (in the aircraft that don't have a clickable cockpit-radio) without having to lift their VR headsets. Afaik this is the required API: https://github.com/ValveSoftware/openvr/wiki/API-Documentation

**Comment by ciribob** [comment]
No the idea is that the dcs overlay is used, and hotkeys are used for control or the actual cockpit controls

**Comment by Dani3lNL20** [comment]
Ah okay.
