### ISSUE TITLE
A-10C IFF ident mic

### ISSUE THREAD

**Issue by steven-omaha** [ciribob/DCS-SimpleRadioStandalone#408]
From the A-10A flight manual T.O. 1A-10A-1, Change 8, page 1-125 

> Identification of position switch. --> MIC --> Initiates identification of position reply simultaneously with the keying of the UHF radio.

It's the same in the modern A-10C. Setting the IDENT switch to MIC currently does nothing when transmitting on UHF.

**Comment by ciribob** [comment]
Thats very helpful, thank you!

Do you know if it's the same in the UH 1 on the UHF radio?

I can add this though it'll only work if you use the dcs ptt controls I think but will see what I can do

**Comment by steven-omaha** [comment]
Sorry, I don't have any documentation for the Huey.

**Comment by ciribob** [comment]
Implemented in next release :)
