### ISSUE TITLE
wine: System.Net.Sockets.SocketException: Success

### ISSUE THREAD

**Issue by Ape** [ciribob/DCS-SimpleRadioStandalone#409]
I'm trying to run SRS 1.7.4.0 on wine (Arch Linux), but whenever I try to connect to a server the program exists with:

```
0052:fixme:winsock:WS_setsockopt Unknown IPPROTO_IP optname 0x00000017
0052:fixme:ver:GetCurrentPackageId (0x20e8a610 (nil)): stub
0052:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
0052:fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000402,(nil),0x0001,0x00000000,0x20e8cab8,(nil)): stub
0052:err:eventlog:ReportEventW L"Application: SR-ClientRadio.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.Net.Sockets.SocketException\nStack:\n   at System.Net.Sockets.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel, System."...
0052:fixme:advapi:DeregisterEventSource (0xcafe4242) stub

Unhandled Exception: System.Net.Sockets.SocketException: Success
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetIPProtectionLevel(IPProtectionLevel level)
   at Ciribob.DCS.SimpleRadio.Standalone.Client.Network.UdpVoiceHandler.Listen()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The exception message is `Success` which sounds rather weird. I realize that this issue is probably caused by Wine, but is there anything that SRS could do to mitigate the issue?

**Comment by ciribob** [comment]
Sorry no, those are the c# socket option functions which are on the winsock.dll eventually and all internal calls so nothing I can do.

Try proton? Heard good things but no idea if it supports .net

**Comment by Ape** [comment]
I investigated the issue a bit and it seems like there is a simple fix:

```diff
diff --git a/DCS-SR-Client/Network/UDPVoiceHandler.cs b/DCS-SR-Client/Network/UDPVoiceHandler.cs
index 481673f..7bf4799 100644
--- a/DCS-SR-Client/Network/UDPVoiceHandler.cs
+++ b/DCS-SR-Client/Network/UDPVoiceHandler.cs
@@ -142,7 +142,6 @@ namespace Ciribob.DCS.SimpleRadio.Standalone.Client.Network
             _udpLastReceived = 0;
             _ready = false;
             _listener = new UdpClient();
-            _listener.AllowNatTraversal(true);
            // _listener.Connect(_serverEndpoint);
 
             //start 2 audio processing threads
```

I was not actually able to build SRS on Linux, but I could remove that one line by editing the binary executable file.

With that, I can connect to a server without crashing. I think SRS might be now usable on Linux.

A proper fix could be something like this:

```diff
diff --git a/DCS-SR-Client/Network/UDPVoiceHandler.cs b/DCS-SR-Client/Network/UDPVoiceHandler.cs
index 481673f..88e5f8e 100644
--- a/DCS-SR-Client/Network/UDPVoiceHandler.cs
+++ b/DCS-SR-Client/Network/UDPVoiceHandler.cs
@@ -142,7 +142,16 @@ namespace Ciribob.DCS.SimpleRadio.Standalone.Client.Network
             _udpLastReceived = 0;
             _ready = false;
             _listener = new UdpClient();
-            _listener.AllowNatTraversal(true);
+
+            try
+            {
+                _listener.AllowNatTraversal(true);
+            }
+            catch (SocketException ex)
+            {
+                Logger.Info("Could not enable NAT traversal");
+            }
+
            // _listener.Connect(_serverEndpoint);
 
             //start 2 audio processing threads
```

**Comment by ciribob** [comment]
Happy to add that if that solved it for you? 

Surprised thats causing an issue as thats old winsock stuff rather than the audio which is the new WASAPI api

**Comment by Ape** [comment]
Yes, this solves the issue for me. I would really appreciate if you can add this to the official builds.

With this workaround I was able to talk with people on DCS servers and it seems to be stable. There are still some crashes when accessing some non-essential things in SRS UI. I will probably try to fix them later.

**Comment by Ape** [comment]
As a note for anybody else trying to uses SRS on Wine. You need to install dotnet with `winetricks dotnet452` and then set windows version to 'Windows 10' with `winecfg`.

**Comment by ciribob** [comment]
Will add 👍

**Comment by TheZoq2** [comment]
Seems like the latest two versions no longer work through wine.

1.9.0.2 gives me this on startup

> 00d0:err:eventlog:ReportEventW L"Application: SR-ClientRadio.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.MissingMethodException\nStack:\n   at Sentry.SentryOptions..ctor()\n   at Sentry.SentrySdk.Init(System.Action`1<Sentry.SentryOptio"...

1.9.0.1 starts fine, but when trying to actually use audio, I get this 

![image](https://user-images.githubusercontent.com/5312813/87225796-b0aba500-c38f-11ea-97e1-86058bae68b5.png)

This is the output in the console when pressing `audio preview`

```
00c4:fixme:mmdevapi:AEV_GetChannelCount stub
00cc:fixme:ole:Context_CC_ContextCallback (000000001A7D5CF0/000000001A7D5CF8)->(0000000001330D80, 000000001A64F880, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 0000000000000000)
00cc:fixme:ole:Context_CC_ContextCallback (000000001A7D5CF0/000000001A7D5CF8)->(0000000001330D80, 000000001A64F780, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 0000000000000000)
00cc:fixme:ole:Context_CC_ContextCallback (000000001A7D5CF0/000000001A7D5CF8)->(0000000001330D80, 000000001A64F460, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, 0000000000000000)
00c4:fixme:wtsapi:WTSRegisterSessionNotification Stub 00000000000500A4 0x00000000
00c4:fixme:msg:ChangeWindowMessageFilterEx 0x500a4 c05d 1 0x21ac58
00c4:fixme:msg:ChangeWindowMessageFilterEx 0x500a4 111 1 0x21ac58
```

My guess is that that AEV_GetChannelCount stub is to blame, but i'm not sure what to do to fix it

**Comment by ciribob** [comment]
The audio interface was changed to WASAPI for both microphone and speakers

At a guess there is something to Google at least... Good luck!

**Comment by TheZoq2** [comment]
Perfect, I'll look into that, thanks!

**Comment by PiecePaperCode** [comment]
So there is no Linux Port :( Would older versions of the releases still work?

**Comment by TheZoq2** [comment]
> So there is no Linux Port :( Would older versions of the releases still work?

I have a custom client which I've used quite successfully for the past few months here https://gitlab.com/TheZoq2/srsrs. It's not as featureful as the official client but it does work

I also noticed the readme is out of date, you can customize your hotkeys, just do `cargo run -- configure`
