### ISSUE TITLE
PTT Not Working, FA18C, Aerobatics Online. Config files included.

### ISSUE THREAD

**Issue by mirage335** [ciribob/DCS-SimpleRadioStandalone#418]
When holding down radio switch, or actual PTT keybind, neither the SRS panel indicator light, nor sound effects, indicate any transmission.

Switching radios works.

Audio preview works.

Control panel "Game Controllers" dialog box shows the vJoy buttons are indeed being pressed continuously.

Tested on the Aerobatics Online server, with the FA18C, fully started up and in the air.

Config files are tracked by git.

https://github.com/mirage335/extendedInterface/tree/e4a48332a85bcbb4bf39e4c148dd56ff717d8833/app/DCS/SimpleRadioStandalone

Please fix or advise as to what may be misconfigured.

**Comment by ciribob** [comment]
You said holding the SRS radio switch?

The radio switch is just that, a switch

You can either bind the SRS ptt or enable radio switch works as ptt in SRS settings

**Comment by mirage335** [comment]
I do not use Viacom, and tried disabling TX inhibit.

Three green plugs? I am not sure what that is about, but I guess I should look for this. On the FA18C, I do have two radios, which show unlit green indicators when switched to.

Was not aware of the Discord channel. Will follow up there. However, I assumed this was a bug because IIRC, it had been working, and ceased to.

**Comment by ciribob** [comment]
Won't be a bug as it would be more widespread so I'll close this for now but please follow up on Discord
