### ISSUE TITLE
SRS not closing when "close" on taskbar icon while "Auto connect" window open.

### ISSUE THREAD

**Issue by Dani3lNL20** [ciribob/DCS-SimpleRadioStandalone#430]
Auto connect window stays open/SRS process keeps running while taskbar icon vanishes when clicking "close" on the icon.

**Comment by Dani3lNL20** [comment]
381 MB .DMP file ("auto connect" window open while taskbar icon has closed): https://ufile.io/n819dekj

**Comment by ciribob** [comment]
It won't, that's a blocking prompt so you need to hit close
