### ISSUE TITLE
Server -> no audio sharing / client connected but leave in game status when radio is selected

### ISSUE THREAD

**Issue by zalexki** [ciribob/DCS-SimpleRadioStandalone#434]
Hey man, thanks a lot for your work !

FYI: I am new to DCS and SRS.

So ! 
1. everything is working fine for my friend and me on other servers
2. I created my dcs and srs server on a windows 7 computer
3. We are correctly connected with auto connect 

BUT
as soon as we select a radio (we fly with m2000) i can see on my client srs that i am no longer in game.

It feels like a stupid problem but i dont see any other config that can block it.

Here is the srs server logs -> 
[serverlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/4399186/serverlog.txt)

Thanks for the help !

**Comment by ciribob** [comment]
Will close for now as I use Discord for client support



Please go here https://discord.gg/xzr8g8

Please follow #common-issues first post as it sounds like an export issue
