### ISSUE TITLE
SRClient process may keep running even if SRS was closed in taskbar (bottom right)

### ISSUE THREAD

**Issue by D4n2020** [ciribob/DCS-SimpleRadioStandalone#435]
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/4400129/clientlog.txt)

455 MB .DMP file of process after having closed the trayicon: https://ufile.io/h8dcyu9q

**Comment by ciribob** [comment]
Move your mouse over it and it'll disappear

**Comment by rurounijones** [comment]
Have noticed the same thing, even when setting https://docs.microsoft.com/en-us/dotnet/api/system.windows.application.shutdownmode?view=netframework-4.8 to `OnMainWindowClose`

**Comment by ciribob** [comment]
I cant replicate this - what steps did you do?

**Comment by ciribob** [comment]
Switched audio input API to WASAPI- should fix this - reopen if not
