### ISSUE TITLE
Echo over ICS with Hot Mic setting

### ISSUE THREAD

**Issue by rstoki** [ciribob/DCS-SimpleRadioStandalone#438]
When using SRS in F-14B to communicate over ICS between PILOT and RIO, there is an echo audible to the speaker when the other party is using Hot Mic setting. We observed this in multiple setups between different people, so it is not likely to be related to HW issues. 

How to reproduce:
 - SRS version 1.7.7.0, connect to some public server, like 104th Phoenix Dedicated (208.94.240.34:5002)
 - join the multiplayer, enter F-14B with somebody as a PILOT/RIO pair
 - for RIO, turn Hot Mic ON, turn the volume knob up to max volume
 - your buddy (PILOT) will hear what he is saying (after some delay which equals to round-trip-time delay for sound over ICS) _[may be related to latency issue #413 -- at least, thanks to the echo one can easily hear how big the latency is]_

If the other party (e.g. Pilot) is using Cold Mic, the echo is not present _(which seems to be obvious, because the pilot is typically not transmitting (keying) at the same time the RIO is talking)_

If the ICS volume in the cockpit is turned down, the echo is still there but is not disrupting. 

My client is set-up as depicted on the attached picture (+5 dB Speaker Boost & NO Passtthrough):
![SRS-1 7 7 0-setup](https://user-images.githubusercontent.com/32607323/78733795-be8ffb00-7946-11ea-82a6-f52bcc44fc1b.png)

**Comment by ciribob** [comment]
Thanks for the detailed report.

The hotmic is just picking up your transmission over the speakers hence the echo and delay.

If they have a closed headset you won't hear a thing (hence why it's affected by volume changes)

If you turn off the microphone autolevel / boost in settings that will help as it won't  boost the tiniest things it hears

**Comment by rstoki** [comment]
@ciribob: Of course, both of us are using closed headset, not speakers.  This was the first thing we checked, sorry for omitting this in the initial report.  

I've tested it extensively yesterday and the unfortunate fact is, that there is really some hardware-induced echo -- there seems to be wire cross-talk between the headset speakers wires and the headset microphone wires (since they are all packed alongside and typically they are not shielded :( )
I assume this problem would be present in most of the "basic" gaming headset, like the one I own (Zalman ZM-HPS300). I heared my echoes through HotMic ICS at least from 3 different people. 

So I would change this report from "bug" to the "Feature Request" -- would it be possible to implement (optional) "Echo Reduction" filter, like in other programs (e.g., TeamSpeak)?

**Comment by ciribob** [comment]
https://cdn.discordapp.com/attachments/598575126530752540/695731268876370040/unknown.png

Please turn off Microphone Automatic Gain Control
and leave Microphone Noise Suppression on

I've only got USB headsets - hyper x and a steelseries one and It doesnt occur unless the mic can hear the speakers
