### ISSUE TITLE
UI freeze when micropone is pulled out

### ISSUE THREAD

**Issue by rstoki** [ciribob/DCS-SimpleRadioStandalone#441]
When the microphone is pulled out, the "loss of capture device" causes UI freeze of SRS Client. 
Tested version: 1.7.7.0 

How to reproduce:
1) connect to some SRS server, connect to EAM (AWACS mode)
2) open AWACS overlay, confirm SRS is working fine, PTT buttons works etc. 
3) pull out the microphone cable from PC --> SRS client freezes 

It would be better if SRS can to tolerate the absence of recording device and 'recover' when the microphone is plugged-in again. As a bonus, it may be indicated by some icon/text informing the user that no microphone is detected, like TeamSpeak does.

**Comment by ciribob** [comment]
Known - but unfortunately no work around due to the library in use
