### ISSUE TITLE
Auto-Updater not available as unattended install

### ISSUE THREAD

**Issue by ozdeadmeat** [ciribob/DCS-SimpleRadioStandalone#443]
Is there a way to run the auto-updater and auto agree to all of the dialogs? I want to run an update script for SRS while my server is running an update on the DCS Server. Is this currently possible? I havent been able to find anything on this capability.

**Comment by ciribob** [comment]
Currently not possible but could be done with a -dedicated flag?

**Comment by ozdeadmeat** [comment]
Hey mate. 

Executing the SRS autoupdater should have a silent mode for dedicated servers so that there is no prompt for a user.

Currently running the autoupdater throws up a directory, opens a webpage and prompts the user for decisions. The intent for a flag '-dedicated' on the srs updater to complete an automated install based on the initial installation options that were selected and then conducts them without prompting the user. 

Savy admins can then do a check via powershell to see if the srs update process is complete and then execute dcs and srs.

**Comment by ciribob** [comment]
Fixed in the latest release
