### ISSUE TITLE
A-10C HOTAS Control

### ISSUE THREAD

**Issue by crow0827** [ciribob/DCS-SimpleRadioStandalone#448]
A-10C doesn't work ingame radio PTT.

**Comment by ciribob** [comment]
Currently disabled - 

change this to a 1

https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SRS/Scripts/DCS-SimpleRadioStandalone.lua#L1360

In Saved Gamed/DCS/tech/mods/DCS-SRS/scripts

**Comment by ciribob** [comment]
Likely to be re-enabled in the next update - pending vote
