### ISSUE TITLE
Add Awacs Radio

### ISSUE THREAD

**Issue by ciribob** [ciribob/DCS-SimpleRadioStandalone#45]
Add support for AWACS / GCI Radio

Add 10 radios. Each can be interdependently controlled via mouse, still keep single PTT 

Radios can be toggled on and off, also need to support the encryption from A10c

Need Toggle for Guard as well

**Comment by Nossarian** [comment]
If possible, creating a mobile app for this feature (even further down the road as a second enhancement) I could see being very useful. I understand DCS wouldn't be run on a mobile device, but you necessarily need it since the User would not be in a DCS module typically.

**Comment by ciribob** [comment]
In theory I could add the interface to a Mobile, but the sound would be from the PC unless I can figure out how to get opus on iOS / Android :)

Partially implemented in #83

**Comment by ciribob** [comment]
Implemented in #110
