### ISSUE TITLE
Feature request: add backup and emergency ICS for F14.

### ISSUE THREAD

**Issue by WelshZeCorgi** [ciribob/DCS-SimpleRadioStandalone#450]
Unable to talk to Pilot or RIO after hit takes out the normal ICS, even if backup and emergency ICS is selected and still working.

**Comment by ciribob** [comment]
@gyrovague - sorry for the tag but I dont follow this at all 😅 

Any pointers?

**Comment by WelshZeCorgi** [comment]
Sorry, I can try to explain in further detail. 

on the DCS F-14, there is a switch on the left side that has "B/U", "norm", and "Emer" selectable positions. in the event that "norm" fails, where the ICS is not working, severing communication between the Pilot and RIO, they can both select B/U (for backup) to try and communicate through that channel or the third "emer" option which is an emergency channel that uses the UHF VHF radio to communicate between Pilot and RIO.

Perhaps you can add 2 additional channels in the ICS, B/U and Emergency that the RIO and Pilot can select. That if the ICS system becomes damaged, they can select the other two channels to continue communication if the systems are still intact.

Sorry, I'm not an expert in programming. I'm self taught and know only a little.

**Comment by gyrovague** [comment]
@WelshZeCorgi make sure press-to-talk is engaged, AFAIK the "hot mic" doesn't work in those backup modes (by design).

**Comment by ciribob** [comment]
Will close for now , as it looks like it's working correctly

**Comment by WelshZeCorgi** [comment]
Ok, thanks, sorry for the confusion.

**Comment by ciribob** [comment]
No worries!
