### ISSUE TITLE
Installer not detecting steam edition 

### ISSUE THREAD

**Issue by tator** [ciribob/DCS-SimpleRadioStandalone#453]
I have DCS in `C:\SteamLibrary\steamapps\common\DCSWorld\`
and SRS in `C:\Program Files\DCS-SimpleRadio-Standalone\`

DCS-SRS Installer is `Unable to find DCS folder in Saved Games!`

![Capture](https://user-images.githubusercontent.com/6314436/81035104-1d219980-8e5f-11ea-8d56-3d7406c18893.PNG)
![Capture2](https://user-images.githubusercontent.com/6314436/81035108-201c8a00-8e5f-11ea-9c61-6105f245bb10.PNG)

**Comment by ciribob** [comment]
For support, please use Discord next time :)

Please read the instructions again - you've pointed it at the installation folder of DCS, not saved games.

Point at your saved games folder (it picks this by default)
