### ISSUE TITLE
Autoupdater immediately starting an installation upon download

### ISSUE THREAD

**Issue by unhappytroll** [ciribob/DCS-SimpleRadioStandalone#455]
When it finishes download an update and shows main window, it immediately begins installation and shows window about installing the scripts, without any buttons pressed. That way location cannot be changed or  installation cancelled, if needed.

**Comment by ciribob** [comment]
That is by design

If you want to customise things, run the installer manually and don't use the autoupdater

The autoupdater assumes you want to do just that, autoupdate everything with no changes (it'll use the last settings from the installer)

**Comment by unhappytroll** [comment]
ok, I see
