### ISSUE TITLE
F-5 radio volume goes over 100%

### ISSUE THREAD

**Issue by dirkan91** [ciribob/DCS-SimpleRadioStandalone#456]
When adjusting the volume for the F-5 in-game, the volume on that specific radio in SRS goes over 100% when turned up to maximum.

**Comment by ciribob** [comment]
![YNuTf](https://user-images.githubusercontent.com/786992/81786056-16e28b80-94f7-11ea-8fa1-0f7c0441125c.jpg)

Thanks! I'll fix for the next release

**Comment by dirkan91** [comment]
You're awesome. Thank you!

**Comment by ciribob** [comment]
Fixed in #457 in the next release
