### ISSUE TITLE
Send on multiple radios/frequencies at the same time

### ISSUE THREAD

**Issue by obfuscoder** [ciribob/DCS-SimpleRadioStandalone#460]
Is it possible to support sending on multiple radios at the same time? Like having one radio on ground frequency and the other on tower frequency? If there is just one station manned IRL, the ground radio is set up so that it relays all transmissions to the tower frequency. It would be nice, if SRS would support this somehow. It could be done by either having a relay setup or by allowing to activate two or more radios with the same PTT button and transmit on those radios at the same time.

**Comment by ciribob** [comment]
Already a feature - see the Simultaneous transmission feature on the AWACS / GCI panel

**Comment by obfuscoder** [comment]
Ah that's good to know. Although I think having an actual relay (also transmitting radio calls on one frequency which are being received on another) is also necessary for this to be effective and to avoid stepping onto each others toes. I believe this was already requested with #129.

**Comment by ciribob** [comment]
Yup already asked for - very tricky to implement but on the list
