### ISSUE TITLE
Feature request: induce breathing effects into voice stream depending on G-load

### ISSUE THREAD

**Issue by destotelhorus** [ciribob/DCS-SimpleRadioStandalone#465]
If you're pulling 7.5g and are transmitting on the radio, then adding hard breathing and potentially even the hiccups up to the point of the person being able to *only* transfer hiccups would be adding a lot to immersion.

**Comment by obfuscoder** [comment]
Shouldn't the pilot himself do this? If he wants immersion, he should play his part too ;-)

**Comment by ciribob** [comment]
I'd need really good effects that I've struggled to find royalty free so I'll close for now
