### ISSUE TITLE
AutoUpdater modal dialog blocks interface

### ISSUE THREAD

**Issue by GeeRez** [ciribob/DCS-SimpleRadioStandalone#468]
On running SRS-AutoUpdater.exe, the main interface appears and instantly another modal dialog box appears with message "Do you want to install the SRS Scripts required for the SRS Client to DFS?"
Regardless of pressing Yes or No, the installation completes, closing the entire installer without allowing further interaction.  It is not possible to change install location or uninstall.

**Comment by ciribob** [comment]
Yes that's by design. If you want to change things, run the installer not auto updater

**Comment by GeeRez** [comment]
Ok. I didn't realize there was separate installer.  The install instructions here:
https://github.com/ciribob/DCS-SimpleRadioStandalone/releases
Mention two methods to install, 1) a .zip to manually extract and run install or 2) file SRS-AutoUpdater.exe as the alternative. 
Using the autoupdate method I never saw the installer.exe inside the .zip and it is not part of the final installed files.  So once installed by that method, there is no obvious way to uninstall or reconfigure.

Please consider any need to update documentation or files and feel free to close this issue.
Thanks!

**Comment by ciribob** [comment]
A few people have come unstuck with this, I'll likely change the autoupdater to just run the installer as normal
