### ISSUE TITLE
feature request: output different radio channels on different audio outputs

### ISSUE THREAD

**Issue by poulet67** [ciribob/DCS-SimpleRadioStandalone#469]
If there is some way to do this already I apologize, and please let me know how to go about it.

Kind of an esoteric request, but I want to be able to output audio from different radios on different audio channels/devices.

Appreciated.

**Comment by ciribob** [comment]
The best way is to pipe your audio through to something like banana voice mixer, and take the left and right channels through to different outputs

It's definitely not something I'd add as a feature and it's not how it works in the aircraft either but hopefully with an audio mixing tool it should be doable
