### ISSUE TITLE
for CA units, SRS uses the location of the camera for LOS calculations

### ISSUE THREAD

**Issue by steven-omaha** [ciribob/DCS-SimpleRadioStandalone#470]
In our virtual wing, we have players acting as JTAC for CAS scenarios. The JTAC assumes control of a ground unit using CA. The JTAC then uses the binocular mode to scout the area, and the F10-map for triangulation, friendly unit positions, etc.

The position reported by SRS is not the position of the ground unit, but the position of the camera view. This means when a player jumps from first-person view to F10, the SRS position changes. When the map view is dragged around, the position changes. When you zoom in and out in F10, the altitude changes. In mountaineous terrain, this often leads to loss of radio contact to our CAS flights.

No matter where the camera is located, SRS should always use the position of the unit currently controlled by the player.

**Comment by ciribob** [comment]
Unfortunately there is no way to detect which vehicle you control reliably so I have to go off the camera position

The only thing I can suggest is a button to disable the line of sight position, or pause the position so you can in effect save the position to the unit and then do whatever you want

**Comment by steven-omaha** [comment]
That would be a good workaround!

**Comment by ciribob** [comment]
With the latest update this should be much improved as the Fresnel effect is actually working now!

Can you retest and see how it goes?

**Comment by steven-omaha** [comment]
Wilco, thanks!

**Comment by ciribob** [comment]
Going to close for now, guessing the position fixed worked
