### ISSUE TITLE
Feature Request: Carrier Deck Megaphone

### ISSUE THREAD

**Issue by maillouxc** [ciribob/DCS-SimpleRadioStandalone#471]
My squadron had an idea that I think would be really neat. Implementing the public address system so that all aircraft on the deck of the carrier could hear it would be really need for someone playing the LSO/ATC role in the supercarrier.

Ideally it would have some echo effect rather than sounding like a radio transmission, and would not require aircraft to be tuned to any particular frequency, instead just requiring them to be in the vicinity.

**Comment by ciribob** [comment]
Sorry I missed this! 

Unfortunately this would be quite a difficult thing to implement so I wont be looking at this for now
