### ISSUE TITLE
SRS causing massive fps issue.

### ISSUE THREAD

**Issue by FatherCool** [ciribob/DCS-SimpleRadioStandalone#484]
Last night I used SRS version 1.9.0.3 for the first time on our MP server and I was left with a flight running at between 1 and 10 fps after about 30 mins flight time. Prior to that it was ok.

I RTB'd as I wasn't sure what the issue was and while on the way back I shut down programs that may have been taking bandwidth thinking it was a network issue. I shut down Teamspeak and then SRS, once SRS was closed the FPS returned to stable 60 fps. I restarted TS and it still remained at 60 FPS, conclusion being that SRS was causing very low FPS (never experienced it before) and choppy audio quality.

What could cause this to happen, previous SRS versions have never caused this for me.

**Comment by ciribob** [comment]
I'd be pretty surprised, as SRS sends data over UDP and can't block DCS

There was a lua memory bug which I've left as an open issue if you press a certain key combination.

Can you replicate it? If not I can't investigate.

Nothing has changed in 1.9.0.3 or really in years with how SRS interfaces with DCS

**Comment by FatherCool** [comment]
Thanks ciribob. I have not played the game since however it was 100% SRS that was causing it. As soon as I shut it down the FPS shot back upto a stable 60 (I have V sinc on) and stayed there. Never had it happen before. It could be a leak of some sort as it wasn't there at take off but gradually got worse as the flight went on. I will check back with you after further flights.
Cheers FC

**Comment by ciribob** [comment]
By any chance did you enable allow more inputs on SRS? If so turn that off

**Comment by FatherCool** [comment]
No I have never had that turned on.

**Comment by FatherCool** [comment]
> I'd be pretty surprised, as SRS sends data over UDP and can't block DCS
> 
> There was a lua memory bug which I've left as an open issue if you press a certain key combination.
> 
> Can you replicate it? If not I can't investigate.
> 
> Nothing has changed in 1.9.0.3 or really in years with how SRS interfaces with DCS

What is the key combination and does it cause it or stop it?

**Comment by ciribob** [comment]
#174 issue

**Comment by FatherCool** [comment]
Hi this did not stop the issue. It starts off ok but gets worse as the mission goes on.

**Comment by ciribob** [comment]
Please go to the SRS Discord and follow the support there https://discord.gg/Ajzxqxj
