### ISSUE TITLE
Feature Request: Server Output channel audio to file ( one file per channel / as configured )

### ISSUE THREAD

**Issue by hbjonsson** [ciribob/DCS-SimpleRadioStandalone#489]
Hi

It would be great if the SRS feeds/buffer from server side could be output (recorded) to file ( i.e. mp3 ) and those files would be separate per set channel, or as configured.

The use case for this would be:

1. Live streaming of channels and recordings ( think LiveATC.net )
2. Debriefings - coupled with programs like TacView - the audio files could be synced and used during play-by-play.
3. Videos / post production - would enable editors to add voice comms on separate audio channels as needed.

**Comment by obfuscoder** [comment]
Uh I would LOVE to have the audio recording of a cockpit and sync it with TacView. That said, I don't need SRS to do this. I can simply record audio (and video) locally just as it is done with DTC in military aircraft. In the end, this needs to be a feature supported by TacView.

**Comment by ciribob** [comment]
Implemented as of the latest release
