### ISSUE TITLE
Switch Client to Caliburn

### ISSUE THREAD

**Issue by ciribob** [ciribob/DCS-SimpleRadioStandalone#49]
Switch client to proper MMVM with Caliburn like the server

**Comment by ugene143** [comment]
I started to port the client to Caliburn (mainly to become familiar with it).  
I never used Caliburn before, so probably it is not properly integrated^^.
https://github.com/ugene143/DCS-SimpleRadioStandalone/tree/caliburn_client

**Comment by ciribob** [comment]
Thank you very much for this, unfortunately I wont have time to look for a while but if you do get it switched over send me a pull request :)

Thanks again, and happy Christmas!
