### ISSUE TITLE
Turning auto connect off doesn't work.

### ISSUE THREAD

**Issue by cecil1527** [ciribob/DCS-SimpleRadioStandalone#492]
When you join a server and SRS starts/connects, sometimes it will minimize DCS, which causes its own problems where DCS goes to a black splash screen with the DCS logo and never recovers and you have to kill the game and start over.  The point is, I thought I'd just turn off auto connect in the mean time so I'd never have to deal with it and I can just start SRS/connect on my own after DCS finishes loading, but it doesn't work.  Setting auto connect to off still forces you to connect when joining a server with SRS.  The server I was joining was Hoggit's PGAW server.

**Comment by cecil1527** [comment]
Nevermind, I found out the option to do what I want (not have SRS auto launch) is in the game under the SRS special menu tab.  I guess I don't know what disabling auto connect is supposed to do.

**Comment by ciribob** [comment]
Auto connect and auto launch are different things

Dcs has an option to launch SRS and connect

Srs has an option to ignore the auto connect if it's already launched
