### ISSUE TITLE
新的A-10C II 兼容性请求

### ISSUE THREAD

**Issue by HappyVoo** [ciribob/DCS-SimpleRadioStandalone#493]
首先抱歉我不会英语，我怕我表达会错误
我的请求是新增关于A-10C II的兼容性问题
目前A-10C II使用会出现：无法切换频道，需要手动更改，但有的人使用会连手动更改都不行，请求新增兼容性
再次感谢伟大的工程。

**Comment by ciribob** [comment]
I've tried with Google Translate

The A10C II is working fine with the latest SRS Release

To make it easier to use - use the settings:

"Always Allow SRS Hotkeys" - Enabled
"DCS PTT" - Disabled
