### ISSUE TITLE
SRS Transponder reveals "private information" even when Transponder is off

### ISSUE THREAD

**Issue by rstoki** [ciribob/DCS-SimpleRadioStandalone#495]
It seems that SRS server is outputting Transponder settings also when the transponder is off.  
Since the LotATC server/client is not doing a proper filtering/conditioning, it is possible for the operator to see code-editing even if the pilot switched off the transponder. 

How to reproduce:
 - pilot takes F5, sets the transponder, turns it on, including M4. All using cockpit-integration (not by using SRS-overlay)
 - LotATC operator will see the transponder codes. 
 - pilot turns off transponder
   ==> UDP packets (from SRS to LoatATC on port 10712 by default) still contain the internal setting of the transponder, of course with the "status: 0") 
 - LotATC operator still see the previous transponder code
  - pilot starts to modify the code (in cocpit)
 - LotATC operator can see "live", how the code changes (of course, there is those 2s refresh (packet) rate)

I would suggest that the transponder information are not sent at all (in the UPD packets) if the transponder is turned off or inoperable. This would closely match the real-world physics (i.e., transponder does not reveal any of its internal information until it is turned on).

**Comment by ciribob** [comment]
Fixed in #688 - thanks!
