### ISSUE TITLE
DCS.openbeta_server folder not detected

### ISSUE THREAD

**Issue by flyingdan** [ciribob/DCS-SimpleRadioStandalone#497]
Attempting to deploy SRS 1.9.2.1 on a machine running the dedicated Open Beta server. The installer isn't finding the directory `Saved Games\DCS.openbeta_server` as a valid install location
![image](https://user-images.githubusercontent.com/1051205/97821837-b9601800-1cab-11eb-804d-75f8fc15585c.png)

![image](https://user-images.githubusercontent.com/1051205/97821907-f75d3c00-1cab-11eb-8102-bd8a84fffe99.png)

**Comment by ciribob** [comment]
That is correct, a server install is not valid

Please read the instructions on the installer and untick install scripts

Client scripts shou never be installed on the server. Optionally the autoconnect lua can be manually installed
