### ISSUE TITLE
Add a commandline option to stop the update dialog opening and doing its thing

### ISSUE THREAD

**Issue by madwax** [ciribob/DCS-SimpleRadioStandalone#502]
This request is based on two real-world things
1) I've experienced way to much 'discussions' with fellow virtual pilots about SRS and its always asking to update on startup even if you pressed cancel before.  While I would agree with some the cancel should mean it goes silent till the next version I just update and have done with it.
2) I'm writing a DCS server hosting platform and every time I start an old version of SR-Server.exe the update dialog pops up. 

I'm not asking for anything to effect default behavior but a command line switch would be cool

**Comment by ciribob** [comment]
There are already command line switches for servers - check the SRS discord for details 👍 

I'm not keen on changing the update behaviour for clients - its on startup it will say you need to update, and people should always run the latest version or support becomes a nightmare for me
