### ISSUE TITLE
Clarification on what is being sent to google-analytics and why?

### ISSUE THREAD

**Issue by madwax** [ciribob/DCS-SimpleRadioStandalone#503]
I've noticed that Ciribob.DCS.SimpleRadio.Standalone.Common.Network.Analytics sends stuff to google analytics? 
I have never read a statement on what data is being collected, is there one? If not there should be to be legal (at least in the UK)

**Comment by ciribob** [comment]
https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/DCS-SR-Common/Network/Analytics.cs

You can see the extent here

I don't have a privacy policy - and i'll have a look at getting one

The why is it gives me a vague idea of usage - and whether I should keep supporting the application or not, as it takes a lot of work to support and keep up to date. Without this I'd have no idea of the usage, and what versions are out there.

The full extent of logging is:
A randomly generated ID
The version of SRS
If its server or client
Timestamp of startup

This is only done on startup as a single event sent to GA - and thats it

IP address is not logged - as that option is disabled in Google Analytics

**Comment by ciribob** [comment]
Further to this - I did vaguely google this a while ago: https://gdpr-info.eu/recitals/no-26/

Looking at this - its for statistical / analytics purposes - and has no PII (IP being ignored as the only possible bit of PII) so not sure I do need anything

Feel free to push back / provide some more info - but looks ok as is from the above link

**Comment by madwax** [comment]
Hell what you've put up on this issue is for me good enough, you've said what you are collecting and why. Anyone asking the same thing will find it and know.  
Soz to meany Data Protection/GDPR/Info sec 'training' sessions in the past lol

**Comment by ciribob** [comment]
👍 no worries at all - will leave this up then for posterity

**Comment by Peliia** [comment]
I probably sound dumb, but the randomly generated ID is generated on each event, right? Because if it were fixed per install, that might be classified as pseudonymization instead of anonymization?

**Comment by ciribob** [comment]
The client id is fixed at install, as that groups events together but it's not not identifiable, as there is nothing that can be used to figure out anything else

IP address isn't logged, nor is anything around hardware or the machine so the stats are just X number of SRS versions launched yesterday so it's anonymised. There is no way to work back and figure out who anyone is so as far as I can see, meets the requirements under gdpr, no PII and specifically for stats
