### ISSUE TITLE
Fade-in fade-out for the overlay

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#51]
If overlay is used transparent it could fade in when transmitting or receiving to indicate radio activity. Same idea as in screenshots. I've heard that multiple times when our group has been testing different radio plugins.

![image](https://cloud.githubusercontent.com/assets/17532699/16844343/787347d0-49ed-11e6-9c07-2f291e878682.png)

![image](https://cloud.githubusercontent.com/assets/17532699/16844370/8cffff9a-49ed-11e6-83f6-cea0eca43a58.png)

**Comment by ciribob** [comment]
Thats an interesting idea. 

What I really want to do is bring the overlay into the game properly using:

https://github.com/spazzarama/Direct3DHook

If you try the sample project, it does work! You can hook DCS and inject arbitrary data. In theory as WPF is DirectX based, you can take the image buffer as bytes and inject directly into dcs which is my long term goal. 

Want to have a go? :+1:

**Comment by mvee** [comment]
I highly doubt I'd succeed to do that. But your vision does sound a good one.

**Comment by ciribob** [comment]
I'm not sure I'll succeed either... I'll leave it to last as I think it will be a lot of work to do it well

**Comment by ciribob** [comment]
Hopefully superseded by the work on the InGame Overlay
