### ISSUE TITLE
encryption not needed or called “useless”

### ISSUE THREAD

**Issue by daviddou80** [ciribob/DCS-SimpleRadioStandalone#514]
First of all, thank you very much for your hard work on SR, this is a very, very good software, thank you, we love it.We have some suggestions, or ideas, which I would venture to discuss with you to see if they will be adopted by you or if you plan to improve them in the future.We found that the SR's encrypted communication function seems to be somewhat imperfect, or called "useless". While “Coalition security” in server settings is on, there is no need for communication encoding，because neither side can hear the other at the same frequency, whether or not the channel is encrypted. But encoding will malfunction while Coalition security is off, meaning that players can still hear what opponents said in their encoded channel. Our suggestion is that when the "Coalition Security" is set to off, both parties can hear each other's communication at the same frequency when it is without encryption, but when one party's frequency is encrypted, the other party cannot hear the communication. We think this is the only way to show the value of encryption, otherwise it would be a useless piece of furniture.Thank you again for your efforts and great contributions and  looking forward to your reply.

**Comment by ciribob** [comment]
How you have described it works is exactly how it works

Coalition security is an obviously non realistic setting, but makes settings up communication on a multiplayer server quick and easy

If coalition security is off and encryption is enabled on the server (you have to turn it on) and you use encryption in your aircraft, the encrypted communication won't be heard.

Try it between three a10cs, encryption is on when there is an E on the overlay followed by a number.
