### ISSUE TITLE
suggestion: enable HAVEQUICK and VHF, UHF, HF and FM effect tones by default, unless several people complained about it already

### ISSUE THREAD

**Issue by MikeyMike22** [ciribob/DCS-SimpleRadioStandalone#516]
Since the HAVEQUICK and VHF, UHF, HF and FM effect tones are an amazingly realism-increasing addition, please enable them by default for the next SRS-release! It makes SRS a whole new experience!

**Comment by ciribob** [comment]
Unfortunately people did complain but I can always try again/ ask in a poll

**Comment by MikeyMike22** [comment]
yes, please make a poll.
