### ISSUE TITLE
UH-1H multicrew: radio trigger not working correctly

### ISSUE THREAD

**Issue by m4ti140** [ciribob/DCS-SimpleRadioStandalone#517]
When flying multicrew UH-1H with (cold mic, not tested how the hot mic is affected since the update just dropped) the co-pilot radio trigger is not recognized correctly from in game bindings (presumably issue with DCS itself), as only the radio PTT (second stage) works. When using SRS bindings it does not acknowledge the helicopter "logic" behind the switch (essentially same issue as in Mi-8) - binding first stage to ICS and second stage to PTT causes the radio to switch to intercom only when passing first stage, independent of radio selector knob.

On pilot side the radio trigger still works, but there are other issues: the radio tone for the selected radio starts playing when depressing the trigger to first stage, even though only intercom is spoken to when that happens.

**Comment by ciribob** [comment]
The Huey is a bit confusing - but it is working as intended, however there are severe limitations with the implementation as the aircraft is missing the appropriate signal distribution panels for each crew member.

With the latest SRS update 1.9.4.0 if you - **AS THE PILOT**
- Enable DCS PTT Controls in SRS
- Disable Always allow SRS Hotkeys
- Bind PTT in SRS

You will have
- always on Intercom hotmic with all crew members
- Ability to select the radio you transmit on with the radio selector wheel in cockpit

When you press the **SRS** PTT - it'll transmit on whatever you've selected on the wheel.

Alternatively - there are TWO DCS keybinds that will also work

ICS PTT
Radio PTT

Those are bound in DCS and again work as intended - pressing the ICS PTT as Pilot will transmit over the intercom - redundant as hotmic is on
Pressing the Radio PTT will transmit over the radio 
This also works by clicking on the collective

As Co-Pilot / Other Crew member - There are NO other panels that you can control - so you're stuck with whatever the pilot is doing (DCS limitation. 

You have two options - keep the settings above to have a hot mic with the crew 

OR

Enable Always Allow SRS Hotkeys
Disable DCS PTT in SRS
Enable Radio switch works as PTT in SRS
Bind Radio 1,2,3 & Intercom

With those settings - pressing and holding a radio bind or intercom bind will select and transmit on the selected radio/intercom. This works well with the warthog 4 way comm switch. There are many variations on this though but the key ones are 
Enable Always Allow SRS Hotkeys
Disable DCS PTT in SRS

As this puts SRS (not DCS) in charge of the currently selected radio and the PTT controls
