### ISSUE TITLE
[Feature request] Please add "Push to Talk Push Delay (ms)"

### ISSUE THREAD

**Issue by Joghurt** [ciribob/DCS-SimpleRadioStandalone#518]
Same as "Push to Talk Release Delay (ms)", but for the start of the transmission.

I am using the same buttons on my HOTAS for SRS that I use for the Comms menus, in "Radio Switch works as Push To Talk (PTT)" mode. The problem is that when I now use the Comms menu while connected to an SRS server, there are two short clicks.

With the requested push delay option I could set it to, say, 100ms and could prevent those unnecessary clicks.

**Comment by ciribob** [comment]
This will be in the next release - thanks for the suggestion! 👍
