### ISSUE TITLE
Outgoing Audio Monitor Muffled

### ISSUE THREAD

**Issue by Peliia** [ciribob/DCS-SimpleRadioStandalone#519]
When using the optional mic output/passthrough option of SRS, the sound comes out muffled and somewhat distorted. Other players hear me just fine. This came to my attention from a fellow wing pilot who experienced this same issue.

Recording linked below, made via OBS, using an audio device of my monitor's jack, which I do not use. Also tried listening live through headphone output with same result.
https://cdn.discordapp.com/attachments/292244530374246400/797109869177471016/Monitor_muffle.ogg

SRS v 1.9.4.0

PC Specs:
i7-3770
GTX 1060 3 GB
24 GB RAM

Edit: The wing pilot who told me of this issue uses a virtual audio device to direct the mic passthrough for OBS to be recorded.

**Comment by aleksi-kangas** [comment]
Can confirm the issue with 1.9.4.0. Microphone passthrough with VB-Audio Cable used to work in 1.9.2.1 if I remember correctly.

Passthrough itself seems to work correctly in a sense that the audio is passed for the device (in this case Virtual Cable) properly. 

- Disabling *Radio Voice Effect* and listening to the passthrough audio reveals that microphone input is relayed correctly. 

- Enabling *Radio Voice Effect* results in a muffled audio in passthrough, while everything else remains normal.

- Disabling/Enabling *Clipping Effect* didn't resolve the muffled audio.

The other effects seem to work fine.

Thanks for this awesome software and hopefully this minor issue is resolved in the upcoming releases.

**Comment by ciribob** [comment]
Thanks for the reports and recording

Fixed internally and will be in the next release

**Comment by ciribob** [comment]
Fixed in #522
