### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Leopard2A5** [ciribob/DCS-SimpleRadioStandalone#523]
Hi!

First of all thanks for this awesome piece of software!

I'd love to see keybindings to be part of the profile, so that you can easily change them from aircraft to aircraft. Some of us like to bind keys as close as possible to the real thing, so mic buttons are in different places :)

Keep up the good work!

**Comment by ciribob** [comment]
They already are linked to the profile - and you can even autoselect the profile based on the aircraft you're in (automatically)

Have a look at the SRS Discord for details 👍
