### ISSUE TITLE
Bug: clients-list.json is not a propper JSON when user with quotation mark (") joins

### ISSUE THREAD

**Issue by szporwolik** [ciribob/DCS-SimpleRadioStandalone#525]
User named **Colt 1-1 | "Rudy" Liseł** joined the DCS and SRS servers causing that _clients-list.json started to be not a proper JSON file. The " symbols shall be escaped prior putting to json file.

**Comment by ciribob** [comment]
Please upload the export file - it's run through a very common .net file so I'd be surprised

**Comment by szporwolik** [comment]
Sure - attached.

Thanks! :)
[clients-list.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/5957369/clients-list.zip)

**Comment by ciribob** [comment]
Nope looks like its valid: https://www.dropbox.com/s/8ehb44cgod04me6/Screenshot%202021-02-11%20at%2008.37.31.png?dl=0

Tested with the file at: https://jsonformatter.curiousconcept.com/#

**Comment by szporwolik** [comment]
Thanks and sorry, this was in fact an error at my side ( https://github.com/szporwolik/perun/issues/54 ).
