### ISSUE TITLE
SRS disconnects my Cougar HOTAS after 15 minutes

### ISSUE THREAD

**Issue by LindavK1972** [ciribob/DCS-SimpleRadioStandalone#529]
Dear Sir,

I own a Hotas Cougar and installed it on a Windows 10 machine. It works great in DCS without SRS. When i use SRS, it wil give me the warning that my HOTAS is disconnected ( which it's not ) and the SRS shortcuts will no longer work. It also freezes up DCS to the point i can't use it anymore.
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/6016032/clientlog.txt)

**Comment by ciribob** [comment]
Please join the discord and see the support section, just helped someone (possibly you) with this

I'll close this issue for now
