### ISSUE TITLE
SRS Standalone "race condition" during windows 10 UAC

### ISSUE THREAD

**Issue by jsburwell** [ciribob/DCS-SimpleRadioStandalone#530]
When I start up SRS, windows always prompts me with a UAC window.  If I don't click on "Yes" quickly enough, SRS seems to start up without permissions required to read the config files, etc.

The SRS window will pop up even before the UAC window is dismissed (I have windows 10 set up to _not_ dim screen, but to pop a window instead.

If I wait until SRS pops up and click "Yes" on the window, it will close SRS and re-launch it.  If I click it quickly enough before SRS comes up, it will just come up and be happy.  If I go at a "normal reaction speed", it seems to launch SRS process without permissions to read its config dir as the user.

Favorites and configs are missing when this happens of course because (presumably) it can't read the config files in the install dir.

**Comment by ciribob** [comment]
What are the permissions on the folder where SRS is running from? 

can you also post the clientlog.txt from a "failed" launch?
