### ISSUE TITLE
How to set up automatic induction speech 

### ISSUE THREAD

**Issue by HappyVoo** [ciribob/DCS-SimpleRadioStandalone#535]
Hi:
How to set up automatic induction speech?
Because the speaking button has a 1 second delay and the device button is very heavy, it makes the fingers very painful :(
Or is it possible to individually set which channel is free to speak.
For example, if me fly F16 VHF, you can chat with your team members freely.

**Comment by ciribob** [comment]
There is no hotmic feature other than for intercom

I'd rebind your controls to an easier button
