### ISSUE TITLE
SRS closes automatically when using the Mi-8

### ISSUE THREAD

**Issue by Bishop331981** [ciribob/DCS-SimpleRadioStandalone#536]
As soon as you spawn on a server in the Mi-8, SRS closes automatically. This also happens when you start SRS manually and connect. As soon as you sit in the Mi-8, SRS closes without an error message. 

[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/6292270/clientlog.txt)

**Comment by ciribob** [comment]
That's because you have a very old settings file it seems from the logs

Delete all the .cfg files (global + default) - it'll reset your settings but fix this error you have

**Comment by Bishop331981** [comment]
Okay thx. I delete the files and it works. Thanks for your help
