### ISSUE TITLE
Hornet IFF UFC breaks SRS

### ISSUE THREAD

**Issue by syn111** [ciribob/DCS-SimpleRadioStandalone#542]
Hi,

Messing up with enabling/disabling IFF modes through the Hornet UFC and exiting CLR sometimes breaks SRS.

Can't find an exact way to reproduce but:
1. Settings MODE 3 xpdr code
2. Cycling through MODE 3/C to enable or disable it 
3. Exiting via CLR

Will, at times, result in SRS breaking and "NOT CONNECTED TO SERVER" showing on the overlay. It can be fixed by going into the IFF menu again and messing with the options.

**Comment by ciribob** [comment]
Thanks for the report

If it happens, before you start a new mission (as this clears the logs) - zip the dcs logs folder in saved games /DCs/logs and post here

With that set of logs o can find the issue

**Comment by syn111** [comment]
Hi again,

Very quick steps to reproduce:

1. jump into hot start mission
2. ensure all SRS overlay/GUI are hidden (this seems to be a required step)
3. Press IFF -> select :3C -> CLR -> CLR
4. display overlay and notice that the connection has been dropped

Nothing meaningful appears in the logs

**Comment by syn111** [comment]
Pull request sent with fix for this

**Comment by ciribob** [comment]
Fixed by @syn111
