### ISSUE TITLE
PTT always activates Radio 1 (R-863) in Mi-24P Hind module, regardless of radio selector switch in cockpit

### ISSUE THREAD

**Issue by fhoekstra** [ciribob/DCS-SimpleRadioStandalone#545]
Not sure if this is a known shortcoming of the current implementation and planned, or an actual bug.

The radio selector switch in cockpit (left panel) does not seem to be picked up by SRS, and when pressing PTT button, it defaults to Radio 1 (R-863)

**Comment by ciribob** [comment]
The incockpit selector is not functional in SRS yet - for now use SRS binds

You can always check what each aircraft supports by pressing the ? mark on the SRS radio overlay - nice helper to explain everything

It will be added soon 👍

**Comment by ciribob** [comment]
In the next release 👍
