### ISSUE TITLE
Receiver with radio encryption turned on receives clear transmissions too

### ISSUE THREAD

**Issue by syn111** [ciribob/DCS-SimpleRadioStandalone#550]
Hi,

With radio encryption turned on (i.e. KY-58), the receiver can hear both encrypted transmissions as well as clear transmissions.

A quick glance at the code shows that the CanHearTransmission function returns true whenever a transmission is not encrypted, regardless of the receiving radio having encryption turned on.

Is this intentional?

**Comment by ciribob** [comment]
This is intentional yes. I'm not sure how intelligent the radios are, I'd guess IRL though an unencrypted transmission would come through garbled but didn't want to confuse people further, so this is a deliberate choice

**Comment by syn111** [comment]
Thank you. Although we have no confirmation either, we suspect the IRL behavior is the same. Do you think that this could be added as a configurable client o server side option? I'm happy to contribute with a pull request for that if you want.

**Comment by ciribob** [comment]
Very happy for a pull request if you want to send one

There is another arbitrary limit on encrypted transmissions, they will not be relayed without the receiver who relays them being able to decode them. Just one to look out for

**Comment by ciribob** [comment]
Will be in the next release supporting the Mosquito (whenever that is released) - possibly today if rumours are correct 👍 

Thanks again!
