### ISSUE TITLE
SRS launching when joining a multiplayer in VR causes the mouse cursor to freeze in headset view.

### ISSUE THREAD

**Issue by perardu** [ciribob/DCS-SimpleRadioStandalone#553]
The mouse cursor becomes frozen in VR view when SRS launches joining a multiplayer. The VR view on the monitor shows the mouse cursor moving, but when I put the headset back on the cursor has frozen in the last position seen on the monitor.
I have tried launching SRS first, and bringing each window up and minimising again in different orders to get the DCS monitor view into focus before putting the headset back on but cursor remain frozen. I have had to uninstall SRS to enable DCS to work in multiplayer with a moving cursor.

**Comment by ciribob** [comment]
What exactly is your setup? Headset etc?

SRS has been tested with Rift S (previous headset) and HP G2 (currently my headset)

If its WMR (G2 or similar) - you have to do Windows key + Y (off the top of my head) to unlock the mouse

**Comment by perardu** [comment]
Hello
Thanks for looking into this. The headset is a reverb G2. I was not aware
of the window y selection to release the mouse. The headset has worked fine
on both DCS and fs2020 and other utility programs without having a locked
mouse so I assumed it was associated with SRS program.
I will give it a go.
Thanks again
Andy

**Comment by ciribob** [comment]
You'll see a blue bar at the top with the G2 with the keybind 

If DCS eats the keys - just alt tab and do it on a different window - but you just want the blue bar at the top to go

Think you also have to change the DCS setting that says something like lock mouse to window, or you cant move it

Have a look in VR settings in DCS

**Comment by ciribob** [comment]
Will close for now - assuming the details above fixed it
