### ISSUE TITLE
Fixed channel list for JF17 does not work

### ISSUE THREAD

**Issue by bwanaaa** [ciribob/DCS-SimpleRadioStandalone#566]
As documented here:

https://docs.google.com/spreadsheets/d/1tzd996zJ1t0heZ-t1PpL7vNUIZbXl7pI6De0GThN1Qw/edit#gid=1869108790

The name of the file for a fixed channel list for a JF17 should be R&S M3AR
When pasted into the filename and the weird characters are filtered out you get
R&S M3AR.txt

Any freqs pasted in here should appear as presets in the cockpit, no?
Also, that document shows only 1 radio for the JF17 when in fact it has two.

Is there a way to 'prepopulate' the radio channels in the Jeff?

**Comment by ciribob** [comment]
I've replied on discord. This is correct, the radio referenced is a full fidelity radio and as such has the channels set by DCS
