### ISSUE TITLE
SRS Keeps Disconnecting from any Server

### ISSUE THREAD

**Issue by Synthi97** [ciribob/DCS-SimpleRadioStandalone#575]
SRS is constantly disconnecting from the SRS Server and therefore i lose coms and have to manually reconnect it everytime.
I use SRS 1.9.9.0. 
Is there any workaround for this problem? I couldn‘t find anything on the internet.

**Comment by ciribob** [comment]
For support, please go to the SRS Discord https://discord.gg/Ajzxqxj
