### ISSUE TITLE
Editing favorites cell captures all mouse input

### ISSUE THREAD

**Issue by JurgenvRooyen** [ciribob/DCS-SimpleRadioStandalone#576]
Using the DCS-SRS Client if you edit an existing entry in the favorites table all mouse input is captured.

To repro: 
1. Launch client
2. Go to favorites tab
3. Populate table with at least one entry
4. Double click a field with content (name, address, EAM password)
5. Click outside of the table

Expected: 
Clicking outside the table should defocus and exit cell editing mode.

**Comment by ciribob** [comment]
Fixed in the next release (finally!) 👍
