### ISSUE TITLE
REDFOR Hornet should not have MIDS radios

### ISSUE THREAD

**Issue by destotelhorus** [ciribob/DCS-SimpleRadioStandalone#578]
In DCS REDFOR planes do not have fighter to fighter datalink.
According to BIGNEWY this is because only NATO has Link-16. In accordance with this it would mean that for Hornets, the MIDS radio has to go as well as it runs over L16.

**Comment by destotelhorus** [comment]
Contrary to what BIGNEWY said it might be possible to have REDFOR jets with Link 16. Will investigate.

**Comment by ciribob** [comment]
Sorry not going to take coalition into account for this. It's already a fantasy having a non Redfor Hornet
