### ISSUE TITLE
Bug/Feature Request: Have SRS-DCS client check that it is included in export.lua

### ISSUE THREAD

**Issue by JanJoh** [ciribob/DCS-SimpleRadioStandalone#579]
So, after having an issue with a lot of cursing as to why I could not get a green connected symbol for "Game", I found the following

Because of reasons (my stupidity) the pcall to DCS-SimpleRadioStandalone.lua was no longer in my Export.lua.

Would it not make sense to have the client check this upon startup/connection? It _seem_ like low hanging fruit that could potentially eliminate a lot of frustration... or is this really a "just me" issue :)

**Comment by ciribob** [comment]
I'm actually dropping the export Lua entirety from the next release and using a different method.

I have thought about this but wary about touching export Lua outside of the installer. I was going to add a warning at most but moot now
