### ISSUE TITLE
Add encryption to F15

### ISSUE THREAD

**Issue by MatschbirneLive** [ciribob/DCS-SimpleRadioStandalone#58]
Would it be possible to add encryption to the F15 , since it has a similar device in the cockpit like the A10c( Showed in the attached pic)? This could be done by adding a little extra panel for the overlay. And thanks for the awesome mod !

**Comment by MatschbirneLive** [comment]
Since file attaching doesnt seem to work , here is the pic http://i.imgur.com/rzMDljy.jpg

**Comment by ciribob** [comment]
Yes the plan is eventually to do that - I think it'll be done once i've completed the AWACS / GCI panel which i'll start on after tonights release :)

**Comment by ciribob** [comment]
Fixed in #83 
Release on Sunday likely :+1:
