### ISSUE TITLE
A-10C II Cockpit keys not working

### ISSUE THREAD

**Issue by LupusTheCanine** [ciribob/DCS-SimpleRadioStandalone#584]
As is known A-10C II no longer supports in-cockpit PTT. 

Here are some things I think might be relevant:

command_defs.lua
```
	Plane_HOTAS_MIC_SwitchUp = 572,
	Plane_HOTAS_MIC_SwitchDown = 573,
	Plane_HOTAS_MIC_SwitchLeft = 574,
	Plane_HOTAS_MIC_SwitchRight = 575,
	Plane_HOTAS_MIC_SwitchOff = 576,
```

**Comment by ciribob** [comment]
Unfortunately the switch is no longer animated so I can't read the values unfortunately

**Comment by LupusTheCanine** [comment]
The switch appears to be animated again.
