### ISSUE TITLE
Whitelist more Cougar MFDs

### ISSUE THREAD

**Issue by born2beflyin** [ciribob/DCS-SimpleRadioStandalone#588]
Thrustmaster software supports up to 8 Cougar MFDs connected at once.

InputDeviceManager.cs has only the first whitelisted as "b351044f-0000-0000-0000-504944564944"

I have four connected and would like SRS to recognize my button presses on the 4th (my general button box) for Radio PTT buttons.

All Cougar MFDs would be:

"b351044f-0000-0000-0000-504944564944" // F16 MFD 1
"b352044f-0000-0000-0000-504944564944" // F16 MFD 2
"b353044f-0000-0000-0000-504944564944" // F16 MFD 3
"b354044f-0000-0000-0000-504944564944" // F16 MFD 4
"b355044f-0000-0000-0000-504944564944" // F16 MFD 5
"b356044f-0000-0000-0000-504944564944" // F16 MFD 6
"b357044f-0000-0000-0000-504944564944" // F16 MFD 7
"b358044f-0000-0000-0000-504944564944" // F16 MFD 8

**Comment by born2beflyin** [comment]
I just built it myself in VS 2019 and can verify the following works:

InputDeviceManager.cs

        //devices that report incorrectly but SHOULD work?
        public static HashSet<Guid> _whitelistDevices = new HashSet<Guid>
        {
            new Guid("1105231d-0000-0000-0000-504944564944"), //GTX Throttle
            new Guid("b351044f-0000-0000-0000-504944564944"), //F16 MFD 1 Usage: Generic Type: Supplemental
            new Guid("b352044f-0000-0000-0000-504944564944"), //F16 MFD 2 Usage: Generic Type: Supplemental
            new Guid("b353044f-0000-0000-0000-504944564944"), //F16 MFD 3 Usage: Generic Type: Supplemental
            new Guid("b354044f-0000-0000-0000-504944564944"), //F16 MFD 4 Usage: Generic Type: Supplemental
            new Guid("b355044f-0000-0000-0000-504944564944"), //F16 MFD 5 Usage: Generic Type: Supplemental
            new Guid("b356044f-0000-0000-0000-504944564944"), //F16 MFD 6 Usage: Generic Type: Supplemental
            new Guid("b357044f-0000-0000-0000-504944564944"), //F16 MFD 7 Usage: Generic Type: Supplemental
            new Guid("b358044f-0000-0000-0000-504944564944"), //F16 MFD 8 Usage: Generic Type: Supplemental
            new Guid("11401dd2-0000-0000-0000-504944564944"), //Leo Bodnar BUtton Box
            new Guid("204803eb-0000-0000-0000-504944564944"), // VPC Throttle
            new Guid("204303eb-0000-0000-0000-504944564944"), // VPC Stick
            new Guid("205403eb-0000-0000-0000-504944564944"), // VPC Throttle
            new Guid("205603eb-0000-0000-0000-504944564944"), // VPC Throttle
            new Guid("205503eb-0000-0000-0000-504944564944")  // VPC Throttle

        };

**Comment by ciribob** [comment]
In the next release - thanks!
