### ISSUE TITLE
New version (2.0.0) causes my game to crash after a while in a multiplayer server

### ISSUE THREAD

**Issue by NimrodSegall** [ciribob/DCS-SimpleRadioStandalone#591]
2.0.0 causes me to crash after several minutes in a multiplayer server (~10m). I'm not sure why. Reproduced the issue 3 times. Uninstalled and everything went back to normal. I will verify that older version don't cause this, however, is there a log somewhere I can upload to help you find the issue?

**Comment by ciribob** [comment]
Please follow #dcs-common-issues on the SRS discord - nothing has changed with the DCS integration - but its possible something else is conflicting. If you post all that info I can take a look.

**Comment by ciribob** [comment]
Solved on Discord
