### ISSUE TITLE
Server works on wine on version 1.9.9.0 but not 2.0.0.0 and above

### ISSUE THREAD

**Issue by Sirtz** [ciribob/DCS-SimpleRadioStandalone#599]
Hey,

So the SR-Server was working perfectly on my linux server by just having wine installed and double-clicking the .exe. After downloading 2.0.0.0 or later it does not work anymore giving me dll and .net errors I can't quite manage to fix. I tried installing mono, and various .net versions but no luck. 
Is this problem on me or did something change from 1.9 to 2.0? And is there a way to maybe get it running again in wine?

**Comment by ciribob** [comment]
Nothing major changed on the server between these versions

You can carry on using 1.9 - its backwards compatible and you only lose a small feature to help support music stations

**Comment by Sirtz** [comment]
The issue miraculously fixed itself. Maybe a wine update did it. Thanks!
