### ISSUE TITLE
Possible Bug  AH 64 COLD start Radio Master Volume 

### ISSUE THREAD

**Issue by Kerrac** [ciribob/DCS-SimpleRadioStandalone#600]
Hello, I have seen this Issue myself, but did not dig into it as I thought it is ED related.
When starting the Master Volume Knob is visible at max, but the real in Cockpit Values suggest is in off, because you cant hear the DCS ingame Voice for examble rearming and refueling.
The VOIP of SRS is working though, it just desync so to speak, once you turn the MAster Volume Knob a bit it is sync up again.

Please also see Link to DCs forum:

https://forum.dcs.world/topic/297257-cold-start-radios-master-volume-not-on-max/#comment-4934584

**Comment by ciribob** [comment]
SRS turns the volume up when you enter the cockpit - DCS should sync that

For now - for the Co-Pilot i'll remove the auto volume up
