### ISSUE TITLE
[Need help] F14 Radio won't transmit when "E1' Is after the frequency

### ISSUE THREAD

**Issue by Wamwod** [ciribob/DCS-SimpleRadioStandalone#602]
I know this probably isn't the place to do this but I can't find anything online for this and I'm confused as hell. 
Sometimes when I'm flying the F14 I'll get this "E1" tag next to my radio freq and I can no longer transmit on that radio I'll try to figure out what's causing it, here's what it looks like in the Radio freq. And before anyone says anything, Yes I'm on both, yes I'm on the right freq but that doesn't matter because it doesn't even show "+ TR" next to the radio, it also fixes after you spawn a new plane.
![image](https://user-images.githubusercontent.com/71331178/163252721-5604371b-2914-4b8f-befa-0dc22437e089.png)

**Comment by ciribob** [comment]
For support - please ask on the SRS discord https://discord.gg/Ajzxqxj
