### ISSUE TITLE
Saved Games\DCS\Mods\Services directory is writable by everyone

### ISSUE THREAD

**Issue by DarkWanderer** [ciribob/DCS-SimpleRadioStandalone#603]
Hi. These lines of code:

https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/87a393f87679148180f1b85ffac30e5258f9490f/Installer/MainWindow.xaml.cs#L1171-L1174

sets "writable by everyone" permissions on created directory. This makes SRS dangerous to use - as any malicious code piece can rewrite srs.dll even when launched in limited context, allowig it to distribute malware.

It is basically a level 9 or 10 [CVE](https://cve.mitre.org/). The created directories must rather inherit the permissions from original directories without modification

**Comment by ciribob** [comment]
Thanks! I'll fix in the next release

The directories are always deleted and recreated so any permission changes will apply retroactively as well when people update

**Comment by ciribob** [comment]
Fixed in the latest release
