### ISSUE TITLE
[Bugreport] "Settings" | "Audio" | "Radio x Audio Channel" sliders don't work as expected

### ISSUE THREAD

**Issue by Joghurt** [ciribob/DCS-SimpleRadioStandalone#604]
Not sure if this is only me, but for me the sliders work like this: They have 21 marks and mark 0 to 10 slide the sound from totally left to right ear (so 6 is center), 11 is center as expected, and 12 to 21 are totally left to right again.
In case this really is not only me, maybe a problem with the offset/divider formula?

**Comment by ciribob** [comment]
Definitely a difference

![image](https://user-images.githubusercontent.com/786992/168471306-0dd3a0d4-fde8-4db3-8f25-6a202da412c1.png)

Though its a bit hard to hear 

Screenshot is with the balance set to further Right 

The output is showing Right is "louder" with Left (top) reduced

i'll have a look at some point or possibly reduce the intervals as its pretty hard to hear the difference

**Comment by ciribob** [comment]
I've had another look and refactored this - it'll be a future release as I agree the behaviour isn't great 👍
