### ISSUE TITLE
 Custom audio pipeline for the Intercom - Custom 'end' effect reverts to default all the time

### ISSUE THREAD

**Issue by Floydii** [ciribob/DCS-SimpleRadioStandalone#608]
Issue: 
 Custom audio pipeline for the Intercom - Custom 'end' effect reverts to default all the time

I have added two new intercom tones (INTERCOM_TRANS_Start_new.wav and INTERCOM_TRANS_End_new.wav) to the 'Audio effects' folder in the SRS directory. The appear in the SRS 'settings' menu as selectable tones for the intercom. However, every time I switch away from that profile (AH64 > Default) and back, the 'end' intercom tone has reverted to the generic 'INTERCOM_TRANS_END.wav'.

I've tried changing the end effect, then changing another effect elsewhere to ensure it's 'sticking', but changing profile always seems to revert it.
![image](https://user-images.githubusercontent.com/40154322/167767129-a7aeeb1c-b1f0-47bb-90f6-a24aabae84cb.png)

**Comment by ciribob** [comment]
I couldnt replicate oddly but I've changed something that should solve it for the next release. 👍 thanks for the report
