### ISSUE TITLE
USB audio devices suffer from audio distortion most obvious with mikes

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#61]
Can't really put a finger on this but I have two cases where USB mic distorts audio as soon as the connection is established with server. Preview is not causing it as much nor any. Both USB2 and 3 is tested out and power management settings fiddled with.

Problem is similar to this: https://obsproject.com/forum/threads/possible-fix-for-distorted-usb-mic-audio.27952/

**Comment by ciribob** [comment]
Hmm interesting! I'll try increasing the buffer size I set in the driver as that might fix it. Will increate latency a bit though but only 30ms or so

**Comment by mvee** [comment]
I've been told it helped. This can be closed. :+1:

**Comment by ciribob** [comment]
Great!
