### ISSUE TITLE
[Feature Request] Option to hide transponder in overlay

### ISSUE THREAD

**Issue by fizzle77** [ciribob/DCS-SimpleRadioStandalone#611]
Toward reducing on-screen clutter, it would be great to have the option of not displaying IFF transponder codes in the VR overlay. I’d argue even that this info should be off by default, because it’s used so infrequently.

**Comment by ciribob** [comment]
If you turn off the transponder (totally off) its hidden. Which aircraft are you seeing this in?

**Comment by fizzle77** [comment]
> If you turn off the transponder (totally off) its hidden.

True, which I discovered shortly after creating this issue. And I've also discovered since then that turning the IFF system on isn't actually necessary for IFF queries to function. It's just squawking the codes. So really not a big deal.

> Which aircraft are you seeing this in?

A-10C or F-16

**Comment by ciribob** [comment]
Great, will close
