### ISSUE TITLE
[feature request] More Realistic Radio Simulation

### ISSUE THREAD

**Issue by Syn-Tax** [ciribob/DCS-SimpleRadioStandalone#620]
I've noticed that in SRS when multiple stations are transmitting (on the same frequency) you can hear both (whereas real radios be blocked so you can't hear anything) and that when you are transmitting you can still hear another station that's transmitting (real radios are either in a receive mode or a transmit mode, when you're transmitting you can't receive anything), I think this would really add to the experience (and I don't think it would be too hard to implement, but I get that I'm saying this without having a look at the code)

**Comment by ciribob** [comment]
That's a server side setting

Enable irl tx and Rx behaviour and radios will be half duplex

**Comment by Syn-Tax** [comment]
ahh right, Thanks, I didn't realise that the tx/rx behaviour was already implemented. I would like to see at least the VHF and UHF AM blocking tone to begin with, I'm happy to have a look and see if I can implement it myself. (I don't know enough about FM radios to look at picketing)

**Comment by ciribob** [comment]
Sure! That would be much appreciated

I already have the tones here: https://github.com/ciribob/DCS-SimpleRadioStandalone/tree/master/DCS-SR-Client/AudioEffects 

AM blocking tones 1-3

**Comment by ciribob** [comment]
Not sure if you started on this @Syn-Tax - but now working on this and it should be in the next release, pending some performance testing

**Comment by ciribob** [comment]
Fixed - current Beta now has this feature
