### ISSUE TITLE
[Feature Request?] Preserve awacs-radios.json on upgrade

### ISSUE THREAD

**Issue by LimaJuliett** [ciribob/DCS-SimpleRadioStandalone#624]
I and others modify the client's awacs-radios.json to do custom AWACS overlays, but they're overwritten with the default on every update. We therefore have to copy our awacs-radios.json and overwrite the new one for every upgrade. I would like the updater to leave awacs-radios.json as it was, but I'm not sure if there's a specific reason to overwrite awacs-radios.json on each upgrade. If there is a reason, an option to preserve awacs-radios.json would be appreciated.
Not sure if this really falls under the category of "feature request" so label as you see fit. Thanks for your work, I love SRS and hope to see it continue improving!

**Comment by ciribob** [comment]
Good question - I overwrite it just in case i've made incompatible changes. 

Instead what I can do is have it load an awacs-custom.json (if present) and i'll always leave that in the directory

Then you get the best of both - if there are incompatible changes, you can see them in awacs.json and then patch your awacs-custom.json. How does that sound?

**Comment by LimaJuliett** [comment]
That sounds like a good solution. Maybe I'll write a gui for making custom jsons eventually 🙂 Thanks!

**Comment by ciribob** [comment]
This will be in the next SRS release 👍 

Create a file named awacs-radios-custom.json - this will persist between upgrades

**Comment by SuperSpiderMonkey** [comment]
@ciribob amazing work you and the team have done for years.

I've found a bug with this new feature. The custom JSON is loaded and then immediately overwritten by the default JSON file.

`                else
                {
                    Logger.Info($"No Custom {AWACS_RADIOS_CUSTOM_FILE} present - Loading {AWACS_RADIOS_FILE}");
                }

                radioJson = File.ReadAllText(AWACS_RADIOS_FILE);
                awacsRadios = JsonConvert.DeserializeObject<RadioInformation[]>(radioJson);`

**Comment by ciribob** [comment]
Well.... Crap. Sorry about that! I was sure I'd tested it too.

Absolutely please send a PR and I'll add to the next release

Thanks for the message!

**Comment by ciribob** [comment]
https://github.com/ciribob/DCS-SimpleRadioStandalone/pull/641/files PR here for fix 👍
