### ISSUE TITLE
[Question] Extracting radio transmission from server with an external script

### ISSUE THREAD

**Issue by Fallcrim** [ciribob/DCS-SimpleRadioStandalone#625]
Hey guys, I am not used to C languages so I want to ask here. I would like to ask if there is a way to receive the same audio data the server receives (with the server running) to process it for different purposes. So I usually work with python and I had the idea to put a specific radio frequency onto a web stream and play it via a Discord Bot. 

Kind regards

PS: Englisch is not my native language so please correct any linguistic mistakes

**Comment by ciribob** [comment]
Sure - SRS is written in C# which is fairly easy to learn / follow along.

Look at the SR-ExternalAudio codebase - that shows you the basics of connecting to a server, and sending (not receiving) but you can see from there how you'd receive the audio.

A single UDP packet contains the audio as well as metadata, which you'll need to decode using Opus. 

You will need to understand TCP and UDP networking - but the UDP packet is well documented in the code, and pretty straightforward to use

You may need to build a jitterbuffer - but if you're ok with some interruptions and you have a good connection to the server, you can ignore / not worry about it

**Comment by ciribob** [comment]
Closing for now - feel free to open and ask more in the future or get me on Discord
