### ISSUE TITLE
A-10C radio encryption is on FM band rather than VHF

### ISSUE THREAD

**Issue by fizzle77** [ciribob/DCS-SimpleRadioStandalone#630]
The A-10C manual states that they KY-58 can encrypt comms on the UHF or VHF radios. In practice however setting the switch to C/RAD 2 encrypts the FM radio, not VHF.

I'm not sure if this is a DCS or SRS issue, but to be honest I'm hoping it's SRS because that would make it more likely it'd be fixed this decade. 😬 Any chance this is SRS behavior, and that it could be investigated?

The relevant section of the A-10C manual:
![a10-radio-encryption-manual](https://user-images.githubusercontent.com/42720583/198412706-f52b9041-b779-4dbe-9817-62b6aec02890.png)

**Comment by ciribob** [comment]
I'm trying to find the email, discord or github issue - but SRS changed to using the **VHF FM** rather than the VHF AM from feedback from an SME

**Comment by ciribob** [comment]
Can you find any other supporting docs or details?

**Comment by ciribob** [comment]
Closing for now - if you find another source happy to switch
