### ISSUE TITLE
DCS-SRS + DCS-ExportScripts not seem to be working

### ISSUE THREAD

**Issue by JS312RAF** [ciribob/DCS-SimpleRadioStandalone#642]
Hello.
I can't seem to get the SRS working with [ExportScripts](https://github.com/s-d-a/DCS-ExportScripts).
When the ExportScripts is in the Export.lua, SRS doesn't connect the Game plugs.
The SRS Client still connects to an SRS server on a DCS server join, but only shows the Ctrl+Shift+ESC message after that.
Any idea what might be wrong, please?

These are my only lines in Export.lua.
`dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]])
pcall(function() local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]]); end,nil);`

**Comment by ciribob** [comment]
The lua is wrong - you need pcall on a new line.

If it still doesn't work it's not anything SRS can fix - it's up to the other mod to correctly set up the hooks so it can work together with others

SRS and tacview work fine together for example

dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]]) 

pcall(function() local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]]); end,nil);

**Comment by JS312RAF** [comment]
That was just me making a new line at the wrong place when writing the message.
It is correct in my Export.lua.
But I found the solution, the issue was the ";" at the end of the pcall function. Without it it works flawless.
So my Export.lua is:
```
dofile(lfs.writedir()..[[Scripts\DCS-ExportScript\ExportScript.lua]])
pcall(function() local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]]); end,nil)
```
