### ISSUE TITLE
clients-list.json is constantly written to

### ISSUE THREAD

**Issue by MikeHump** [ciribob/DCS-SimpleRadioStandalone#643]
Of course clients-list.json should only be written to when there's new information to add. But even with 0 connected clients its modification date is always *now*.

**Comment by ciribob** [comment]
Sorry I don't follow - why is that of course?

The file is written by a timed job and written regardless of any changes or not.

Happy for a PR from others but I'm not going to change that behaviour as it stands

**Comment by MikeHump** [comment]
Sigh... 

If this is representative of your attitude towards optimization there there must be a LOT in this app that can be improved.

The timed job should note if there's been any changes, and only THEN should it stomp on the file. Writing to a file constantly for no reason is just wasteful of resources. (And it shouldn't be a timed job, it should be fired by the player joins/leaves.)

**Comment by ciribob** [comment]
Sure, there's loads that can be improved! No argument there.

However, I have limited time, and as I said above it's not something I'd likely spend time in the short term. 

Happy for a PR though, it's open source for a reason and always keen for some help.

On the attitude front - please bear in mind this is a volunteer free time project and be a little less condescending in your message, you will get more positive responses

**Comment by MikeHump** [comment]
Jesus Christ, you fucking suck!

**Comment by ciribob** [comment]
Phew! Thanks for making my point again on how you should communicate. That's not the way to do it.

I'll be reporting this to github and banning you from any further comments due to your approach to comms. 

Hope you have a nice weekend!
