### ISSUE TITLE
Hercules addition not working?

### ISSUE THREAD

**Issue by RafaPolit** [ciribob/DCS-SimpleRadioStandalone#654]
Good afternoon. 

Thanks for this incredible piece of software.  Hands down the single most important add-on for any MP server.

I'm having trouble with the Herc radio and SRS.  I still get 3 FC3 radios that I need to change with bound controls over at SRS, and it does not show (as the video in #648

Is there something else I or the server host need to do in order for this to work from the MCDU?

Thanks.

**Comment by ciribob** [comment]
Sorry thats a mistake on my part - it'll be fixed in the next release 👍 

Glad you like it!
