### ISSUE TITLE
[Feature Request] F-16 UHF / VHF text in DED filled if transmitting

### ISSUE THREAD

**Issue by sandpatch** [ciribob/DCS-SimpleRadioStandalone#659]
I have no idea if it's even possible. I just saw that when transmitting internally in DCS, the F16 DED UHF and VHF text get filled in to indicate transmission.

It would be very cool if it would be possible here as well. See attached screenshots. Here it is transmitting on both frequencies but it is individual.

The "filling in" responds to the controls:
- Transmit switch - UHF (VOIP)
- Transmit switch - VHF (VOIP)

![F16 UHF VHF OFF](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/23266782/6a85f5cb-7b5b-41a7-b3f3-67b9421c43f8)
![F16 UHF VHF transmit](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/23266782/757eb7da-c5e0-4d68-94c0-6ecb9ee89ff2)

**Comment by ciribob** [comment]
Unfortunately not possible as there is no animation argument I can hook
