### ISSUE TITLE
[Bug]Join a new server SRS hang

### ISSUE THREAD

**Issue by Handsome1080P** [ciribob/DCS-SimpleRadioStandalone#664]
pic
![image](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/13675031/cf510491-1f6d-4f2a-a850-3628204377db)

**Comment by Handsome1080P** [comment]
GUI logs:
![image](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/13675031/e989147c-3850-4a95-ab06-ae6ea7861e19)

**Comment by ciribob** [comment]
Please post on the SRS discord for support - I try not to use github for support as its much tricker to communicate
