### ISSUE TITLE
Connected, export seems to load. (DCS launched as admin)

### ISSUE THREAD

**Issue by mvee** [ciribob/DCS-SimpleRadioStandalone#67]
Ok, here's next one, not mine either. Newest version does not pull radio data. DSC is launched as admin (tried this one myself, no problem with my install). Registry removed and reinstall, no luck. Older version works just ok. Firewall switched off. Could this be ISP related, so maybe option to select multi/broadcast (might be too much for normal user)? See attached.

[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/380414/clientlog.txt)

[dcs.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/380412/dcs.txt)

**Comment by ciribob** [comment]
Hmm can you ask them to manually replace the DCS-SimpleRadioStandalone.lua from here:
https://raw.githubusercontent.com/ciribob/DCS-SimpleRadioStandalone/master/Scripts/DCS-SimpleRadioStandalone.lua

?

The UPDATE From: player Coalition: 0 means that UDP broadcasts are being received, but only the one from the GameGUI from some reason...

I can always switch back to multicast if needs be :)

**Comment by mvee** [comment]
Should that file differ from the last release. I can't find the difference. Tested and not working. localhost server doesn't work either

**Comment by mvee** [comment]
d'oh, if localhost is not working either it proly is not ISP :P silly me

**Comment by ciribob** [comment]
Its only this line that may differ: https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SimpleRadioStandalone.lua#L174

If it doesnt, thats good. :)

Try changing this: https://github.com/ciribob/DCS-SimpleRadioStandalone/blob/master/Scripts/DCS-SimpleRadioStandalone.lua#L16

To true:

SR.unicast = true

**Comment by mvee** [comment]
![image](https://cloud.githubusercontent.com/assets/17532699/17086448/e9471b34-51fa-11e6-9f71-35baaf3e3a02.png)
worked!

**Comment by ciribob** [comment]
Great! :)
