### ISSUE TITLE
Running under Steam and proton.

### ISSUE THREAD

**Issue by cymax95** [ciribob/DCS-SimpleRadioStandalone#670]
Hello

I hope you are all doing well. 
Since SRS is very widely used for multiplayer in DCS. I have been trying to get it to run inside the prefix without success. I am able to get OpenTrack, the head tracking software to work though.

I see there have been some mentions of some people being able to get it to work but I am at a loss. I am new to winetricks or protontricks and would appreciate guidance.
When I run SR-ClientRadio.exe I receive the following error:

0f8:err:module:fixup_imports_ilonly mscoree.dll not found, IL-only binary L"SR-ClientRadio.exe" cannot be loaded
00f8:err:module:LdrInitializeThunk Importing dlls for L"C:\\users\\steamuser\\Documents\\DCS-SimpleRadioStandalone-2.0.8.6\\SR-ClientRadio.exe" failed, status c0000135

**Comment by ciribob** [comment]
See the other issues for Linux - should help

https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/621#issuecomment-1255474316
