### ISSUE TITLE
F-15E Radio Volume Knobs

### ISSUE THREAD

**Issue by robohunterx** [ciribob/DCS-SimpleRadioStandalone#674]
The F-15E's radio's start slightly "on" at the rough 1 o'clock position, however, if you twist them to the "off" position aka fully counter clockwise, the displayed radio volume in the SRS interface shows as -11% which in turn still allows audio to come through. It's also pretty much impossible at that point to roll the volume knob CW back to 0% to mute it.

The initial cold and dark state
![image](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/19507632/1101b223-d3e8-497b-9a41-85e504f0217a)

Turning the radio knobs fully CCW to "Off"
![image](https://github.com/ciribob/DCS-SimpleRadioStandalone/assets/19507632/fa71bf3b-9859-467f-a6f2-ab31eb04aa88)

**Comment by ciribob** [comment]
Thanks for the report! Fixed in the next release
