### ISSUE TITLE
Overlay not on top

### ISSUE THREAD

**Issue by splash99** [ciribob/DCS-SimpleRadioStandalone#68]
Hi Ciribob, I'm using a three monitor configuration and I could not get the overlay shows on top of DCS World. I have to press Alt-Tab to show the overlay but when I return to DCS (by clicking on the screen or pressing Alt-Tab again), the overlay is hidden. This happens in DCS GUI as well.

In previous versions I would swear that worked...

Anyway, thanks for your excellent application.

**Comment by splash99** [comment]
I don't know the reason, but today it's working flawlessly. It's always on top. So from my part this issue is solved.

**Comment by splash99** [comment]
I have to open the overlay "after" running DCS. If I open the overaly and later DCS, it is not on top.

**Comment by ciribob** [comment]
wow thats very odd... not sure why that would happen!

**Comment by splash99** [comment]
Yes, it's very odd but the workaround is opening DCS before.

**Comment by ciribob** [comment]
This new update will have an overlay toggle hotkey so hopefully toggling it will work to bring it on top

**Comment by splash99** [comment]
Many thanks. It works well at all times. I have no problems of any kind.

**Comment by ciribob** [comment]
Awesome!
