### ISSUE TITLE
Change installer wording

### ISSUE THREAD

**Issue by dMARLAN** [ciribob/DCS-SimpleRadioStandalone#680]
Every time I install my brain has a melt down whether to click yes/no and end up reading the whole prompt again (feels backwards, I expect yes to continue), I suggest instead of using yes/no I'd suggest using words such as Change/Continue.

I'd put up my own PR but not sure if I'm dumb or missing permissions (getting 403)

`Resources.resx` + comment in `Resources.Designer.cs` seem to be the right spots based on a brief search.
```<data name="MsgBoxChangeText" xml:space="preserve">
    <value>Do you want to make changes? 

Change - Pause install and make changes

Continue - Run with previous install path and install scripts as default.

If unsure - hit Yes!</value>
```

**Comment by ciribob** [comment]
I will do this - not forgotten! I confuse myself with the wording 👍
