### ISSUE TITLE
Possible bug with newest version 2.1.0.0, MIDS volume?

### ISSUE THREAD

**Issue by Joghurt** [ciribob/DCS-SimpleRadioStandalone#689]
There's this line in the diff https://github.com/ciribob/DCS-SimpleRadioStandalone/compare/2.0.9.1..2.1.0.0 coming from DCS-SR-Client/Audio/Providers/ClientAudioProvider.cs that says "vol = vol / 0.30f;". I haven't tested it yet, but it seems mathematically wrong to "lower the volume by 30%" as stated in the comment - maybe you want to do something like "vol = vol * 0.70f;"?

**Comment by ciribob** [comment]
Comment is wrong (rather than the code) but it's supposed to lower the cockpit ambient effects but it's wrong anyway as that lowered all the volume, not the ambient cockpit one 

I'll have a look, thanks!

**Comment by ciribob** [comment]
Tested and fixed - thanks!

**Comment by Joghurt** [comment]
Thank you for all your work!
