### ISSUE TITLE
[Feature request] Configurable Stream Deck keypresses in Controls

### ISSUE THREAD

**Issue by Heidana** [ciribob/DCS-SimpleRadioStandalone#698]
Currently none of the keypress actions from Stream Deck being recognized by SRS.
I tried following:
- the built in System / Hotkey
- the Super Macro [Bar Raider]'s Keystroke PTT
with no success.

**Comment by TaeruAlethea** [comment]
I was unable to reproduce the issue described when using a Stream Deck Mk2 and Stream Deck+.
Both worked when emulating a keyboard press.

**Comment by ozdeadmeat** [comment]
Are you running both the streamdeck app and SRS as Admin?

**Comment by Heidana** [comment]
> Are you running both the streamdeck app and SRS as Admin?

I tried in the past with no success - I recently got an update and now it seems to be fixed! Closing the issue!
