### ISSUE TITLE
[ENHANCEMENT] AUTO volume balancing to mic and output! :)

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#70]
A part of code/script that will actually balance all output from all other clients evenly to one level (with a slider like output, but it will put all clients to one SAME specific dB level (the script should compare the output of the client and adjust automatically to a by script as "normal" defined level)

**Comment by ciribob** [comment]
This is surprisingly tricky so I won't look at this for a while

**Comment by Nossarian** [comment]
Would it be helpful to think of it in two parts:

Implement max dB output 
Implement min dB output

Slicing it into smaller vertical chunks may make partial implementation easier

**Comment by ciribob** [comment]
I've tired a few libraries but it introduces too much latency. Will keep investigating.

**Comment by ciribob** [comment]
For now - Not easily solvable
