### ISSUE TITLE
SRS-Server Autoconnect message to client

### ISSUE THREAD

**Issue by Maverick87Shaka** [ciribob/DCS-SimpleRadioStandalone#705]
As far as I can understand, the way that autoconnect works basically is send on chat the host details, and the client will connect.
This is fine I'm creating a script to block player on selecting the slot, and I'll use the chat to notify to the player eventually what was the error status, I would like to control SRS auto connect message order, to make it appear before my custom error message. 
Actually the srs auto-connect is the last one, and it may be confusing for player that will not read the message before the srs line, where actually there is the reason for blocking that particular slot.

So the question is, it's safe to change the SRSAuto.onPlayerChangeSlot to onPlayerTryChangeSlot to have the SRS message before? and also, it's necessary to send the message every time the player is changing slot? not enough on server connect?

Thanks

**Comment by ciribob** [comment]
Thats exactly how it works - SRS reads the text chat and looks for the connection string pattern.

You can definitely try it in onPlayerChangeSlot - should work fine 

Its usually safer to send it on change slot, as if they lose connection the easiest way to get it to reconnect is just swap or join a slot

**Comment by Maverick87Shaka** [comment]
Removed (Commented out) the part of SRS auto connect onPlayerChangeSlot and it works fine for our need just leaving the onPlayerConnect function.
We don't see any abnormal behavior, so we'll take like this for our server.
Thanks for confirm the expected behavior.
