### ISSUE TITLE
[ENHANCEMENT] GeoTiff and line of sight calculation, feat. a real-calculated invisible and a "fake" dumb deactivated real AWACS!

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-SimpleRadioStandalone#71]
Some resources I found:

for .NET not sure is useful:
http://bitmiracle.com/libtiff/
http://build-failed.blogspot.de/2014/12/processing-geotiff-files-in-net-without.html

for C# (?)
https://github.com/stefangordon/GeoTiffSharp

1.)

GeoTiff and line of sight, how will GCI be affected, will airplanes automatically receive and increase any transmissions they receive? (To relay information to the next aircraft, for example GCI, who is based at let's say on one specific airfield, wants to talk to pilot A, who is behind a mountain, but there is pilot B who has line of sight to both GCI and pilot A...
Will "pilot B"s aircraft automatically increase all receiving transmissions (only on team X channels of course, not enemy team's radio channels) or will only specific aircraft types function as "relay stations" aswell?)

2. )

I'd suggest that team (both teams location fixed for whole round) red GCI is based in Anapa-Vityazevo airfield and team blue's GCI in Vaziani airfield ("safe" airfields until one team pushes the other team that far off Caucasus... :D ) .

3. )

And please also make the team's captured comms arrays and airfields functioning as relay stations! :D (I'd say excluding FARPs and cities)

4. )

So if NO aircraft relay system, then, only, basically the client (OR SRS server) has to check line of sight to all other team's aircraft, airfields & comm arrays, and only those with direct line of sight (server updating LOS ID's every 250ms and only during transmission to not cause too high server CPU load on the 51 pilots, 21 airfields and 6 comm arrays, 78 objects the server will have to calculate LOSs every 250 milliseconds!)

5. )

Then the question is, shall the receiving aircraft/client check for LOS or the transmitting aircraft/client? (if only the transmitting one it would not stress all other clients!)

6. )

Or, to balance CPU load amongst all pilots (unless the SRS server has VERY powerful CPU), maybe the transmitting aircraft only checks which aircraft, airfields and comm arrays in LOS, and from there the receiving clients take over (transmitting client will transmit the ID's of the LOS-aircraft, airfields and Comm arrays to the SRS server, which will then send the ID's to the clients, which then compare their own position to the ID's and thereby calculate LOS. :) )

7. )

And we can "fake" two radio-AWACS per team (just for radio ranges, nothing with radar) two so one can refuel while other is doing the radio-AWACS mission) the radio-AWACS' positions calculated on the SRS server, as several positions from a line, to make it very basic) and place two AWACS aircraft (without actual mission) per team in the BlueFlag mission file, just to fly the route for realism ;) (And being able to be shot by enemy team! Then SRS server could take the radio-AWACS (as relay) offline for 1 or 2 hours :D Will add immersion and variety!)

8. )

Basic calculation:

we could say the 2 radio-AWACS will be at 1 position every 1 km, position updating every 5 seconds/5000 ms (AWACS travelling @ 720 kph=200m/s) so 2 values every 5 seconds / 5000 ms that the SRS server would calculate and send to the connected clients (OR the clients "request" that information from the server themselves?)

Positions for teams (could be optimized for two/four/six CPU server cores for load balancing! 1 core/ 2 cores/3 cores/CPU-threads team red calculations and the other 1, 2 or 3 cores/CPU-threads server cores team blue calculations! :D :tada: :zap: )

red:

Team red's radio-AWACS flying a straight line (back and forth for between Anapa City and Temryuk (north of Anapa), 40 km flight distance, so those are 40 positions on team red.

blue:

Team blue's radio-AWACS flying a straight line between Marneuli and Giorgitsminda Sagarejo (50 km flight distance), 50 km flight distance, 50 positions on team blue.

So 90 possible positions (all pre-calculated), of which only 2 positions (1x red 1x blue) every 5 sec/5000 ms. :+1: 

9. )

So what we need to know is which server CPU, how many cores/threads and then we can decide how far we can stress the SRS server and how much work we can split up to the clients (not too much to clients as they already have low FPS in DCS... )

**Comment by ST6Daniel** [comment]
So I created two gifs what it would technically look like (red dots the positions, updating every 5 seconds/5000ms)


Shown at 4x speed (1250 ms frames)

Team Blue animation:

http://gifcreator.me/viewgif/20160731-19-HMxXHnePEfs8UHwA-q689PH

Team Red animation:

http://gifcreator.me/viewgif/20160731-19-HMxXHnePEfs8UHwA-7msi0v

**Comment by Nossarian** [comment]
If possible, try to make this feature not directly linked to Operation blue flag. I know it's getting the most use there, but having it require a lot of mission editing in order to function would be looked well upon by other groups. If it's necessary to have scripts running, a tutorial and/or a copy of the script should be provided to users.

**Comment by ciribob** [comment]
Thanks for the detailed message Daniel! Going to close for now as LOS is in using a different method and will have a think about awacs :)
