### ISSUE TITLE
SRS doesn't detect mic input

### ISSUE THREAD

**Issue by NorseManGef** [ciribob/DCS-SimpleRadioStandalone#712]
I once had SRS running flawlessly through wine. It still does, ignoring the fact that I cannot speak on radio. After an update a while back, SRS doesn't seem to be able to receive audio from my mic. Other than that everything runs perfectly, so I don't believe it's a wine issue as there are no errors in the logs.

**Comment by NorseManGef** [comment]
Update: Moving back to version 2.0.9.1 fixes it.

**Comment by ciribob** [comment]
Will close for now then as it appears solved

**Comment by vsTerminus** [comment]
Rolling back to 2.0.9.1 did not fix it for me. 

Instead, I found that Wine was at fault. I have several different versions of Wine kicking around in Lutris, so I tried a few:

- Wine 10.0 does not work
- Proton 9.0 does not work
- Proton 8.0 does not work and also crashes the app
- GE-Proton9-23 does not work

- **GE-Proton8-32 works**
- **wine-ge-8-22 works**

(This is with SRS 2.1.1.0, running on KDE + Wayland, on Gentoo Linux)\

So it kind of seems like something in Wine/Proton 9+ is the problem. There might be some environment parameter or something we could set that fixes it, but for the moment I'm just going to run SRS with wine-ge-8-22.

Also worth noting, if you run SRS and DCS in the same prefix they need to be using the same version of Wine/Proton. You can't launch two different versions in the same prefix at the same time. So you probably still want to run SRS in its own prefix. (It communicates with SRS via sockets anyway, so there's no need for it to be in the same prefix)

**Comment by Neburski** [comment]
> Rolling back to 2.0.9.1 did not fix it for me.
> 
> Instead, I found that Wine was at fault. I have several different versions of Wine kicking around in Lutris, so I tried a few:
> 
>     * Wine 10.0 does not work
>  ....
> 
>     * **wine-ge-8-22 works**
> 
> 
> (This is with SRS 2.1.1.0, running on KDE + Wayland, on Gentoo Linux)\

I'm using Hyprland on Arch linux and I have tried:

1. wine-staging 10.0 (from the command line) following the instructions from your other post here: https://github.com/ciribob/DCS-SimpleRadioStandalone/issues/621#issuecomment-2628837996. While the client starts in this case, there are clearly some issues, drop down lists are fully black and I'm unable to make the microphone work.
2. wine 10.0 (from the command line), but the same results as with wine-staging 10.0
3. wine-ge-8-22 through lutris 5.18, here the drop down lists work as expected and the microphone also works in preview. (I had to use the preview button a couple of time)

Could you maybe clarify in you other post if for wine 10.0 the microphone works or not and if it works, how did you make it work?

**Comment by Neburski** [comment]
> You do not need to install dotnet48 anymore,

Yes, indeed. I didn't install dotnet48 in my prefix and all seems to work fine with wine-ge-22 and wine-ge-26.
