### ISSUE TITLE
Feature Request: Server control over effects & panning

### ISSUE THREAD

**Issue by sevn10** [ciribob/DCS-SimpleRadioStandalone#713]
My servers are currently using Special K's [DCS Server Bot](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot) and the music plugin that is part of it. What would be nice as a quality of life improvement is if SRS Server could control the client effect settings, like turning off Radio Rx Effects and panning if they're set to off and centered on the server side for a specific frequency or frequencies. That way users would not need to manually go adjust those settings in SRS Client each time they tune into a music station where they would like to listen in full fidelity.

**Comment by ciribob** [comment]
You can do part of that already - list the frequencies for your music in the global frequencies on the server and the SRS effects will be skipped automatically on the client on that frequency / frequencies only
