### ISSUE TITLE
Overlay is cut off

### ISSUE THREAD

**Issue by thryckz** [ciribob/DCS-SimpleRadioStandalone#72]
I can only see the first two radios on the overlay. I tried numerous installs and uninstalls. I don't know where the configuration files are for the program but I need to delete them as they are most likely the culprit for this.

**Comment by thryckz** [comment]
Fixed!
It's stored in the registry under
HKEY_CURRENT_USER\SOFTWARE
Just delete the two tables.

**Comment by ciribob** [comment]
This is hopefully fixed in this release: https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.1.5.0

If not there is a reset button as well now to reset the overlay :+1:
