### ISSUE TITLE
CH-47 FM1 radio set as AM

### ISSUE THREAD

**Issue by scrupeus** [ciribob/DCS-SimpleRadioStandalone#723]
version 2.1.0.9

Modulation set incorrectly for the ARC-201 (FM1) in the CH-47

DCS-SimpleRadioStandalone.lua, line 2239 redefines `_data.radios[2].modulation` as 0 (it's correctly set as 1 on line 2231)

(there are a couple other duplicated lines in that block of code - `volMode` defined three times, `encMode` twice)

**Comment by ciribob** [comment]
Thanks - was in a bit of a rush and i'll tidy it up in a hotfix
