### ISSUE TITLE
Feature Request: Add Microsoft Azure AI Speech Support to DCS-SR-ExternalAudio.exe

### ISSUE THREAD

**Issue by Maverick87Shaka** [ciribob/DCS-SimpleRadioStandalone#728]
As per title, it will be nice to have also Microsoft Azure Voice rather than only GoogleTTS service available.

Final goal is to use Azure voice with DCS Simple Text To Speech (DCS-STTS) script.

I can try to work on it ;)

**Comment by ciribob** [comment]
Thank you very much for this! In the release today 👍
