### ISSUE TITLE
SRS disconnect DCS Game after release slot in DCS

### ISSUE THREAD

**Issue by Smuli34** [ciribob/DCS-SimpleRadioStandalone#733]
SRS seems to disconnect from the DCS Game when releasing a slot or changing the plane -- Unless SRS is the last line in the export.lua file. This is an issue e.g. with WinWing SimAppPro that should be the last line in the export.lua file.

I know this may be hard to reproduce but I have been using quite lot of hours to fix this after the latest DCS update.  In my setup SRS works fine only when its command line is the last one in DCS export.lua.

**Comment by ciribob** [comment]
Thats actually an issue with the other Exports not playing nicely - if you put SRS at the end it tries it best to fix everyone else so they work so SRS is always recommended to be at the bottom. 

Tacview is well behaved - so SRS can be before or after Tacview
