### ISSUE TITLE
Feature Request: Linux/Mono-based version

### ISSUE THREAD

**Issue by f4l0** [ciribob/DCS-SimpleRadioStandalone#76]
A linux or mono-based version would be great.

I'll check what we need to do to achieve this...

**Comment by f4l0** [comment]
Sadly WPF is not supported by Mono thus a Linux version is far away...

**Comment by ciribob** [comment]
When i've got through the major work and protocol changes I'll do a build that should run on Mono that'll be command line. Won't be for a few months at least. It should be pretty easy to port the server protocol to something like Java with Netty which you're welcome to try :)

**Comment by f4l0** [comment]
Wuarg Java :-1:  :-)
I'm a C/C++ guy :+1:

**Comment by ciribob** [comment]
you can do it in that too :)

**Comment by FalkF** [comment]
Can we reopen this one?
I am willing to look into it but I can't promise success :)

**Comment by ciribob** [comment]
Sure! Good luck 👍

**Comment by TheZoq2** [comment]
I'd love to see this happen since DCS works quite well in proton https://www.protondb.com/app/223750.

I tried running SRS in proton, but it crashed on start. I'll have to investigate further to see if I can get some actionable debug info
