### ISSUE TITLE
Add a Multicrew radio

### ISSUE THREAD

**Issue by MatschbirneLive** [ciribob/DCS-SimpleRadioStandalone#80]
Since there is gazelle multicrew coming soon(TM) it would be awesome to enable a multi crew radio. Here is a way how could it be done. You could add a 4th invisible radio where every aircraft has its own frequency( Something like 1000.01, 1000.02 etc...). In my own expierince the intercom between the pilots and crew members is a constant hot mic, so transmitting on the 4th radio could be done with a not logic gate or something like that: `If transmitting then transmit else transmit on the 4th radio`.The intercom (this may vary on the aircaft and radios) also is unfiltered wich means you can hear the engine/rotor noises in the background. You could also add a option to disable the intercom for people who want to use thier personal teamspeak or any other von program. Also in realife, when the pilot holds down the radio switch, the copilot also transmits on the frequiency so he has to shut up. This might be tricky to implement and isnt that needed but it would be neat. Hope this was a bit helpful.

**Comment by ciribob** [comment]
Already underway :)

For the Gazelle it'll be a PTT for the intercom and normal radios as I'd rather save bandwidth so not have a constant transmission if it can be avoided

**Comment by ciribob** [comment]
Fixed in #83 

Ready for Gazelle Multicrew :+1:
