### ISSUE TITLE
Client cannot receive audio if they do not have PTT bound

### ISSUE THREAD

**Issue by Nossarian** [ciribob/DCS-SimpleRadioStandalone#81]
I am not entirely aware of the situation the User was in, but in the process of getting a friend set up to run SimpleRadio on BlueFlag, we came across the issue (after 2 days) that, in order for a Client to receive audio from the server, they MUST have a PTT bound.

**Comment by ciribob** [comment]
ah its not that they must have a PTT bound, its that they must transmit audio before they can hear.

Transmitting audio registers you on the server but in the next release it should actually do it automatically for you by basically tapping transmit for you on connection.

For example, you could jump in an L-39 and press the transmit button on the throttle which would would then register you

Sorry for the trouble!

**Comment by Nossarian** [comment]
Ah, excellent. I will check for that on the next release.

**Comment by ciribob** [comment]
Fixed in #83 

Reopen if not! :+1:
