### ISSUE TITLE
Radio Modifiers do not take priority if they are pressed and a radio without a modifier uses the same base keybind

### ISSUE THREAD

**Issue by Nossarian** [ciribob/DCS-SimpleRadioStandalone#82]
Radio Modifiers do not take priority if they are pressed and a radio without a modifier uses the same base keybind

For example, with the following keybinds set up, it is impossible to switch to radio 2 or radio 3 because the keybind for radio 1 overrides the modifiers for 2 and 3

R1 - W
R1Mod - <null>
R2 - W
R2Mod - LAlt
R3 - W
R3Mod - LCtrl

If R1Mod has a binding, then the modifiers will work as intended. 

My own personal setup has the TM Warthog Mic switch as the base keybind for each radio, and the two states for the TM Warthog Pinkie Switch as the modifiers for radio 2 and 3.

**Comment by ciribob** [comment]
I see you're point, thats confusing!

My worry is if I fix this, it will still be confusing as say you're holding W + LALT for radio 2 you then release LALT  a fraction before you release W, it'll then switch to radio 1... 

I'll have a think, not sure what I should do with it as the keybind system is a bit tricky

**Comment by ciribob** [comment]
Fixed in #111
