### ISSUE TITLE
Feature Request: Allow Guard selection for CA/FC3 radio stack

### ISSUE THREAD

**Issue by HomeFries94** [ciribob/DCS-SimpleRadioStandalone#87]
With the Combined Arms/Flaming Cliffs radios automatically monitoring guard, it stands to reason that CA/FC3ers should be able to reply as well.  I recommend a mechanism such as selecting the "G" on the radio to switch the transmitter channel to Guard, and then pressing it again to return it to its original frequency.

**Comment by Nossarian** [comment]
Is this a function of real aircraft? a button to switch to the Guard frequency by default?

I'm not aware of this functionality, most of the Hi-Fidelity ships must switch to 243 (for blufor Guard) manually.

**Comment by HomeFries94** [comment]
I can't speak for VHF AM/FM (I have more experience with UHF), but most UHF tactical radios have a Guard setting.  Sometimes it's one of the options on the power knob (e.g. off, tr, tr+g, g like the Huey), and sometimes its on a manual/preset/guard selector (like the Mirage 2000C).  Both the F-15C and A-10 have this feature on the UHF, so for this radio it at least makes sense.

**Comment by Nossarian** [comment]
I know they have the function to listen to guard, but not to automatically xmit on the guard frequency. I will also look into it.

**Comment by ciribob** [comment]
Not sure about this, my worry is it would encourage / make it easier to spam the guard frequency which would annoy everyone?

**Comment by ciribob** [comment]
Fair enough, I'll have a think how best to do it. :)

To start with it'll likely just be a button that sets your frequency to guard and you'll have to manually tune back to where you were which isn't ideal obviously but to do anything much more complicated might require quite a few changes. I'll have a look.

**Comment by ciribob** [comment]
Implemented in next release 1.7.0.1
