### ISSUE TITLE
Feature Request: IP "phonebook" to allow selection of preset servers

### ISSUE THREAD

**Issue by HomeFries94** [ciribob/DCS-SimpleRadioStandalone#88]
Please add a feature to enable saving a server's IP to a favorites list (along with a description) so that it is an easy evolution to change between servers without having to remember individual IPs.

[I did something like this for EF2000 Reloaded.](http://img.photobucket.com/albums/v637/madgonzo/EF2000/IPX%20client_zpsyqqf1wub.jpg~original)

**Comment by Nossarian** [comment]
This seems reasonable. I could even imagine implementing it (poorly) with a csv file.

I don't know C or C++ very well, but I know it would be very doable in Groovy/Java

**Comment by HomeFries94** [comment]
It's pretty easy.  I used a tab delimited text file and paired one IP with one description.  Granted, I did this in VB6, but implementing it with a CSV is not implementing it poorly.

**Comment by ciribob** [comment]
Its on the list now. Thanks! :)

**Comment by ciribob** [comment]
Partially solved by new Auto-Connect feature but this is still on the list :)

**Comment by ciribob** [comment]
@GylesBates is now going to have a look 👍

**Comment by ciribob** [comment]
Fixed in #147 Will be in next release

@GylesBates - Hero to the people 👍
