### ISSUE TITLE
1.2.0.0 - Could not hook into DCS, complete removal and install of DCS-SR folder was required

### ISSUE THREAD

**Issue by Nossarian** [ciribob/DCS-SimpleRadioStandalone#92]
1.2.0.0 - Could not hook into DCS, complete removal and install of DCS-SR folder was required

Editing the Export.lua in the Saved Games\DCS\Scripts did not fix it either.

My settings were saved, however, so it's not a huge problem.

**Comment by ciribob** [comment]
That sounds more like maybe the scripts weren't up-to-date in the export folder? Not sure what else could cause that... sorry.
