### ISSUE TITLE
Support: Cannot assign keys for Gametrix ECS

### ISSUE THREAD

**Issue by noroot** [ciribob/DCS-SimpleRadioStandalone#94]
Cannot assign keys for Gametrix ECS (This is usual USB device) Settings doesn't recognise any button from this device, joystick at the same time works fine.

**Comment by Nossarian** [comment]
Does the device work in DCS? Is it a unique USB device in the controls editor in DCS?

Do you have a custom profile that you enabled after running DCS-SR?

**Comment by noroot** [comment]
Yes it does. It works with DCS and with TeamSpeak. It is unique standalone usb device in controls editor in DCS. Have no custom profiles enabled.

**Comment by ciribob** [comment]
Please post your SimpleRadio logs as that gives me all the device descriptions. 

I had to be quite restrictive to stop problems with the x52/x55 Joysticks so only Joysticks, Gamepads and Keyboard are accepted as DirectX input devices. That device is a "Joystick" so it should've been detected. As its not is must be reporting as something else...

**Comment by noroot** [comment]
Here it is
[simple-radio-logs.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/441338/simple-radio-logs.txt)

**Comment by ciribob** [comment]
Will be fixed in #96
