### ISSUE TITLE
Bind Server to a different Port - Client side enable a different port to be used

### ISSUE THREAD

**Issue by virtual812** [ciribob/DCS-SimpleRadioStandalone#95]
For instances where one might need to provide a SR-Server for multiple different DCS servers, the ability for 1 x SR-server to offer different 'rooms' would be great.

SR-Server could be configured with say 3 'rooms'
DCS Public 1 
DCS Mission 1
DCS Mission 2 

SR Clients could select a room in their client depending on what server they join.

A possibly easier short term alternative might be to give to give the ability to specify listen ports to SR-Server.exe and then run multiple instances side by side.

**Comment by Nossarian** [comment]
This could potentially lead to creating multiple servers for one dcs mission, which would defeat the purpose of moving away from teamspeak. 

I also can't imagine this would be a valid use case. Yes it would make managing severs easier, but you could also just install simple radio on each server. 

There should never be a way for simple radio to turn into another teamspeak in my opinion. This could do exactly that

**Comment by virtual812** [comment]
> This could potentially lead to creating multiple servers for one dcs mission, which would defeat the purpose of moving away from teamspeak.
Not sure what you mean by that?

> There should never be a way for simple radio to turn into another teamspeak in my opinion. This could do exactly that
Not suggesting anything like that.

I'm in a position where it would be ideal to provide a SR server for 2 x DCS servers.
Whilst i'm happy to leave 1 machine on 24/7 i'm reluctant to do so for 2 machines.
It would be ideal to run SR-Server at least twice in my case.
Is there any way we can achieve that?

**Comment by Nossarian** [comment]
Why not install it on both machines the dcs servers are running on? By logical reasoning, a server would only be up if the relevant dcs server is running?

**Comment by virtual812** [comment]
I don't have access to the servers

**Comment by Nossarian** [comment]
Then I question why you would be hosting multiple Sr servers, but the request does seem reasonable, of not super edge case. 

I would recommend this get implemented after the "auto join Sr based on dcs server" the feature

**Comment by virtual812** [comment]
> I would recommend this get implemented after the "auto join Sr based on dcs server" the feature

I didn't bother mentioning it but i did see this feature req.
It is a very good idea, and would compliment my idea well.

**Comment by Nossarian** [comment]
My main concern is the potential for another teamspeak like service, where everyone just joins the room they want to be in, instead of being forced into the same one and using radio freqs

**Comment by virtual812** [comment]
No, not my intention.
The term room might have been a bad choice on my part.

When i said room i meant for 1 room in SR to be equal to 1 machine DCS server, and never more than 1 room per DCS server (or as you say you head off in a TS direction, which is undesired).

Exchange the word 'room' for whatever is more appropriate.

Ultimately, 1 x SR instance or 'room' per DCS server
I have a 32 thread 64GB box that, once i have a DX11 card in it may one day run multiple DCS servers.
This is where 2 instances side by side would be great, or even one instance that can host 1 'room' per DCS server.

**Comment by Nossarian** [comment]
The only real solution here is connecting on different ports or running a
second virtual machine, which would be required with multiple dcs servers
anyway, unless you manage to run two clients with different ips on the same
box somehow

**Comment by virtual812** [comment]
Plan is to use different ports for the clients, but same IP.

**Comment by ciribob** [comment]
Added an option to change the port binding is a good idea, I'll see if I can get this in the next release as it shouldn't be too hard

**Comment by virtual812** [comment]
Running SR-Server when an instance is already running caused the second one to crash on Win10
You guys know what you're doing, and probably already know how to deal with this.
I'd try to lend a hand but can hardly get an LED to blink on an Arduino at the moment.

**Comment by ciribob** [comment]
No worries, that's because it can't bind to the port because it's already in use.

I'll have it handle that better so it uses an ini file where ever the server is so to run two versions you'll just have the server in two different folders with their own separate configs :)

**Comment by virtual812** [comment]
That sounds perfect.

This probably sounds mad, but i have never used the client.
I first setup the server 2-4 weeks ago and then spent a lot of time dealing with some health issues of a family member.
I'm tidying up my desk as i speak and hope to fire up DCS later tonight or on Thursday.

This will be my first time installing SR as a user.
Thinking ahead, will any changes be required to the client to specify a port, of will it just accept the usual host:port syntax?

**Comment by ciribob** [comment]
sounds reasonable to me, I hardly fly at the minute as I'm programming radios! :)

for the client there will be an update as well but it'll just use standard syntax as you describe. If there is no port it'll just assume the standard SRS port

**Comment by ciribob** [comment]
Will be part of #96 by the weekend
