### ISSUE TITLE
Ka50 short wave radio

### ISSUE THREAD

**Issue by etcher3rd** [ciribob/DCS-SimpleRadioStandalone#99]
The Ka50 actually has three radios.

In addition to the R800 and R828 radios, it also has a short wave radio (labelled SW on the SPU9).

That SW radio is a preset UHF radio used to communicate at very short range.

Is there any chance you might consider implementing it somehow in SRS ?

**Comment by ciribob** [comment]
Do you know what it's preset too? If so its an easy addition :)

**Comment by etcher3rd** [comment]
Unfortunately, no.

I guess any kind of placeholder UHF frequency high up in the spectrum could do, as the SW is supposed to be very, very short range (a few kilometers) only.

We're using UniversRadio at the time being, and the SW radio is implemented as a 600MHz and something UHF. It's very useful as an always-available means of communication between Ka50 assets, as long as we are within 10 kilometers or so of each other.

**Comment by ciribob** [comment]
I'll go with 600MHz now, its easy to add but there won't be a volume control for it unless you can find where it actually is in the cockpit or I can tie it to another radios volume.

Thanks for the info!

**Comment by etcher3rd** [comment]
There is no volume control for that specific radio as far as I know anyway :)

Thank you for your amazing work !

**Comment by ciribob** [comment]
No worries :)

Fixed in #101
